### ISSUE TITLE
xScheduler  three issues

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#855] opened 2017-05-07 14:35 UTC
Set up a library playlist.  This playlist are the songs that will play when the show is not.  Set up a schedule to run 24 hours and set it to priority 3.  Checked the shuffle and loop boxes and  during play it did not shuffle, let it run all night and it just played in order.  Next morning I clicked the end gracefully.  It did not end, but then started to shuffle.  

Tried to set up a show schedule while the library playlist was playing where the show schedule was to start a few minutes after creation of the show schedule.  Gave it priority 5.  It did not stop the library playlist and play the show.  

Closed out the program.  Reloaded, created a show schedule to start a few minutes after creation.  It was to run about forty minutes.  It did start..  When I clicked on the Library playlist (it was showing stopped) with the idea in mind that it would start after the show ended.  The audio from the show playlist started playing noticeably slower.

**Comment by keithsw1111** [comment] 2017-05-07 20:19
Can you send us your xschedule file so i can see exactly how you set it up.

**Comment by JoelDearing** [comment] 2017-05-08 00:16
sent a reply to your direct e-mail

**Comment by keithsw1111** [comment] 2017-08-13 20:51
Middle issue should be fixed in .23. Last issue maybe fixed. I cannot reproduce the first issue.

**Comment by keithsw1111** [comment] 2018-01-02 04:13
Joel ... can I close this?

**Comment by JoelDearing** [comment] 2018-01-02 14:56
I recall in the Wed night zoom call that you had found a way to fix the songs playing slower issue when going from playlist to playlist.


I have not d'loaded that version yet, but yes, please close the bug report and if it pops up again, I will advise.


Joel




-----Original Message-----

**Closed** 2018-01-02 21:02 UTC
Labels: Bug - Trivial
