### ISSUE TITLE
Random flicker in polyline strings in v22 not present in v20

### ISSUE THREAD

**Issue by SarahDods** [smeighan/xLights#3535] opened 2022-11-08 02:50 UTC
**Describe the bug**
I upgraded from v20 to v22.  When I re-rendered this sequence (Mistletoe), the AC net lights (AC net light left shrub and AC net light right shrub) now both flash, sort of in time with the musical beat.  This doesn't happen in v20.  I rolled back to confirm.  These are set up as polylines representing shop bought led net lights

**To Reproduce**
Open the sequence in v22, render and play.  Problem throughout - example at 4.8-5.0 second mark
[2022 Mistletoe Net light v22 problem.zip](https://github.com/smeighan/xLights/files/9957199/2022.Mistletoe.Net.light.v22.problem.zip)

**Expected behavior**
AC net lights should not come on at all - they're not sequenced.  Have checked those lines are blanks.  It doesn't happen in v20

**Screenshots**
![v22 bug report screenshot](https://user-images.githubusercontent.com/109121211/200462550-a5693c97-44bf-42de-a7dd-3610048034ec.jpg)

**Versions (please complete the following information):**
 - OS: Windows 10 Pro
 - xLights version 22 upgraded from v20 (v21 crashed on my laptop)

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by AzGilrock** [comment] 2022-11-08 04:36
I wanted to look into this but my debugger is not cooperating today.  It keeps detaching the process whenever I try to step over a line.  Anyways the problem is the PolyLine model in front of those models is starting at channel 4 instead of 1.  You should be able to fix all this by changing the Lights/Node from 3 to 1 on both the House Lights Uphill and House Lights Downhill models.  If you really want Lights/Node to be 3 then you would need to wait till we fix this bug then put it back.  Its really a display only option.

**Comment by AzGilrock** [comment] 2022-11-08 04:38
By the way when you change the Lights/Node from 3 to 1 you will not see the channels numbers update immediately but they will.  If you do something like drop another model or close/reopen the program you will see those numbers update.  I tried to fix that refresh issue before but its kinda a fundamental architecture thing that's not easy to fix without causing a lot of extra recalculations and slowing everything down.

**Comment by SarahDods** [comment] 2022-11-08 05:35
Hi Gil,

Thanks for looping back.  The ones that are coming on when they shouldn't
are AC relays, so single strand, single colour.

House lights aren't the problem - unless you've found another one.  The
house lights are LPD6803 strip, which has sets of 3 pixels controlled as a
unit.  Is there a better way of setting those up?

Let me know if there's more I can send or show to help.

Sarah

**Comment by SarahDods** [comment] 2022-11-08 05:41
Thanks for this and other emails.  I've just been into the preceding model,
and found it was set up as ws2811 not lpd6803.  I'll upgrade again and see
if that fixes it.  Sorry if problem is incompetence at my end - I hadn't
thought to look at the model before it. 😣

Noted on the other solution above - I think you're saying that I can just
show each group of 3 as a single pixel and that might also fix it.  I'll
update you shortly when I've tried both.

Sarah

**Comment by SarahDods** [comment] 2022-11-08 05:52
Hi again Gil,

OK.  Confirmed your fix works - changed House Lights down to 1 Light per
node, and it fixed it.  I've made the House Lights appearance square and a
bit bigger to compensate, and they look OK. Protocol being corrected from
ws2811 to lpd6803 didn't make a difference (I guess it shouldn't for screen
display).

Thanks for your help, and I'll stay upgraded :-)

Sarah

**Comment by SarahDods** [comment] 2022-11-08 22:53
No worries - thanks for looping back, and finding me a fix.  xLights is the
most awesome software, and really appreciate the work you all do to keep it
updated and progressing.

Sarah

**Comment by AzGilrock** [comment] 2022-11-10 15:55
The fix is checked in for next release

**Closed by AzGilrock** 2022-11-10 15:55 UTC
