### ISSUE TITLE
Controller Visualiser doesn't display correctly on surface book with 200% scaling (default)

### ISSUE THREAD

**Issue by craiz** [smeighan/xLights#1549] opened 2019-05-10 00:46 UTC
The controller visualiser does not display correctly on a Windows device with HiDPI and default scaling of 200%.  In my case it is a Surface Book with 3000x2000 resolution display and 200% scaling.
![image](https://user-images.githubusercontent.com/8462504/57495294-58a47a80-7282-11e9-9fe8-e553d7adb1f1.png)

**Comment by keithsw1111** [comment] 2019-05-11 07:27
This is pretty much going to happen until one of the windows developers gets a HDPI monitor and can test it.

**Comment by PeteMatthews** [comment] 2019-07-29 00:38
Turns out I've got the right kit to reproduce this, and think I've got a fix in progress. It's worth noting that while this is the most broken aspect of the interface I've found, the whole thing looks a bit funky and not-quite-happy with DPI scaling on (which I know Windows isn't exactly famous for handling well in it's own right).

I'll see if I can fix up the immediate issues (Controller visualisation and the text on the splash screen are particularly annoying), but may see if I can fix bits of the interface piecemeal too (assuming people are interested)

**Comment by dkulp** [comment] 2019-07-29 00:42
wxWidgets has a bunch of DPI fixes that I don't think Keith has picked up yet.    We should, at the least, move to 3.1.2 and see if anything improves.  I know from the wxWidgets dev lists, there are constant discussions about DPI things on Windows and improvements being made.  Since the version of wxWidgets we are using is over a year old now, it wouldn't surprise me if things improved just by grabbing the newer version.

**Comment by PeteMatthews** [comment] 2019-07-29 00:51
Fair enough - I noticed a lot of talk about forthcoming stuff in 3.2.0, but I'll admit I didn't go check 3.1.1..3.1.2. Maybe I'll leave it for now then, but keep an eye out for a 3.1.2 shift - Am happy to come back and retest/fix up as best I can when it lands.

(Is someone pursuing the 3.1.2 shift, or is that something that could be usefully picked up/played with? Am interested in learning my way around the source, so if there are tech-debt-type or menial tasks that are on the "todo someday" list, I'm happy to take a look if it'll make people's lives easier...)

**Comment by dkulp** [comment] 2019-07-29 00:54
Well, on the Mac, I'm using the latest git code as of two days ago so pretty much something close to 3.1.3.

**Comment by computergeek1507** [comment] 2020-03-14 14:03
This should be fixed now

**Closed by computergeek1507** 2020-03-14 14:03 UTC
