### ISSUE TITLE
Long Range Visualizer Pixel count error on multi-string models

### ISSUE THREAD

**Issue by ljbrusta** [smeighan/xLights#2705] opened 2021-07-11 23:06 UTC
MegaTree 8 Strings – spreads across 2 Long range 4 port cards. Each on their own long range port. Smart remote A on each card looks great, however when you add another model to this multi sting layout it calculates the number of pixels on that stream incorrectly using the total model count instead of the individual stream count and then will not upload to the controller.  

See attached screenshots.
[Longrange smart receiver calculation error..docx](https://github.com/smeighan/xLights/files/6797802/Longrange.smart.receiver.calculation.error.docx)

**Comment by keithsw1111** [comment] 2021-07-13 02:05
I cant reproduce the problem. Can you doo a tools package logs with the configuration in the error state so we can see what else you may be doing.

**Comment by ljbrusta** [comment] 2021-07-13 04:04
On this layout. Both port 1 and port 13 exhibit the issue (hinkspix controller). Though only port 1 shows in error due to total pixel count. Port 13 shows 650 but there are only 150 and 200 between A and B receivers. 
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/6805813/xLightsProblem.zip)

**Comment by keithsw1111** [comment] 2021-07-13 04:10
We need @computergeek1507 to chime in here. The hinkspix has a number of rules and constraints so I am not even sure that is a valid configuration ... so i dont want to 'fix' anything until we are clear about what is broken.

**Comment by ljbrusta** [comment] 2021-07-13 04:27
makes perfect sense thanks for looking.

**Comment by computergeek1507** [comment] 2021-07-13 15:09
My understanding is the only way around this is to use individual universes per string/model. The internal data buffer of the controller is continuous per "data stream" or receiver port i.e 1A, 1B, 1C. This means the internal controller channels of Mega Tree Sting 1 must be channel 1-1200 and then the chromaflake must be channels 1201-1298. Mega Tree Sting 2 would be channels 1299- 2499. The only way I know to "weave" the channels like this is to setup individual start channels for each string port of the tree and skip the channels needed for the chromaflake. To "fix" this, the auto layout models mode would need to be smart enough to assign channels per individual strings of a model. I personally thought this was too complicated to add so I have not persuaded it.

**Comment by ljbrusta** [comment] 2021-07-13 20:38
Yes that does makes sense. It is not hard to work around it just would have been convenient to weave in a few candy canes here and there with the extra space. Layout layout layout so many options. Thanks!

**Comment by computergeek1507** [comment] 2021-09-15 13:15
this should be fixed with https://github.com/smeighan/xLights/commit/4e397130df9e7f6cd363be26f3ba38e58553b0dc

**Closed by computergeek1507** 2021-09-15 13:15 UTC
