### ISSUE TITLE
Crash when importing LSP files - 4.1.5

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#269] opened 2015-06-15 01:30 UTC
Hello,

I have included files in the drop box location below.
I split the import into two steps (LSP_ByStrandMap1) and (LSP_ByStrandMap2)
The first one worked fine .

After saving , exiting and starting xl again , I opened the saved seq and tried the second import.
After a while received the message 
"An unexpected exception occurred . Press Abort to terminate the program , 
Retry to exit the program normally and Ignore to try to continue."

Aborted  and retried the process again . Second time round clicked Ignore.
After a few minutes , tried to save and received the messages
10:54:48: Can't create thread (error 0: the operation completed successfully.)
10:54:48: Can't set thread priority (error 0: the operation completed successfully.)
10:54:48: Can't create thread (error 0: the operation completed successfully.)
(repeated many times)
Then 
Xlights error
File dialog failed with error code 
 
Note - in the second mapping , the source and target strands for some of the models do not tally exactly for exactly , for example 
RightVertIn-B3B4 maps to 2 strands in LSP (B3 and B4) - so I just picked one. 
Similarly RightVertOut-C2C3.
Also , some in LSP may be an extra pixel or two (eg 26 in LSP) where as in xl I have split into (25) and a null pixel model (1).
Was not sure if the mapping was then by channel number and would ignore any channel numbers not found...

I also specified MTREE in the target( xl) , but for this seq there is nothing in the source LSP file .
(Was hoping to be able to reuse the maps )

Am happy to work around , if I know what of the above is causing the crash....
 
https://www.dropbox.com/s/0ky9qihci3d84ha/LSPImportCrash.zip?dl=0

**Comment by tucsonlights** [comment] 2015-06-15 04:43
Are you running windows 8.1? I am getting the same issue importing HLS Files.

**Comment by gerry4** [comment] 2015-06-15 04:54
Yes I am on 8.1 , but I suspect that is not the issue as have been importing in bits and pieces for a while now and have imported LOR and LSP previously. In this case (second example) I did a few things differently whereas in previous imports (including the first) I only did  two or a few models at a time and the models aligned perfectly between LSP and XL.

**Comment by tucsonlights** [comment] 2015-06-15 05:03
I pull up my event viewer and see that there is an issue with NTDLL. D.Kulp was the point person for importing lsp, HLS and lor so hopefully we can get this figured out.

**Comment by MrChristmas2000** [comment] 2015-06-15 12:06
I am running Win7 64bit Home Prem.

**Comment by dkulp** [comment] 2015-06-15 19:05
Wasn't able to reproduce the crash on the Mac.   However, xCode does say the memory usage with the sequence loaded is over 3GB.   I'm wondering if you're hitting the 32bit limit since the Windows version of xLights is a 32bit app.    (Mac version is 64bit)  I have no idea what the steps would need to be to get a 64bit version on Windows.   That said, as I mentioned in the other post, changing the effects from node level to model level would help a ton.

**Comment by gerry4** [comment] 2015-06-15 23:08
Okay - I'll give it a shot.
 
I thought I was doing it at the highest level , but will try one level higher.
 
Also happy to try splitting into smaller groups to import.
 
Will try later in the day today my time


Gerard
 
Date: Mon, 15 Jun 2015 12:05:28 -0700

**Comment by tucsonlights** [comment] 2015-06-16 03:21
Dan, can you make xlights large address aware so it can utilize up to 4gb in 64bit os?

**Comment by dkulp** [comment] 2015-06-16 03:27
I would have no idea how to do anything like that on Windows.   xLights is 64bit on the Mac and can use all the memory it needs there.

**Comment by tucsonlights** [comment] 2015-06-16 06:46
So I found a way to allow xlights to utilize up to 4gb of ram by turning on Large address aware in .exe file. Which stopped the crashing on importing. The problem now is that xlights after importing is at 3.2-3.5 gb in the task manager. I still have more channels to add, which after effects are added will bring me well over 4gb. Any suggestions. I have about 5000 channels.

**Comment by gerry4** [comment] 2015-06-16 08:45
Do you need to import them all as 'effects' ? What I have been doing (still experimenting) is importing the previous LSP sequences as a data layer . This brings a much smaller image in , but you cannot edit the LSP component. You can however , add models to the same sequence and add effects against the models  (ie combination of old and new).
In my case - I have 8 LSP sequences of last year and earlier this year , but I have added several new things such as a mega tree , P10 panels , floods etc  this year..
So I will define these as new items models and seq them in xlights but in the same seq have whatever previously done eg house outline , stars , arches etc from LSP as a data layer.
Not sure what would happen if I 'overrode ' say the arches  and also sequenced them. I think it ca be done , but have not tried,

**Comment by gerry4** [comment] 2015-06-16 10:22
Attached are links to 3 files
https://www.dropbox.com/s/xlxftj7i848jzfm/LSP_ByStrandMap3?dl=0
https://www.dropbox.com/s/zfugtjx3jgsiqxo/LSP_ByStrandMap4?dl=0

I am adding to the seq that I successfully imported 15 models .

I used the first mapping document above (ie map3) to map at the model level , but I don't think it did anything . Not sure if this is what you meant ...
I waited 20 mins and there was no completion message or any error message
if it should have worked and would have made a difference I will try again.

I then used the second mapping document (map 4) , same effects by mapped at the strand level . it completed after a few minutes , but when I went to save it , it crashed , was not able to complete creating the debug zip in the normal folder , but I went and got it from the temp folder and zipped it and attached.
So would appear that importing this way (ie as effects) makes the file too large and I did not have that many channels  last year . 

https://www.dropbox.com/s/oceee0qzsbw4mzo/xLights_dbgrpt-13252-20150616T200401.zip?dl=0

**Comment by dkulp** [comment] 2015-06-16 12:08
The suggesting is to do exactly what I already recommended (and doing for my own sequences):  after importing the effects for a model, go through the model and create model level effects that match the imported effects and delete the effects on the Nodes.   Replacing 2000 (85x24) effects with a single effect will save a ton of memory and render a LOT faster and have a much smaller xml file.   It's worth spending the time to do it.

**Comment by MrChristmas2000** [comment] 2015-06-16 12:27
I have reached the same conclusion that Dan has stated. 
Also importing to a 25ms NC sequence will also create too much data for the 32bit Windows version of NC to work with.
Breaking down a large element into multiple LSP sequence parts will help with importing all the data. However once you do get NC to import an element you will have to do the conversion to the model level at that point because I have found that saving, closing NC and attempting to reopen a newly imported sequence does not work either and that has nothing to do with the importer. I think until NC is ever converted to 64bit for better memory handling capability that the conversion process into NC will still be a multiple step process.

**Comment by tucsonlights** [comment] 2015-06-16 13:24
Dan, is all this in the video you made about importing? I am completely new to xlights 4.0 and am fuzzy about going from nodal effects to model.

**Comment by dkulp** [comment] 2015-06-16 19:27
4.1.6 has two things that may help: 
1) memory limit increased to 3GB (default for 32bit apps is 2GB, so 50% more) via the linker setting

2) A new "Promote Node Effects" option on the model popup menu.   This will search through the node level On and Color Wash effects and if the same effect is on all the nodes at the exact same times, it will be removed from the nodes and placed on the Model.   That would be a starting point for doing the manual conversions as it picks out the easy stuff.   The next step would be for you to identify the areas that are spirals or chases or similar and put the appropriate effect on the model that would match the node level stuff and then delete the node level effects.

**Comment by tucsonlights** [comment] 2015-06-16 19:32
Thanks so much Dan. I really appreciate the work you, Gil, Sean et al. do.

**Comment by MrChristmas2000** [comment] 2015-06-16 19:54
Will test sometime today. Thanks for your hard work on this.

**Comment by gerry4** [comment] 2015-06-16 22:46
Thanks Dan . I too will test in the next day or so - echo the thanks above.

**Comment by gerry4** [comment] 2015-07-06 01:29
Hi,
Should we close this issue now as I don't think that anything else should be done re this item.

**Comment by tucsonlights** [comment] 2015-07-06 01:55
Sure.

**Comment by stevegiron** [comment] 2015-07-06 02:51
Closing per previous comments.

**Closed by stevegiron** 2015-07-06 02:51 UTC
Labels: Bug - Minor
