### ISSUE TITLE
3D Layout Screen missing model

### ISSUE THREAD

**Issue by Dazzled1** [smeighan/xLights#1200] opened 2018-08-12 06:02 UTC
Using Mac 10.13.5, 2018.27 3D in the layout screen one model Arch Front 1 is missing from the display. I have tried all GL settings and it still will not show. It works perfectly well in 2018.27. I have attached a video and packaged a small sequence to help.

Stuart W
https://vimeo.com/284563690/108296a8e6
[Amazing Grace Techno 3D.zip](https://github.com/smeighan/xLights/files/2280758/Amazing.Grace.Techno.3D.zip)

**Comment by Dazzled1** [comment] 2018-08-12 11:05
Here is the Log file
[3D Layout no Arch.zip](https://github.com/smeighan/xLights/files/2280906/3D.Layout.no.Arch.zip)

Stuart

**Comment by dkulp** [comment] 2018-08-12 19:31
It doesn't fix this, however, if you use the properties on the left to adjust the "X1" , the arch does appear.   There is a range from around 93-94.5 ro so where it disappears.  Not sure what is going on with it yet.

**Comment by Dazzled1** [comment] 2018-08-13 00:05
I adjusted the x1 to 96 and the arch appeared. Thanks for the tip Dan and the problem with the sequencer grid is fixed as well in 27b, great job.

**Comment by AzGilrock** [comment] 2018-08-25 04:56
Dazzled can this one be closed?

**Comment by Dazzled1** [comment] 2018-08-25 21:09
Hi Gil
I'll close this one as Dan's work around fixed my problem. It only really effects a model that has the X1 range that Dan mentioned and I maybe the only person with that setting. It may pop up again when more people start converting over to 3D.

Stuart

**Comment by AzGilrock** [comment] 2018-08-25 21:12
I don't think we want to close it.  Sounds like a real problem.

**Comment by Dazzled1** [comment] 2018-08-26 00:03
Ok Gil sounds good

**Comment by dkulp** [comment] 2018-08-30 16:51
I'm going to close this.   I re-downloaded the zip and the arch is now displaying fine.  Not sure what would have fixed it, but I now cannot reproduce it.

**Closed by dkulp** 2018-08-30 16:51 UTC

**Comment by Dazzled1** [comment] 2018-08-31 11:44
No problem Dan sounds good.
