### ISSUE TITLE
SMPTE/MTC (Professional Time Code)

### ISSUE THREAD

**Issue by tbetgeorge** [smeighan/xLights#1941] opened 2020-02-17 16:42 UTC
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when 
I was asked by many pros if xLights had time code built in so we could make it part of a larger system. 
**Describe the solution you'd like**
Add SMPTE integration so xLights can be used to be triggered remotely along with other pro gear (fireworks, GrandMA boards, theme park hardware)

**Describe alternatives you've considered**
Triggering manually

**Additional context**

**Comment by AzGilrock** [comment] 2020-02-17 16:46
I thought xScheduler already had that feature.  It wouldn't be in xLights because its not a show player.

**Comment by tbetgeorge** [comment] 2020-02-17 16:51
This is a good point. Do you know where I can find the feature? I did search quite a bit for it but I’m probably missing it right in front of my face 😦

Tom BetGeorge

**Comment by AzGilrock** [comment] 2020-02-17 16:55
I'm not at home to browse the menu but I did search the code base here for SMTPE and it seems to show up in a few of the xSchedule files and I thought I remembered it being asked for in the past so I'm thinking Keith added it.  Maybe he will chime in later.

**Comment by keithsw1111** [comment] 2020-02-17 17:28
I have a Smpte version but it needs testing.

Sent from my iPhone

On 18 Feb 2020, at 3:42 am, tbetgeorge <notifications@github.com> wrote:

﻿

Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when
I was asked by many pros if xLights had time code built in so we could make it part of a larger system.
Describe the solution you'd like
A clear and concise description of what you want to happen.
Add SMPTE integration so xLights can be used to be triggered remotely along with other pro gear (fireworks, GrandMA boards, theme park hardware)

Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.
Triggering manually

Additional context
Add any other context or screenshots about the feature request here.

**Comment by jholmes09** [comment] 2020-02-18 14:51
I have used MTC multiple times and a friend of mine (@shmorgan) even committed some code  to make it more stable. @tbetgeorge I will be happy to show you how it works. 

I know @shmorgan and I want to test the LTC version soon.

**Comment by shmorgan** [comment] 2020-02-18 15:16
I know we would be very interested in testing this!!! Keith, let me know how you want to proceed!!

**Comment by shmorgan** [comment] 2020-02-18 15:19
Right now, xSchedule supports sync via Midi Time code or Artnet Time Code (Artnet time code is not stable last time I tested it), it would be great to have native Timecode built in.

**Closed** 2020-04-05 08:12 UTC
Labels: Enhancement
