### ISSUE TITLE
I am would like to help improve xlights. 

### ISSUE THREAD

**Issue by jwfoody** [smeighan/xLights#1798] opened 2019-10-31 01:11 UTC
I am importing my LORedit files to xlights. And they are not working with xlights. I understand that this is a beta version. 

[Loredit to Xlights.zip](https://github.com/smeighan/xLights/files/3791685/Loredit.to.Xlights.zip)

**Comment by keithsw1111** [comment] 2019-11-01 13:38
Going to need some specifics about what the problem is.

**Comment by jwfoody** [comment] 2019-11-01 21:05
In lor the all section, lights as required with different light colors. In xlights the all section, lights white the coloring is different. The sequence seems to work fine just the coloring is the main concern. It renders very fast, which is nice. Good work on that.

**Comment by keithsw1111** [comment] 2019-11-01 23:06
Yeah ... I am afraid that is worlds away from the level of detail I need.

Which specific effect is having the issue. Starting at what time on what model ... do you have a video of it working correctly in LOR vs not in xLights. Can you share a minimal sequence that just shows the problem.

Giving me a huge sequence and saying it isnt right but no specifics is like saying I lost something in a haystack and I want you to find it. It would be almost impossibly hard even if i knew what I was looking for.

Specifics please or we will need to close this issue until you are able to provide them.

**Comment by jwfoody** [comment] 2019-11-03 04:50
xlights 18.50 sec - whole sequence, the color wash effect, the All model. lor 18.50 - whole sequence, the color wash effect, All model. Here is some video and my grid config import for lor, and network data for xlights. Hopefully this gets you what you need. If not please let me know. Thanks.



[Loredit to Xlights.zip](https://github.com/smeighan/xLights/files/3801249/Loredit.to.Xlights.zip)


[Video.zip](https://github.com/smeighan/xLights/files/3801253/Video.zip)

**Comment by keithsw1111** [comment] 2019-11-04 08:05
From the LOREDIT file these are the effects:

        <effect startCentisecond="1850" endCentisecond="1860" startIntensity="0" endIntensity="100" settings="Mix_Average|0|0|full|20|lightorama_colorwash:FFFFFFFF,1:full,full|lightorama_none::|0" />
        <effect startCentisecond="1860" endCentisecond="1875" intensity="100" settings="Mix_Average|0|0|full|20|lightorama_colorwash:FFFFFFFF,FF919191,1:full,full|lightorama_none::|0" />
        <effect startCentisecond="1875" endCentisecond="1890" intensity="100" settings="Mix_Average|0|0|full|20|lightorama_colorwash:FF0000FF,FF000091,1:full,full|lightorama_none::|0" />
        <effect startCentisecond="1890" endCentisecond="1905" intensity="100" settings="Mix_Average|0|0|full|20|lightorama_colorwash:FFFF0000,FF910000,1:full,full|lightorama_none::|0" />
        <effect startCentisecond="1905" endCentisecond="1935" intensity="100" settings="Mix_Average|0|0|full|20|lightorama_colorwash:FF00FF00,FF002300,1:full,full|lightorama_none::|0" />

The only problem I can see here is the colour wash should be changing colour and isnt ... is that the SPECIFIC issue you are hinting at

**Comment by keithsw1111** [comment] 2019-11-04 09:17
Try this version: https://www.dropbox.com/s/ocny6wlotgmlebn/xLights64_2019_63.exe?dl=0

**Comment by jwfoody** [comment] 2019-11-07 22:30
Hey thanks that fixed my problem. You can close me out for now.

**Closed** 2019-11-08 01:36 UTC
