### ISSUE TITLE
Lights don't turn off when sequence is stopped 

### ISSUE THREAD

**Issue by jcmarksafb** [smeighan/xLights#97] opened 2015-03-23 19:51 UTC

**Comment by AzGilrock** [comment] 2015-03-27 05:03
I think I fixed this so next build it needs to be verified.

**Comment by AzGilrock** [comment] 2015-03-28 14:40
Can anybody test this with 4.0.7?

**Comment by LightsOnHudson** [comment] 2015-04-01 22:10
I have been using a Matrix for my testing, and when I press the STOP button (just to the right of the Pause button) The matrix stops displaying anything.

Although looking at the 'bridge' output of the FPP status window there is still universe data being received. 

So, is Xlights just sending out all 0's and 'blanking' the data when STOP is pressed? When I turn off ' output to light's then i see NO DMX data being received in the Bridge Mode status screen of FPP.

**Comment by smeighan** [comment] 2015-04-01 23:13
i believe xlights has a timer to keep sending data even when there is no data. some controllers went off line if they did not see packets periodically. maybe the developers can give the exact specs.

**Comment by AzGilrock** [comment] 2015-06-08 15:42
I'm not sure why this is listed as a bug.  I tested this at home and my lights were cutting off when I stopped sequence playback.  Sean instead of developers digging into code to figure out how we operate why not just tell us how it's expected to operate?   If it's sending out 0's when you hit stop is that really a problem?

**Comment by smeighan** [comment] 2015-06-09 14:32
The continuous sending of packets of zeroes is by design. There are some controllers that give errors if they dont see data coming in.

Here is comment from Matt Brown, the author of our output routines.
"The key in the code above is the comment... the J1Sys DR4 would not maintain its outputs without a periodic refresh. I imagine there are other E1.31 devices with similar logic. If the entire universe is zeros a refresh would not be needed, but I don't think that test was put into the code."

And the code snippet from xlights_out.cpp

void TimerEnd()
    {
        // skipping would cause ECG-DR4 (firmware version 1.30) to timeout
        if (changed || SkipCount > 10)
        {
            data[111]=SequenceNum;
            datagram->SendTo(remoteAddr, data, E131_PACKET_LEN - (512 - num_channels));
            SequenceNum= SequenceNum==255 ? 0 : SequenceNum+1;
            SkipCount=0;
            changed = false;
        }
        else
        {
            SkipCount++;
        }
    };

I am closing this as it is not a bug but planned behavior

**Closed by smeighan** 2015-06-09 14:32 UTC
Labels: Bug - Minor
