### ISSUE TITLE
Custom Model w/Picture very slow response

### ISSUE THREAD

**Issue by ljbrusta** [smeighan/xLights#2551] opened 2021-03-07 01:33 UTC
When creating a custom model using a 50x50 grid and any size file. I've tried a really small 2k jpg, a 137k jpeg. I'm am really trying to model this spider at 400k (file attached). I'm using 2021.07 and the performance on the grid just dies, scrolling is really slow the first rendering sends the app into unresponsive for a few seconds and it starts flashing and has a spinning cursor. This is on a Intel I7 fairly new laptop. I started rolling back versions of xlights. It is working on 2020.57 correctly but the next version i had was 2021.04 and it stops working. 
![Spider Topper](https://user-images.githubusercontent.com/47700342/110226101-68ef0600-7ea9-11eb-8c7e-2b949bca5838.jpg)

**Comment by flloyd-aa7bq** [comment] 2021-03-12 15:10
I'm having the same issue.  When moving the scrollbars in any direction when a background image is present, the system stalls and it takes 30 to 60 seconds for the interface to start working again.  My system is super fast, lots of RAM, with SSD.  No performance issues at all with the hardware.  Nearly impossible to complete a model.  I'm using a 100x100 grid with a background image.  This is seriously broken.

**Comment by AzGilrock** [comment] 2021-03-12 16:15
It was always slow with bigger grids but I used to work with 200x200 and it was usable.  I would suggest using the online tool from David Peace it works better than xLights for this.  Maybe someone can figure out how to make this work better than I did.  Sounds like something changed that made it worse.

**Comment by flloyd-aa7bq** [comment] 2021-03-12 16:37
I just found a workaround.  As it turns out, the background image complexity is the apparent culprit.
I had a fairly dirty image with lots of shadows, etc. in it from the hasty cell phone photo that I took.  Although I had trimmed it down in Photoshop, it still had a lot of gradients, etc., in the image.

Next, I took it back to photoshop and I reduced the image to a 1-pixel deep, black and white image and then saved it as a BMP file.  The image size was 800x800, and was about 500kb on disk.

The new 'skinny' image worked great.  The performance improvement was immediate and I was able to complete my task as it was designed.

TIP: make sure your background image is as simple as possible, black and white only with no greyscale.  Save the resultant image without compression and use it as your model background.

**Comment by Old-Salt** [comment] 2021-03-29 13:42
First reported as #2478 
https://github.com/smeighan/xLights/issues/2478
issue exists for simple black and white (two color) images as well

**Comment by submodelguru** [comment] 2021-04-01 04:08
I have been having the same issue since 2021.1, i have to use 2020.57 to do custom modeling work.  But anytime I upload a picture of any size, color or anything it locks up xlights...

**Comment by dkulp** [comment] 2021-04-03 19:19
Fixed in 4d9ad03701185a8eaffe7d2e48ebb5a4b0eb7b3c

**Closed by dkulp** 2021-04-03 19:19 UTC
