### ISSUE TITLE
An unhandled exception occurred during Import Data Layer 2017.13

### ISSUE THREAD

**Issue by FlyingPlanes99** [smeighan/xLights#860] opened 2017-05-13 13:44 UTC
When trying to create a new sequence and import a LOR data layer, I keep getting a "An unhandled exception occurred..." error and it keeps crashing the app.

To simplify the test, I've tried all 3 different options during the Import process but it hasn't helped.  I tried uninstalling the app and reinstalling it but it didn't help.

**Comment by AzGilrock** [comment] 2017-05-13 13:58
Are you getting the screen that shows the files about to be packages in a crash dump?  Are you hitting OK so it uploads to us?  If you were running 64bit there is an issue with it not reporting the stack trace in the crash log correctly so it will be fixed next release so for now the 64bit crash logs are not helping us much.

**Comment by FlyingPlanes99** [comment] 2017-05-13 14:00
Unfortunately it only gives me the options to ignore abort or close. It doesn't give me the crash window through xlights.

On May 13, 2017, at 9:59 AM, Gil Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you getting the screen that shows the files about to be packages in a crash dump? Are you hitting OK so it uploads to us? If you were running 64bit there is an issue with it not reporting the stack trace in the crash log correctly so it will be fixed next release so for now the 64bit crash logs are not helping us much.

**Comment by FlyingPlanes99** [comment] 2017-05-14 01:03
Don't know if this helps, but I uninstalled the 64bit version, installed the 32bit .13, reran the import data layer but instead of it crashing, the app hung when it hit the warning in the picture here and stayed non-responsive:
![capture](https://cloud.githubusercontent.com/assets/27301656/26030364/858b197c-381f-11e7-8d77-adedd20b04fd.JPG)

**Comment by AzGilrock** [comment] 2017-05-14 01:16
If you can post the files somewhere might be the only way to find it.  Here's a folder to upload to me:
http://www.mediafire.com/filedrop/filedrop_hosted.php?drop=b8b49be6df9e4b8c21e8deae92295be020438be4e5399239e28c0568bd204d12

**Comment by FlyingPlanes99** [comment] 2017-05-17 22:16
FYI, I just tried to do a data layer import as a new sequence in .14 and got the same crash, but this time, it generated a crash dump.

I just uploaded the crash files to the mediafire share above, let me know if you find anything.

**Comment by AzGilrock** [comment] 2017-05-17 22:26
There isn't anything in the backtrace that points me to the problem.  You will need to do what I originally asked which is provide the files.  I have your show directory files now so I need the LOR file you are trying to import.

**Comment by FlyingPlanes99** [comment] 2017-05-17 22:32
Just uploaded the LMS file, and just as an FYI, I unstalled .13 x32 and installed .14 x64.

**Comment by FlyingPlanes99** [comment] 2017-05-17 22:57
And when you look at the file, you'll notice that the only thing in the xlights config is the megatree, I don't have any other models in the layout. 

I just uploaded a more full, experiencing the same crash, setup that has the rest of the models setup.

**Comment by AzGilrock** [comment] 2017-05-18 03:33
The problem is the LMS file contains data for what looks like an entire house setup and there are universes up to like 122 with a ton of gaps on the middle.  Without digging much I just created 130 universes in setup and then it imports just fine.  We should prevent the crash but it wouldn't really fix your problem it would just prevent the program from exiting.

**Comment by FlyingPlanes99** [comment] 2017-05-18 10:19
Thanks for looking into it.  That's why I had asked previously if I should fill in the gaps in LOR to make the universes go from 1-122 instead 1-12,17-28....  BTW the gaps are there because I removed LOR DMX devices from my shows and switched to all RGB's.

One other question, after the import is complete, and you should see this as well, if you look at the 7th string in the sequence, it's always missing lights, but in LOR, it displays properly.  Is this just an issue with the house preview or is something getting lost during the import?
![treemissing](https://cloud.githubusercontent.com/assets/27301656/26197851/cb5bf0b4-3b91-11e7-9ca7-bf85d8f10c8a.JPG)

**Comment by FlyingPlanes99** [comment] 2017-05-18 10:44
Sorry, and 1 more thing I've noticed on the import.  During the import, it's reporting a large amount of channels are supposedly mapped to the same channel, but when I look at the config in LOR (see pic below), a channel it's complaining about are on separate universes.
![channels](https://cloud.githubusercontent.com/assets/27301656/26198807/822db55e-3b95-11e7-96a8-ef44fb7af137.JPG)

**Comment by AzGilrock** [comment] 2017-05-18 13:49
Are you getting the conflicts after you've provided enough channels in setup?  How many universes did you create?

**Comment by AzGilrock** [comment] 2017-05-18 13:49
By the way I won't be able to look further into this for like a week or more.  Getting ready for Vegas and then I immediately have to setup for a high school light show when I get back.

**Comment by FlyingPlanes99** [comment] 2017-05-18 14:04
No problem, i'll be watching the webcasts.

I added a total of 130 universes in Setup which should have more than covered everything.  The import just doesn't seem to like the way LOR setup the models/visualizations and is choking on them.

**Comment by AzGilrock** [comment] 2017-05-18 14:49
Plenty of us import just fine.  You gotta have a perfect match of channels when you use a data layer.  LOR only sets up the models the way you told it to.

**Comment by keithsw1111** [comment] 2017-05-19 13:49
I think i have this fixed for 2017.15

**Comment by FlyingPlanes99** [comment] 2017-05-23 00:41
What do you think the issue is?

**Comment by keithsw1111** [comment] 2017-06-11 03:49
Have you retested this in .15? Can we close it?

**Comment by FlyingPlanes99** [comment] 2017-06-11 11:54
Yes I did and the fix worked. Thanks.

On Jun 10, 2017, at 11:49 PM, Keith Westley <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you retested this in .15? Can we close it?

**Closed** 2017-06-11 21:54 UTC
Labels: Bug - Trivial
