### ISSUE TITLE
2021.6 - Cant render

### ISSUE THREAD

**Issue by jefft0825** [smeighan/xLights#2543] opened 2021-03-01 19:07 UTC
Something is up with 2021.6 - I cannot render anything on this PC or my wifes - another member from the xlights group is reporting this as well

Didnt attach sequence - none of them will render and have to force task to get xlights to do anything.   Cannot hit escape either to cancel the render

**Comment by bhheath** [comment] 2021-03-01 19:38
Yes, I am seeing the same, restarted multiple times stick at about half way, I reverted .05 and it  Renders just fine.

**Comment by dkulp** [comment] 2021-03-01 22:37
Cannot reproduce.   I was able to batch render my entire Christmas show.   Is there a packaged sequence that would show this?

**Comment by jefft0825** [comment] 2021-03-01 22:43
Just upgraded back to .6 and its working now - i sat for a an hour trying to get this to work and a few others said they had the issue as well - good to close out

**Comment by jefft0825** [comment] 2021-03-01 22:45
It got hung up again - create a new sequence and import then render - happens every time.   Old sequences that have been saved previously render correct

**Comment by jefft0825** [comment] 2021-03-01 22:53
emailed you a copy of the packaged sequence - it was purchased and didnt want to leave it here

**Comment by computergeek1507** [comment] 2021-03-01 22:55
Wonder if it's a OSX vs MSW issue.

**Comment by jefft0825** [comment] 2021-03-01 22:56
I was able to render your Star Wars imperial March.  I cannot render the new ppd sequence.   The Star Wars war previously mapped

**Comment by dkulp** [comment] 2021-03-01 23:57
Fixed in 08108467a160857dbfc75cdf904cde6c4416115a

**Closed by dkulp** 2021-03-01 23:57 UTC
