### ISSUE TITLE
XL4.0.5 Crash

### ISSUE THREAD

**Issue by bluzervic** [smeighan/xLights#108] opened 2015-03-26 17:34 UTC
I had an existing Sequence open and then went to open another sequence and XL4.0.5 crashed

It generated a bug report which I will try to upload here

-Blu

**Comment by bluzervic** [comment] 2015-03-26 18:28
How do I send you a crash dump file

-Blu

**Comment by AzGilrock** [comment] 2015-03-26 18:35
If you just showed us the top 10 lines in the Backtrace.txt file that's usually all we need and sometimes it won't have enough info to point us to the problem.  In that case it needs to be a reproducible problem and we may need to get your sequence and configuration XML's.  But part of this problem is possibly because we haven't written the code to clear out the old sequence yet when you open a new one.  I tried to take a stab at it one day and causes more problems so I had to table it till later.

**Comment by stevegiron** [comment] 2015-05-18 20:29
Hello, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are version 4.0.31. Is this issue still occurring?

**Comment by stevegiron** [comment] 2015-07-09 20:46
With 4.1.10 are you still having this issue?

**Comment by bluzervic** [comment] 2015-07-10 00:54
I will take a look and let you know

Vic

From:  stevegiron <notifications@github.com>
Reply-To:  smeighan/xLights
<reply+006f0fa99990b5cbc1be2d3d8856762936a49d6908256d8892cf0000000111b69f8d9
2a169ce03d98eed@reply.github.com>
Date:  Thursday, July 9, 2015 at 1:46 PM
To:  smeighan/xLights <xLights@noreply.github.com>
Cc:  Victor Churchill <bluzervic@gmail.com>
Subject:  Re: [xLights] XL4.0.5 Crash (#108)


With 4.1.10 are you still having this issue?


Reply to this email directly or view it on GitHub
<https://github.com/smeighan/xLights/issues/108#issuecomment-120139779> .

**Comment by stevegiron** [comment] 2015-08-12 19:07
4.02.00 is current. If no further updates received I'll close this out on 8/15.

**Comment by stevegiron** [comment] 2015-08-20 21:43
No response. Closing issue.

**Closed by stevegiron** 2015-08-20 21:43 UTC
Labels: Need More Info
