### ISSUE TITLE
Once Effect assist is undocked then closed , cannot go to other tabs without it appearing again until docked.

### ISSUE THREAD

**Issue by bcarriveau** [smeighan/xLights#3710] opened 2023-02-01 23:04 UTC
To recreated, Undock effect assist, exit/close effect assist window, try going to controllers tap or layout.

One would expect this window to not reappear once closed and not forced to redock window before exiting it.

https://user-images.githubusercontent.com/60801063/216185338-facecde3-3a3a-4a75-bbd0-560a210b451d.mp4

**Comment by AzGilrock** [comment] 2023-02-01 23:34
You probably have effect assist set to toggle mode

**Comment by bcarriveau** [comment] 2023-02-01 23:42
Mines always on, but changing it to auto or off, if i manually open it, and hit the x to close it, jumping to another tab reopens it again.

**Comment by AzGilrock** [comment] 2023-02-02 00:07
Yeah the problem is using the close button puts the window in a state that mismatches the setting.  I'm sure we've looked at this before and didn't have a good option.  There's probably a function running when you do an action that says hey the setting says he wants that window On.

**Comment by bcarriveau** [comment] 2023-02-02 00:10
ok, i did just confirm this also happen on the Mac as well.  Its not biggie, just off behavior of a window that was closed. If this has been visited before feel free to close :)

**Comment by AzGilrock** [comment] 2023-02-02 00:11
It could probably be fixed but would need another state variable or something.  I won't close cause it would be nice to correct.  It might have just been a pain when I looked at it before.

**Comment by bcarriveau** [comment] 2023-02-02 00:21
✅   Has some hope

**Comment by merryoncherry** [comment] 2023-02-04 17:58
Another symptom of the same issue is if you maximize, say, the house preview on the sequencer tab, then switch to the layout tab, then switch back to sequencer tab, the house preview will be joined by the effect assist panel on the tab.  Sounds like @bcarriveau has it in progress but if not, I see the issue also and can help.

**Comment by bcarriveau** [comment] 2023-02-11 01:33
@merryoncherry , I wish I was intellectually smart enough to understand the deep tissue of codeing lol. I think gil was going to revisit at some time but if you see where it could be fixed I bet they all appreciate the help as I do also!

**Comment by merryoncherry** [comment] 2023-02-11 02:20
Looking at it and finding the situation matches what Gil was saying.

There's a function called ShowHideAllSequencerWindows that gets triggered when the sequencer tab comes into view again.  It will put the "EffectAssist" pane as visible if mEffectAssistMode is set to EFFECT_ASSIST_ALWAYS_ON.  There are menu options that will change this setting as they show and hide the "EffectAssist" pane, but some ways of hiding the pane don't update this state, for example undocking, closing it, or maximizing something else.  So it will reappear after switching tabs.  To fix it, have to understand what we really want it to do, tap into events that fire when the panel is adjusted, and then make the state machine match.

If I spent 5 minutes messing with it I'd definitely break it worse 😀

**Comment by keithsw1111** [comment] 2023-04-26 07:29
I think if you have always on or toggle then when you switch to the sequencer it should respect that choice. I did in the last release include a fix to stop the show/hide toolbar option changing the setting which i think was a bigger problem.

**Closed by keithsw1111** 2023-04-26 07:29 UTC
