### ISSUE TITLE
Xschedule on Mac Crash

### ISSUE THREAD

**Issue by GMANFRE57** [smeighan/xLights#1251] opened 2018-09-22 11:36 UTC
I have xSchedule v2018.33 64bit and all the time crash please i need help.
[xSchedule_l4cpp copy.txt](https://github.com/smeighan/xLights/files/2407729/xSchedule_l4cpp.copy.txt)

**Comment by keithsw1111** [comment] 2018-09-25 05:54
Looks to me like a crash opening the audio files. I will include some improvements in next release which may help but it is not clear from this log exactly what the problem is ... i just see ...

2018-09-21 21:17:33,370 140735237042944 log_base [INFO] FSEQ file /Users/ManfreNotary/Dropbox/ChristmasxFun/Countdown.fseq opened.
2018-09-21 21:17:33,374 140735237042944 log_base [ERROR] FSEQ: Loading audio file '/Users/ManfreNotary/Dropbox/ChristmasxFun/Music/Christmas Medley 2017.mp3'.
2018-09-21 21:18:15,175 140735237042944 log_base [INFO] ******* OnInit: xSchedule started.

The [ERROR] is not actually an error but its the last thing logged and i would expect a bunch of details logged about the audion file. One option is to PM me the audio file. Maybe there is an issue with it.

I wouldnt swear to it though as looking through all the crashes there are a bunch of things that look weird.

**Comment by keithsw1111** [comment] 2018-10-01 20:34
Can you try again with .34 and post your xSchedule log.

**Comment by GMANFRE57** [comment] 2018-10-01 20:38
I will try tonight soon back home after work and let you know.Tk

**Comment by GMANFRE57** [comment] 2018-10-02 00:36
I installed version 34 on mac and as soon as I tried to open xschedule crash I did not even get the log file, is there any other way to open the log file?

**Comment by keithsw1111** [comment] 2018-10-03 00:42
It should be in the Library/Logs directory under where the executable is ... at least that is what the code seems to say.

**Comment by AzGilrock** [comment] 2019-10-04 14:02
Closing...any crash over a year old is out of date for investigating.  Open new issue for current crashes per the new issue instructions.

**Closed by AzGilrock** 2019-10-04 14:02 UTC
