### ISSUE TITLE
Crash when attempting to apply Chase effect or manually apply On effect for simulated chase.

### ISSUE THREAD

**Issue by lyori1** [smeighan/xLights#886] opened 2017-07-26 15:47 UTC
xlights 2017.19 64 bit; OSx 10.10.5: MacPro Mid 2015

I am new to lights so I may be causing the crash as this is my first sequence, but not certain how.

I have just created layered AC star by using the star model and selecting single color with a single strand and channel.  I repeated this for each layer of the star and overlayed them on the preview screen to appear as a single AC star prop with 3 unique  sections.  I then created a group including the inner, mid and outer stars.  Applying the Chase effect does not work to a single grouping as expected unless I select group all arches in the effect window.  However doing this has caused the system to crash after several tests back and forth.  The last crash this am occurred when I was simply applying the on command across the 4 groups to create the desired chase effect similar to LOR.  I can't duplicate this but it is happening quite frequently.  I have restarted lights several times and the laptop a couple.  Appears to correct for a while.  Hope this information helped.
[xLights_dbgrpt-507-20170726T112349.zip]
(https://github.com/smeighan/xLights/files/1177195/xLights_dbgrpt-507-20170726T112349.zip)

**Comment by keithsw1111** [comment] 2017-07-28 09:54
I am afraid I am struggling to reproduce a problem with this sequence.

**Comment by lyori1** [comment] 2017-07-28 14:31
No worries.  It may have to do with the model I was trying to build.   It occurred 5 times throughout the 2 hours I was testing. If it happens again, I'll let you know directly. 

Maybe you can offer a suggestion.  I'm trying to build a 3 strand, 3 tier, 5 point AC star.  Tried both separate models overplayed and also a single model with 3 strands identified by separate numbers in model.   

I would like to be able to use chase or morph across 4 such stars as follows;

1) All 3 tiers on and then chase across 4 stars
2) Chase across any given layer from each of 4 stars (E.g. All inner tiers.)
3) Chase with a individual star outer to inner or reverse

My next step was to download the new AC effects beta and program as I would in LOR, but was hoping for a better way using effects.  

Any suggestions would be greatly appreciated. 

Larry

**Comment by AzGilrock** [comment] 2017-07-29 02:23
Sounds like you just need to learn how to create submodels and then groups of them.

**Comment by lyori1** [comment] 2017-07-29 02:35
Actually setup sub models first, but I'll give it another shot thanks. 

Larry

**Comment by keithsw1111** [comment] 2017-07-30 20:44
Re your question about how to sequence your star ... that would be better posted on the Official xLights Support Group on facebook. Lots of people there who can help.

**Comment by AzGilrock** [comment] 2017-08-07 15:58
I really think this crash was due to some buffer bugs in version .19.  I'd upgrade to the latest v.22 and try again.  When you get a crash window if you hit OK it automatically is uploaded to a place we can access and evaluate the problem so there is really no need to create an issue ticket unless you are able to provide instructions that allow us to reproduce the crash.  I'll close this and you can create a new issue if you have other problems.

**Closed by AzGilrock** 2017-08-07 15:58 UTC

**Comment by lyori1** [comment] 2017-08-07 18:18
Ok thx
