### ISSUE TITLE
DMX-Pro and Visualizer

### ISSUE THREAD

**Issue by AleXthePunK** [smeighan/xLights#2251] opened 2020-09-29 04:29 UTC
When you use DMX-Pro as your protocol, the visualizer doesn't work. 

If you drag a model over to a serial port, it wont stay.

when you upload to a controller, it will throw the addressing off by however many channels is on DMX-Pro

Thank you as always!

**Comment by keithsw1111** [comment] 2020-10-03 07:16
There really is not enough information here to work this problem. I need to know the full controller configuration.

**Comment by AleXthePunK** [comment] 2020-10-03 14:46
It is a Kulp K32. If you add a model using the DMX-Pro protocol, then go back to controller tab, you can't add that model to the visualizer under a serial port.

**Comment by keithsw1111** [comment] 2020-10-03 14:48
If you have nothing more then i am closing this bug report because this does not even come close to enough information to fix it.

**Comment by AleXthePunK** [comment] 2020-10-03 15:03
I have put more than enough information. You can't drag a model on the visualizer when you use a certain protocal. It's quite clear.

I'm not sure the personal vandetta you have had against me for months, but its obvious to everyone in the community that you are constantly unneccessarily a dick to me.

I will stop reporting bugs.

**Comment by computergeek1507** [comment] 2020-10-03 15:26
I was able to reproduce it, but I cannot figure out the issue in the code.

![dmx-pro](https://user-images.githubusercontent.com/2293065/94995270-3ee88f00-056b-11eb-82c6-4f83f0e9ce1d.gif)

**Comment by keithsw1111** [comment] 2020-10-03 21:52
I have tried to reproduce it and every time I drag it over it stays ... I really really really really need files. There is clearly something different but unless I can see what it is this is not going to get fixed.

As for vendetta ... why? Why would I invest energy in that? I spend hours trying to reproduce bugs and all I ask is that you add the details that make it simple to reproduce things. There are many many different ways in which things can be done and the way you do it is likely different to the way I do it. Even doing the same thing in a different order can surface bugs. THAT is why we ask for details (in this case layout and networks files) ... and THAT is why it gets frustrating when people refuse to provide them.

**Comment by computergeek1507** [comment] 2020-10-03 22:18
[xLightsProblem_DMX_Pro.zip](https://github.com/smeighan/xLights/files/5322366/xLightsProblem_DMX_Pro.zip)

**Closed** 2020-10-04 00:32 UTC
