### ISSUE TITLE
New effects to Sequence allows for drag and no positioning

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#152] opened 2015-04-02 19:12 UTC
Using OSX 4.0.10
See the screen shot, With no timing track, etc, you can still drag an effect into the sequence window and when the effect reaches the Sequence screen (black area) a + sign appears giving you the impression that you can drop an effect there but you cannot.
![screen shot 2015-04-02 at 1 05 56 pm](https://cloud.githubusercontent.com/assets/10136122/6971461/e3414132-d939-11e4-82af-9a943325caf4.png)

**Comment by LightsOnHudson** [comment] 2015-04-05 16:51
Using OSX 4.0.14 this morning. Now with the default timings track (thank you) - you are still able to drag to the Sequence window with no models in the sequencer window and the PLUS sign appears again but you cannot drop anything without a model.

**Comment by AzGilrock** [comment] 2015-04-05 20:20
For future reference if the issue is not listed in the release notes then odds are it's not fixed.  I know for sure this one isn't fixed because I couldn't figure out the right spot in the code to change the icon.

**Comment by stevegiron** [comment] 2015-06-24 15:31
With the current release this is now fixed. Closing issue.

**Closed by stevegiron** 2015-06-24 15:31 UTC
Labels: Enhancement
