### ISSUE TITLE
No timing marks showing in the sequencing grid when a new sequence is created

### ISSUE THREAD

**Issue by RichardRennII** [smeighan/xLights#73] opened 2015-03-14 14:06 UTC
Release dated March 13 .
When creating a new sequence I chose the Audio file then select 50 ms timings the timing label is there but the actual timings are not in the sequencing grid. I save the new sequence then reopen it the label is there but the actual timings are not. I then can add 25 ms timings with no issues but have to delete the 50 ms timing label and re add it for them to be seen. When I try to add 100 ms timings the label and timings will show up in the sequencing grid but then I get a Xlights.exe has stopped working message and the program closes no error report with this issue.

**Comment by AzGilrock** [comment] 2015-03-14 14:09
If you're saying there are no timings including no label that sounds like an Aero issue.  Is anything else showing in the grid?  Maybe show us a screenshot.

**Comment by RichardRennII** [comment] 2015-03-14 14:26
The label is there Gil just the actual timings are not after saving I can
add the timings back in and they show

**Comment by RichardRennII** [comment] 2015-03-14 14:28
![image](https://cloud.githubusercontent.com/assets/11212370/6652004/d94a6f8c-ca34-11e4-94aa-7758fdf7069d.png)

**Comment by dkulp** [comment] 2015-03-14 14:31
Gil,

For new sequences, the sequence_loaded flag is false and there is a bunch of things that don't work.  I fixed the timing mark issue last night (I think ), but I think there are other issues related. 

Daniel Kulp

**Comment by RichardRennII** [comment] 2015-03-14 14:34
This is after the save and re open then adding 25 ms timings 
![image](https://cloud.githubusercontent.com/assets/11212370/6652029/a1560996-ca35-11e4-8251-8c1989da9e1c.png)

**Comment by AzGilrock** [comment] 2015-03-14 14:35
Yeah did you read my email.  That flag was there for a reason.  During conversion from 3 to 4 users have the settings dialog open and add timings but there is no sequence yet so I load it into the xml locals objects and then they load into the sequence object when it gets loaded.  They aren't supposed to show up on the screen until the sequence is loaded.  But if you want to fix and text all the timing mark scenarios feel free just make sure you include all the conversion scenarios as well.

**Comment by AzGilrock** [comment] 2015-03-14 14:38
Not saying there wasn't something wrong but the solution was probably to set the flag for a new sequence not remove everywhere I used it.

**Comment by stevegiron** [comment] 2015-03-14 20:23
When you start a new sequence and only have one set of timing marks, that set is not selected. You have to select the radio button next to the timing mark ID and they will show.   Perhaps the default should be that the top most timing mark be selected by default.

**Comment by RichardRennII** [comment] 2015-03-14 20:40
sorry but here it is 
![image](https://cloud.githubusercontent.com/assets/11212370/6653423/d79cdd76-ca68-11e4-938e-ae1c26631d5f.png)

**Comment by RichardRennII** [comment] 2015-03-14 20:42
after saving and adding timings 
![image](https://cloud.githubusercontent.com/assets/11212370/6653429/202f8002-ca69-11e4-8933-8d09c7f34706.png)

**Comment by AzGilrock** [comment] 2015-03-14 22:17
Thanks that's plenty of photos. ;)  Originally I just wanted to make sure you clicked on the circle to activate them.  So there's 2 or 3 ways to add timings to a new sequence.  You can add them on the original settings dialog.  You can close that dialog and open it back up again.  I think I might have missed doing both scenarios because the first way like Dan says the sequence was established yet so I was trying to store them in the xml file object and then they should have gotten loaded when the dialog closed and established the sequence but since it was a new sequence it probably doesn't run through that logic.  Anyways I'm sure we can get this fixed this weekend.

**Comment by AzGilrock** [comment] 2015-03-14 22:42
Ok yeah I just confirmed this.  Pretty much what I said above is why I thought it was working and others said it wasn't.  We were doing it different ways.  That's why details are important.  When you said you were adding timings to a new sequence I thought you meant in the new sequence wizard flow.  It works if you add your timings there.  It's after you close that dialog and re-open that settings dialog that they weren't being added.  And that was because I should have set the sequence_loaded flag Dan was talking about.  So I'll have this fixed in a minute.

**Closed** 2015-03-14 22:54 UTC

**Comment by RichardRennII** [comment] 2015-03-14 23:00
if you would like I can screen shot each step showing what is going on
 they will not appear with using the new sequence wizard after I save I
have to add them manually then they will show.

**Comment by AzGilrock** [comment] 2015-03-14 23:02
It doesn't really help at this point because I have newer code.  Just wait till next build and try again.
