### ISSUE TITLE
Edit Display Elements not moving correct model/group/timing track

### ISSUE THREAD

**Issue by TrekErs** [smeighan/xLights#2464] opened 2021-01-16 18:27 UTC
**Describe the bug**
Sorting items in the Edit Display Elements dialog does not work...item three items below selected items moves instead of selected item, item "bounces" or moves the wrong direction.

**To Reproduce**
1. Open Sequence
2. Right Click on elements/models list
3. Choose Edit Display Elements
4. Choose model/group/timing track
5. Click up/down arrow to move element

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2021.1

**Attachments**
https://www.dropbox.com/s/dbz88u9l17u4t1m/Let%20It%20Go.zip?dl=0

**Comment by AzGilrock** [comment] 2021-01-16 19:00
Sorry I can't reproduce the error.  There was no sequence in that zip file so I created a new blank sequence with your layout and the arrows all worked normal.  Can you video the issue?

**Comment by PixelPowerUSA** [comment] 2021-01-16 19:23
Here's a video from yesterdays issue with the same problem.

https://user-images.githubusercontent.com/49037022/104820947-5c81f180-5806-11eb-8eaf-1e21897e43ff.mp4

**Comment by TrekErs** [comment] 2021-01-16 19:48
Christmas is the show folder and the xsq is under the musical sequences folder.  I'll see if I can get a video for you too.

Ryan

On Sat, 16 Jan 2021 19:01:21 +0000 (UTC), Gil Jones <notifications@github.com> wrote:
 
 

Sorry I can't reproduce the error. There was no sequence in that zip file so I created a new blank sequence with your layout and the arrows all worked normal. Can you video the issue?

**Comment by AzGilrock** [comment] 2021-01-16 19:52
Ok didn't think to look in subfolders.  So I can reproduce the error with that sequence so no need for a video.

**Comment by AzGilrock** [comment] 2021-01-16 19:56
Ok looks pretty simple.  If I remove one of your timing tracks it works fine so when I made the latest changes I didn't account for the number of timing tracks.

**Comment by TrekErs** [comment] 2021-01-16 20:02
Thanks for your help!

**Comment by AzGilrock** [comment] 2021-01-17 20:58
I checked in a fix I believe correct this.  The issue we apparently are not storing the timing tracks at the top of the element list so they are not stored in the order you see in the display elements window.  That caused me to mess up the sorting when fixing some other sorting issues.  I had tested with multiple timing tracks but apparently I had added them before the models and so mine were in the right order.

And for the developers there are some leftover quirks to us not having the timings sorted to the top.  I believe this is why the list tends to jump around when sorting because it only does that jumping if you have a timing track that is at the end or middle of the list of models.  It also appears to cause a focus issue when you move a timing it thinks it needs to set the list focus at the real timing index instead of the displayed index.  For instance I had 3 timing tracks that had element indices of 0, 2, and 150.  So the one that is at 150 is displayed 3rd in the list so when you tell it to move up one it does move up but then focus is set to 150 instead of 2.

**Closed by AzGilrock** 2021-01-17 20:58 UTC
