### ISSUE TITLE
Submodel, States, and Faces preview windows are missing.

### ISSUE THREAD

**Issue by MDickson00** [smeighan/xLights#3674] opened 2023-01-06 21:10 UTC
The preview windows in the submodel, states, and faces dialog boxes are missing.

xlights version 2023.01

1. Open xlights
2. choose a prop
3. open the submodel window
4. observe the missing preview window
5. also note that using yyour cursor to try and attempt to move the preview window itself will cause artifacts to show up

Please see the attached images. 

![2023-01-06 15_02_43-Window](https://user-images.githubusercontent.com/83371818/211100548-238b8db2-e854-4a0c-b640-051ae8a15a39.png)
![2023-01-06 15_03_18-Window](https://user-images.githubusercontent.com/83371818/211100549-cdf2ea25-764f-4237-a51d-98f1db524489.png)
![2023-01-06 15_04_02-Window](https://user-images.githubusercontent.com/83371818/211100550-777e29dc-afed-419d-b46f-805d54a1f495.png)
![2023-01-06 15_04_37-Window](https://user-images.githubusercontent.com/83371818/211100552-bc701d63-d4bf-4c8e-83e9-acbc8e8bf0a1.png)

**Comment by AzGilrock** [comment] 2023-01-06 21:55
Was it all working last version?   We had someone on Ron’s zoom last night that had a similar issue but everyone else tried to reproduce it and couldn’t.

**Comment by computergeek1507** [comment] 2023-01-06 22:00
It works on Mac but is broken on windows

**Comment by dkulp** [comment] 2023-01-06 23:18
I think this is being tracked in wxWidgets.   It might be https://groups.google.com/g/wx-dev/c/X8TaBccQCDk

**Comment by AzGilrock** [comment] 2023-01-06 23:31
Looks like there’s a call to fix it but we would have to add it to everywhere there is a canvas panel.

**Comment by MDickson00** [comment] 2023-01-08 16:04
Any idea if there is an incoming fix for this? It looks like wxwidgets received a fix.

**Comment by computergeek1507** [comment] 2023-01-08 16:17
Wx did? I didn't see a fix yesterday when I looked.

**Comment by MDickson00** [comment] 2023-01-08 16:19
The link that Dan posted above shows to be closed and completed. 

to wx-...@googlegroups.com, Subscribed
Thanks for checking this!

I'll add MSWDisableComposited() but we'll probably have to somehow document the fact that any windows that are siblings of an OpenGL one (or of a wxListCtrl...) may flicker. Unless we end up reverting the change enabling the use of WS_EX_COMPOSITED entirely by 3.3.0 which I suspect may well still happen...

—

**Comment by dkulp** [comment] 2023-01-08 16:33
I merged/updated master of our fork yesterday.  Haven't tagged yet as I want to verify that it fixes it for us.

**Comment by MDickson00** [comment] 2023-01-08 20:11
Not that it changes anything, but just wanted to update that this also issue also breaks the RGB sliders in tool>test.

**Comment by computergeek1507** [comment] 2023-01-08 23:10
try this build that uses WX master, https://github.com/smeighan/xLights/suites/10247994305/artifacts/502699341

**Comment by derwin12** [comment] 2023-01-09 00:31
That works for me Scott on Windows.

**Comment by MDickson00** [comment] 2023-01-09 17:59
This issue seems to be fixed in the latest nightly build, thanks guys.

**Closed** 2023-02-10 23:55 UTC
