### ISSUE TITLE
Enhancement request - Prompt on exit to click Save

### ISSUE THREAD

**Issue by gerry4** [smeighan/xLights#247] opened 2015-05-31 06:54 UTC
If modifications have been done to the sequencer effects ie new effects have been dropped onto the sequencer , or existing ones changed and the user attempts to exit without having Saved the changes, provide the usual 'Exiting without saving will lose changes .. etc ' warning.

Currently , if the above occurs , the changes since the last save are lost.

**Comment by kppankratz** [comment] 2015-05-31 13:12
Or if you try to open or create a new sequence while another sequence is open that hasn't been saved yet either.

**Comment by AzGilrock** [comment] 2015-05-31 13:58
Duplicate of #151

**Closed by AzGilrock** 2015-05-31 13:58 UTC
