### ISSUE TITLE
House preview not correct with Moving Heads

### ISSUE THREAD

**Issue by danielrenwick** [smeighan/xLights#3314] opened 2022-07-04 02:31 UTC
With .13 some of the moving heads effects are not showing correctly of what they should actually be doing. This would be from the change to frame timestamp for the pan/tilt in .13. 

I rolled back to .12 on the weekend and connected a MH head to perform some real testing's and can confirm that the house preview (frame timestamps) on .12 is correct does what the actual MH does and that .13 preview was wrong and different to what the actual MH was doing.

**Comment by dkulp** [comment] 2022-07-04 20:15
Using your Nutcracker MH sequence, I'm not seeing any obvious difference in the preview between .12 and .13.  Is there a particular area/effect/timestamp I should be looking at?

**Comment by danielrenwick** [comment] 2022-07-04 23:40
Thanks Dan for getting back to me. 

It's definitely not happening on every effect and sometimes it is hard to see. It seems more prone on the tilt effect where it is "snapping" back into place. Almost like the tilt slew limit works in one direction but in the other direction it acts like a 0 value and going straight back and it doesn't happen on every sequence. 

Below are two links to a video of a sequence running on .12 and another on .13. I can send you the sequence privately if you like.  
https://www.dropbox.com/s/jefc6pd017cfxhp/Rasputin%20version%2012.mp4?dl=0
https://www.dropbox.com/s/e37xo3k3l8i0rs7/Rasputin%20version%2013.mp4?dl=0

**Comment by keithsw1111** [comment] 2022-07-05 05:55
Holding down the ctrl key and dragging in the waveform you should be able to freeze frame the playback and prove/disprove the differences. This is easier than trying to catch it while it is runnning. Just freeze at the same frame and compare.

**Comment by danielrenwick** [comment] 2022-07-05 09:18
![Picture1](https://user-images.githubusercontent.com/108642619/177293000-a0c5d44f-b0f5-42a8-8c7f-8659021d45e8.png)
![Picture2](https://user-images.githubusercontent.com/108642619/177293010-53a3c824-fcfe-4c09-b1a1-1ecebbdf8c73.png)
 
Picture 1 is how it is meant to look and picture 2 is how it turns out on 2022.13. The strange thing is, I just got the same issue when I paused the effect and hit play and then pause again while on 2022.12, so that has thrown me off now. 

If I just run the sequence and don't pause the effect on 2022.12, it just does what picture 1 shows which is what I would expect from the MH. If I run it on 2022.13 it does what picture 2 shows.

The 2 video files my comment above are only 27 seconds long and are the same effect, one running on 2022.12 and the other on 2022.13

**Comment by dkulp** [comment] 2022-07-05 12:13
Create a small test sequence that reproduces the issue and attach it here.   Looking at pictures and videos is not useful at all in this case.

**Comment by danielrenwick** [comment] 2022-07-05 13:36
I couldn't recreate the issue I was having the other day. 

I think it is the tilt slew limit in the layout. If the value is not the same as the vendors the effect isn't right. Using the attached small sequence I made, which has a tilt slew limit of 150, it is out, but when you change all the MHs to a tilt slew limit of 100 in the layout and render, it does what it should and used to. 

I'll put it down to user error, the only think I can think of is maybe I messed around with the tilt slew limits recently and when I opened an old sequence I had a different tilt slew limit back then. 

[MH test 202213.zip](https://github.com/smeighan/xLights/files/9046629/MH.test.202213.zip)

**Comment by danielrenwick** [comment] 2022-09-06 23:21
Hi guys,

I just wanted to pick this one up again as it seems it is indeed an issue. I see there is another vendor now with the same issue who has submitted ticket number 3379. They have also included a video regarding it https://www.youtube.com/watch?v=jkGi5EauY9M

**Comment by AzGilrock** [comment] 2022-09-07 12:42
I think I remember trying to look at your layout and I saw the issue but I couldn't figure out a fix.  It definitely happened when Dan changed the DMX heads to calculate the slew position differently so that the heads would look correct at slower playback speeds and when exporting which doesn't run at realtime.  I reviewed those code changes and I didn't see a problem with what he did but obviously something is affected.

**Comment by danielrenwick** [comment] 2022-09-07 13:20
Thanks for getting back to me Gil, I really appreciate all the work you guys do. Perhaps Justin from the other post can also help shed some more light on it (no pun intended :) ).

**Comment by danielrenwick** [comment] 2022-09-08 01:20
Thanks a lot for looking into this Dan. I have attached a sequence for you. It is difficult at times to see the issue as it doesn't always happen. If you go into MH Tilt...node 1, at 7.5 second mark there is a bar effect. Just click on that and just let it keep running through. On version 2022.11 it will just keep working, on 2022.16 you will see it go "wonky" after a few goes, it will go hard left, like it is trying to snap to another position. The issue I found is that sometimes it works and other times it doesn't. It can happen on a DMX effect as well. If you have the we will rock you sequence on 2022.16, there are some tilt effects on 2 and 3 for the first 30 seconds, if you play it through you will see it acting normal and then after a while you will see it snap to the left, it happened to me around 24 secs, but may just depend. Or you can click on the effect there and you can see it quickly snapping back to the left. The problem is, MHs can't move that quick, so it is almost like something is overriding the pan and tilt slew limits set in the layout. 
@lenhard2007  perhaps you can also share the sequence you had where you saw the issue as well? 
[MH sample.zip](https://github.com/smeighan/xLights/files/9522681/MH.sample.zip)

**Comment by lenhard2007** [comment] 2022-09-08 02:18
Slew values are being overwritten by any value. It does not happen in preview but when you actually play the sequence they are completly messed up.
I have a free sequence available in my store
JLPIXELSEQUENCE.COM.  superstition is free. Anything after 2022.12 is not working correctly and have many many people  messaged me with the same issues. You tube link is available to watch on the website on how they are suppose to look but if you download 2022.13 or later they are complettly messed up. Hope that helps

**Comment by lenhard2007** [comment] 2022-09-08 02:22
The solution is easy. 2022.13 added something that messes them up. Whatever it was in 2022 13. But it back the way it was and that solves the issues.

**Comment by dkulp** [comment] 2022-09-08 05:00
2022.13 fixes a problem that vendors and users were having that was easily reproduced.  Namely, they could not use the export house preview video and have it produce a video that was anywhere close to what the preview would do.  This was a huge problem on the M1 Macs were the video export of even a 4K preview occurs in much less than 1/2 the time.   With 1080ish previews, the video exports in seconds and the moving heads would barely move.    For folks that sequence in slower speeds (like 1/2 speed) to get things lined up more exactly, they also didn't work as the heads would move too far.  These were real issues where I had easy to examine test sequences that showed the issue.    Did some behavior change?  Possibly.   The looping single effect is likely a change, but I believe it's not "more broken" than it was before.   Ideally, the preview would look all the way back to the beginning of the sequence to calculate the head positions all along the timeline up until that point so it would know exactly what the starting position is, but all of that information is not available in the preview.   It only has the data value for the first frame of the effect and it assumes that that is the value to use for the starting position.   

There is nothing to "put back" to the way it was as that was severely broken.   Since no one seems to want to create a small test sequence that actually shows the problem when played from the beginning, I'm going to assume nothing is wrong and won't spend anymore time on it.   I'll likely close this as not-reproducible.

**Comment by danielrenwick** [comment] 2022-09-08 05:03
Understood Dan and thank you for taking the time to look into it for me

**Comment by lenhard2007** [comment] 2022-09-08 11:38
I create a small video explaining in great detail what is the problem. It was asked of me to create the video so i did. A customer of mine went into the zoom room just the other day on another matter and brought  up this exact same issue up and everyone in the zoom room knows of the issue and all have to go back to 2022.12. There have been other tickets made on this as well. Thanks.

**Comment by lenhard2007** [comment] 2022-09-08 11:42
Link to the video
https://youtu.be/jkGi5EauY9M

**Comment by dkulp** [comment] 2022-09-08 11:45
I need a small packaged sequence that shows the problem.  Without that, don't expect a fix.    I don't have moving heads in my show and I don't have time to spend trying to figure out how to get stuff setup and configuration exact and all that to try and reproduce it.   If it's bothering you, then spend the time and create a small sequence that shows the issue.

**Comment by lenhard2007** [comment] 2022-09-08 14:09
Here is a Sequence. Interesting to note, the issue will not repeat if I just use "Animation" Under animation they work correctly, very smooth transitions. Once i add it to"music" and add the track they mess up. DMX heads do not match up to the song and I did that on purpose. 

[dmx issue file.zip](https://github.com/smeighan/xLights/files/9527481/dmx.issue.file.zip)

**Comment by dkulp** [comment] 2022-09-08 14:14
I think it's corrupt.   If I download with Chrome, it won't unzip at all.   If I download with safari, there isn't an xsq file in there.  There seems to be an rgbeffects.xml and networks.xml, but no xsq.

**Comment by lenhard2007** [comment] 2022-09-08 14:23
im trying to figure it out now

**Comment by lenhard2007** [comment] 2022-09-08 14:29
Interesting to note. Under "animation" they work perfect. Under "music" and add a music file is where they mess up. Have installed lastest 2022.17 and still an issue. I have included an edited portion of the music file and the DMX heads to not match up the the song as i have done that on purpose since i sell the sequence. I have no problem providing you the whole sequence to an email if need be. but this should show how they are not working. Thanks
[Dmx issue test 2.zip](https://github.com/smeighan/xLights/files/9527707/Dmx.issue.test.2.zip)

**Comment by dkulp** [comment] 2022-09-08 14:53
I'm not seeing any difference.   

https://user-images.githubusercontent.com/91569/189154430-17496ecb-582d-4221-9223-5cd1374c6f0b.mp4

Left is Animation and then Export house preview, right is Music export.   Both immediately after a render all.

**Comment by lenhard2007** [comment] 2022-09-08 14:56
that is correct and how its suppose to look. could it be the computer we use? Im on Windows 11

**Comment by dkulp** [comment] 2022-09-08 16:06
It's possibly a windows thing.  I'm on a Mac and don't have a way to test things on Windows anymore so I'm not even sure how to go about looking into it. 

As a follow up.... this is a comparison of export of the house preview with 2022.12 (on the left)  and .17 (on the right).  You can see the .12 stuff is definitely wrong in the export (although it looks ok when I hit play in real time on the screen).   That said, there were some audio changes in .13 as well for Windows so if it only occurs with Music, it's possible it has nothing to do with the DMX changes.
https://user-images.githubusercontent.com/91569/189170526-e43a55bb-6a08-4977-a335-55c85b476a7a.mp4

**Comment by lenhard2007** [comment] 2022-09-08 16:23
Well we might be getting somewhere. The house preview has been an issues for sometime...well over a year and i personally dont use it to record my show because of the DMX issue. Basically it was too slow which is what we see in the last video.So, with the orginal issue Im starting to think its a windows issue. I have had customers with the same problems as previuosly discused and they are also on windows. Any ideas?

**Comment by AzGilrock** [comment] 2022-09-09 01:49
I can run on Mac and Windows so I’ll see if I can look at it in the next couple days

**Comment by keithsw1111** [comment] 2022-09-09 05:56
I still dont see it. I opened sequence ... added audio file, rendered and played back fine. Exported to video ... also fine. Then did it again after removing the audio. Also fine. Here is a video with dans comparison and then windows with and without audio ... they look pretty much the same to me. What exactly are you doing that we are not doing.

https://user-images.githubusercontent.com/10283944/189280987-0abdd5e3-7e5f-4d4d-94d4-c13fc98dcb49.mov

**Comment by AzGilrock** [comment] 2022-09-09 20:30
The question is has anyone recorded there being a problem when everything is fully rendered and played.  Of course there will be issues when clicking around effects because we won’t have calculated the slew rate backwards of the click spot.

**Comment by lenhard2007** [comment] 2022-09-09 20:43
I plan on doing a side by side comparision as soon as i can

**Comment by lenhard2007** [comment] 2022-09-09 23:36
left is 2022.12 which moves correctly and the right is how they move on anything after 2022.13 but is on 2022.17 . Also watch as the new version on the right just jumps right to the position completely over righting slew

https://user-images.githubusercontent.com/89794336/189458893-38c5cf2d-f2f1-4046-b093-a963bf585163.mp4

**Comment by keithsw1111** [comment] 2022-09-10 03:02
Please stop sending videos ... we need sequences which behave as you claim ... unless I can see it do the wrong thing there is absolutely nothing we can do. You did send a sequence ... it did not have the problem you claimed when Dan or I rendered it ... you can see that in the video we both posted ... so I see no bug to work on unless there is something about your setup that is different.

**Comment by AzGilrock** [comment] 2022-09-10 13:19
lenhard I can't even see what you are saying is wrong in the side-by-side video you posted.  Things are jumping and flashing too much.  It would be better to have something more simple like a single moving head with one or two effects that shows a problem.

**Comment by AzGilrock** [comment] 2022-09-10 13:39
Ok I've witnessed the problem but only on Windows.  It looks fine on the Mac.  Keith did you test in Release or Debug?  I don't have a debug version built but downloading the release version I can see the issue.  I used lenhard's  DMX Issue Test 2 file.  I had to unhide the Moving head bodies to see the issue.  When it hits the first effect the moving heads should slowly move to the 45 position.  In Mac they move slow and in Windows they moved really fast.  They didn't snap in place but it was definitely a much faster slew.

**Comment by lenhard2007** [comment] 2022-09-10 14:01
I have 2 sequencing computers. 1 is brand new and  another computer that runs the show. On all my computers (3)  the moving heads will just "snap" to position disregarding slew. Seems it has been narrowed down to windows 11 as that is what I run on all my computers

**Comment by AzGilrock** [comment] 2022-09-10 14:17
I don’t run Windows 11 so don’t lead people astray

**Comment by AzGilrock** [comment] 2022-09-14 15:35
I looked at this more yesterday and had a video that's shows the original rotation issue but didn't get time to upload it.  Basically if you draw an Arch and then move the blue handle across the X axis you will see the arch never tilts.  If you pull the green square to the right of the blue square and then pull the green handle back and forth across the X axis you will see the arch does a lot of tilting.  That was the issue I never fixed from way back when first creating the 3D.  The problem is I'm creating a rotation matrix that is capable of rotation a line across the x-axis to align it with the 2 endpoints.  When the green square is on the right side relative to the x-axis then apparently the arc-cosine starts to produce rotation values that don't keep the arch upright.  It seems like I should be able to just detect the green square on that side and reverse the calculation by swapping the points and then rotating around Y.

**Comment by AzGilrock** [comment] 2022-09-15 01:47
Deleting my last reply it was meant for a different issue.

**Comment by AzGilrock** [comment] 2022-10-02 02:56
Keith and I worked on this in Zoom and believe we have it fixed for the next release.  The issue was the code was expecting the frame time to always advance and in Windows sometimes we got back to back calls with the same milliseconds so it was skipping the slew rate restriction code in that instance.

**Closed by AzGilrock** 2022-10-02 02:56 UTC
