### ISSUE TITLE
Mac: Butterfly not rendering

### ISSUE THREAD

**Issue by neowolfwitch** [smeighan/xLights#2968] opened 2021-11-25 13:14 UTC
The Butterfly effect is not rendering properly on my M1 Mac. Actually- not rendering at all unless I mess with it. I believe Dan mentioned he was working on testing this particular effect.

I ran into the problem in a welcome/announcement sequence that just does the Butterfly effect on my All group. I was trying to figure out why nothing was lighting up, and went back into the sequence to try to re-render it. It will show up sometimes in Model Preview, but as soon as I render it- it's blank.

Sometimes I can get it to work by toggling Layer Settings between "Default" and "Per Preview", or by changing the Style slider a few times. It seems to be really hit-and-miss. It isn't just a display issue on the Mac- it renders as blank, and nothing shows on my lights running from FPP.

This is on a 1st-gen 13" M1 Macbook Pro.

**Comment by neowolfwitch** [comment] 2021-11-25 13:42
I figured I'd make a video to better show the problem...

https://user-images.githubusercontent.com/68392802/143451956-7fa74e0c-3ba9-4549-a3b1-e0a7610fab05.mp4

**Comment by dkulp** [comment] 2021-11-25 13:52
Can you save and package the sequence and attach?  I want to see the buffer sizes and such during rendering so I'd need the full setup.

You can go to Preferences and on the Other page, turn off the GPU rendering (off should be the default anyway, did you turn it on?) and it would use the normal CPU rendering for butterfly and should fix the issue.   That said, I'd like to understand what's going on with it.

**Comment by neowolfwitch** [comment] 2021-12-06 23:34
Sorry Daniel- didn't see this when you replied. I'll try to get to this tonight...

**Comment by neowolfwitch** [comment] 2021-12-07 02:03
Okay, I just did a quick test sequence, basically the same as what's in the video I sent. Same issue. It's attached
[Butterfly Test.zip](https://github.com/smeighan/xLights/files/7664921/Butterfly.Test.zip)
.

**Comment by dkulp** [comment] 2021-12-07 13:15
I was unable to reproduce this on my M1Max MacBoo Pro or my wife's M1 13' MacBook Pro.   Scott also tested on his M1 Mac Mini and was unable to reproduce.     We both tried with both the normal CPU rendering as well as the new GPU rendering and it worked each time.

**Comment by computergeek1507** [comment] 2021-12-07 13:19
What MacOS version are you using, I using Monterey

**Comment by neowolfwitch** [comment] 2021-12-09 13:03
Monterey on a 1st gen M1 13” MBP.

**Comment by neowolfwitch** [comment] 2021-12-13 17:59
Okay, so it was GPU rendering. I toggled it off and restarted xLights, and now Butterfly renders normally and I'm no-longer having issues with it in my sequences.
I don't remember turning it on, and I know it is "experimental". It apparently doesn't work right on 1st Gen. M1 MacBooks. I'm happy to try out any other possible fixes other than turning it off.

**Comment by dkulp** [comment] 2022-10-27 15:31
This will be fixed in the next release. Workarounds are to either disable the GPU rendering or to disable the RenderCache.

**Closed by dkulp** 2022-10-27 15:31 UTC
