### ISSUE TITLE
xSchedule crashes

### ISSUE THREAD

**Issue by OzAzgithub** [smeighan/xLights#2644] opened 2021-05-16 04:03 UTC
xSchedule crashes as soon as first step finishes
Both versions 2021.14 and 2021.15 crash, not tested 2021.13

2021.12 works fine

on windows 10
Running a basic 3 step playlist with just 3 basic sequences.

**Comment by darylc** [comment] 2021-05-16 04:26
duplicate of #2635

**Comment by keithsw1111** [comment] 2021-05-17 09:48
I believe this was fixed by another change

**Closed by keithsw1111** 2021-05-17 09:48 UTC
