### ISSUE TITLE
DMX moving head

### ISSUE THREAD

**Issue by greerfamilylights** [smeighan/xLights#2153] opened 2020-08-01 01:48 UTC
IS there a way to get a positive and negative rotation for the pan feature? Im not sure if im saying that correctly but when doing certain pans the head can easily move to the left 1st instead of turning 360 degrees to get that point. If you click the movements manually it works. when you play the sequence it does a full turn clockwise to position itself in a left facing direction.

**Comment by AzGilrock** [comment] 2020-08-05 15:22
Looks like a duplicate of the same one you entered before.

**Closed by AzGilrock** 2020-08-05 15:22 UTC
Labels: Enhancement

**Comment by greerfamilylights** [comment] 2020-08-05 15:27
You didnt understand my issue and answer my question
   

    On Wednesday, August 5, 2020, 11:22:24 AM EDT, Gil Jones <notifications@github.com> wrote:  
 
 


Looks like a duplicate of the same one you entered before.

**Comment by AzGilrock** [comment] 2020-08-05 15:33
Aren't we discussing this on the forum?  It was pretty much the exact same description so I assume it was you.  Anyways don't create a second issue all because nobody replied the first time.

**Comment by greerfamilylights** [comment] 2020-08-05 15:38
With so many forums who knows where to post. I tried a different route. Sorry I pissed you off.
    

    On Wednesday, August 5, 2020, 11:34:05 AM EDT, Gil Jones <notifications@github.com> wrote:  
 
 


Aren't we discussing this on the forum? It was pretty much the exact same description so I assume it was you. Anyways don't create a second issue all because nobody replied the first time.

**Comment by AzGilrock** [comment] 2020-08-05 16:00
Why would you think I'm pissed off?  We close duplicate tickets all the time.  I've been trying to help on the forum and there was no reply or sequence provided after my last response.  Feel free to continue.  If someone else wants to jump in and help they are welcome also but I haven't seen any raised hands...lol.

**Comment by greerfamilylights** [comment] 2020-08-05 16:29
I thought you were mad. I gave you a sequence in the forum. And you replied but it didnt really answer my question. I replied reiterating my issue. Sorry buddy. I did donate to you all today lol 
    

    On Wednesday, August 5, 2020, 12:00:53 PM EDT, Gil Jones <notifications@github.com> wrote:  
 
 


Why would you think I'm pissed off? We close duplicate tickets all the time. I've been trying to help on the forum and there was no reply or sequence provided after my last response. Feel free to continue. If someone else wants to jump in and help they are welcome also but I haven't seen any raised hands...lol.

**Comment by AzGilrock** [comment] 2020-08-05 16:39
You did give me a zip file on the forum but it did not contain a sequence file so I was only able to create the layout using the xlights_rgbeffects.xml file.  If you have a sample sequence that shows the error please post that.

**Comment by greerfamilylights** [comment] 2020-09-29 01:14
You have helped me before and Im asking again lol. I am having trouble remapping the channels for moving heads on an imported sequence. I can't get them to remap

    

    On Wednesday, August 5, 2020, 12:40:11 PM EDT, Gil Jones <notifications@github.com> wrote:  
 
 


You did give me a zip file on the forum but it did not contain a sequence file so I was only able to create the layout using the xlights_rgbeffects.xml file. If you have a sample sequence that shows the error please post that.

**Comment by AzGilrock** [comment] 2020-09-29 09:08
Sorry I have no experience trying to do that.  Not sure if you can.  May need to just import then manually copy paste the rows where you need them.

**Comment by greerfamilylights** [comment] 2020-09-30 01:08
Will there ever be a way to import DMX from another software?
    

    On Tuesday, September 29, 2020, 05:08:30 AM EDT, Gil Jones <notifications@github.com> wrote:  
 
 


Sorry I have no experience trying to do that. Not sure if you can. May need to just import then manually copy paste the rows where you need them.

**Comment by keithsw1111** [comment] 2020-10-02 14:25
Not sure what you mean ... DMX models ... or DMX sequencing ... and if the latter which one. The former xLights has thousands of fixtures that can be downloaded.
