### ISSUE TITLE
SMS texting issues seen

### ISSUE THREAD

**Issue by SniperMunyShotz** [smeighan/xLights#1613] opened 2019-07-25 02:50 UTC
Kieth,

Just putting the bugs I have seen since we met at EXPO here just in case we missed some.

1.  The welcome message that scrolls is not working when no texts are in queue in xscheduler shows this:
![xschedule error](https://user-images.githubusercontent.com/22962428/61841779-e5afa680-ae63-11e9-8907-f7b23d70b1c8.PNG)

2.  I was not able to find it in the logs, but if you get a queue in line for multiple texts, seems they all disappear after the first line display reaches its limit (had set for 3) and all messages clear out.

Feature request, maybe more for FPP team?

Ability to push text across a matrix that is in FPP remote mode?

**Comment by keithsw1111** [comment] 2019-07-27 06:12
These may be fixed

________________________________

**Comment by keithsw1111** [comment] 2019-08-06 07:17
I am closing this ... if you think the issues still exist please reopen.

#2 i could not reproduce but the changes made may already help.

**Closed** 2019-08-06 07:18 UTC
