### ISSUE TITLE
XML parsing error: 'syntax error' at line 1

### ISSUE THREAD

**Issue by PKingRoch** [smeighan/xLights#828] opened 2017-02-20 23:35 UTC
I selected two props that are grouped in my layout, copied them and then tried to paste them but I receive the above error on the paste operation.  This happens every time I try this.  xLights BETA ver 2017.3

**Comment by keithsw1111** [comment] 2017-02-21 11:20
We are going to need more information ... maybe paste it into notepad and send that to us.

**Comment by PKingRoch** [comment] 2017-02-21 12:06
RGBeffects and networks attached.  Select "PT Base - 1" and "PT Star - 1" in the layout screen by the mouse.  Select Edit Copy from the main menu.  Click anywhere on the layout screen.  Select Edit Paste from the main menu.
What additional information do you need?  I can send anything you need today, I will be out of town and unavailable to send anything until after 3/6 starting tomorrow.

[xlights_rgbeffects.zip](https://github.com/smeighan/xLights/files/790018/xlights_rgbeffects.zip)

**Comment by keithsw1111** [comment] 2017-02-22 07:49
I have tried and i cant reproduce this problem. I also dont believe the program supports copying more than model at a time. I select 2 models copy and then paste. One model pastes correctly and the other is ignored. I need more information to progress this. Maybe a video. A copy of your log file.

**Comment by PKingRoch** [comment] 2017-02-22 07:50
Where is the log file?

**Comment by PKingRoch** [comment] 2017-02-22 07:57
Sorry, I'll have to get to this after I return.  Sometime the week of March 6th.

**Comment by keithsw1111** [comment] 2017-05-03 04:29
Do we have any more information on this? If not I feel we should close this ticket.

**Comment by PKingRoch** [comment] 2017-05-03 11:03
Sorry about that – close this for now.  We’ve had a death in the family and I haven’t been able to get back to this.

**Closed** 2017-05-03 19:32 UTC
Labels: Bug - Minor
