### ISSUE TITLE
xLights crashes on render

### ISSUE THREAD

**Issue by MrChristmas2000** [smeighan/xLights#788] opened 2016-12-27 16:04 UTC
When I do a render on save this sequences crashes upon rendering. It never gives me a chance to input any information at the time the crash screen flashes by.

After I restart xLights and reload there is a rendered file and it will play in the visualizer screen ok.
[Who Spiked The Eggnog - 12-25-2016 - Import.zip](https://github.com/smeighan/xLights/files/674344/Who.Spiked.The.Eggnog.-.12-25-2016.-.Import.zip)

**Comment by keithsw1111** [comment] 2016-12-28 23:36
While I understand you dont have the crash log could you make it crash then restart xlights and run package logs on the tools menu and send us that file.

**Comment by MrChristmas2000** [comment] 2016-12-29 15:36
Ok here is file as requested.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/677401/xLightsProblem.zip)

**Comment by keithsw1111** [comment] 2017-05-03 04:39
Tom with all the recent fixes is this still happening?

**Comment by keithsw1111** [comment] 2017-08-02 19:33
I am closing this issue as there is no confirmation it is still happening and i cant reproduce it. If it is still happening please let us know and we will reopen it.

**Closed by keithsw1111** 2017-08-02 19:33 UTC
