### ISSUE TITLE
Create a "Color Swatch" Library as a dockable panel...

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#652] opened 2016-08-17 15:02 UTC
With Gradients there is a lot more than 8 swatches that I want at my quick disposal when sequencing. Rather than argue with people about how many swatches should be in the color panel can we have a Color Library dockable panel where we can add as many swatches as we like?

**Comment by stevegiron** [comment] 2016-08-17 15:30
Dupe of #361

**Comment by stevegiron** [comment] 2016-08-17 15:41
The trick that I use right now is a psuedo color model with several layers.  Each layer has the color wash effect and each effect has a different color palette loaded. The effect goes cross the entire timeline.  Now I have several palettes at my disposal across the entire sequence. Just click on the color wash and the palette will load to those colors selected for that effect. Now choose a new effect and place it with the loaded palette.

**Comment by AzGilrock** [comment] 2016-08-17 16:14
I don't think we will create another panel.  Like I said privately I had planned to provide a way to quickly switch and/or save the color palettes.  It needs to stay fixed at 8 colors because all the internal logic in the program operates on the colors existing at those slot locations.  Also all your sequences have an effect database that is geared upon those slot numbers.  Some of the effects are even hard-coded as to which slot number they pull a particular color from.  Like my morph grabs the head colors from the first and possibly second slot and the tail colors from the remaining slots.

**Comment by AzGilrock** [comment] 2016-08-17 16:16
If you haven't learned the trick that Steve talks about I use something similar all the time.  When you select an effect it loads that effects palette into the color panel.  So sometimes I click on an effect for the sole purpose of loading the palette and then I drag a different effect down and it inherits that palette.

**Comment by stevegiron** [comment] 2016-08-17 16:40
You can also use presets to store your color palettes as each effect stored also stores the 8 colors used for that effect. Your options are unlimited. Since you can share a preset, you can share a color palette.

**Comment by keithsw1111** [comment] 2016-08-17 19:32
While it does not help the colour panel issue ... with the gradients you can add as many as you like. Just export them as xcc files and leave them in your show folder or a colorcurve folder under your show folder and they will be available for all sequences you work on in that show folder.
If you want to reuse them across different show folders put the xcc files in the colorcurve folder in the xlights install directory (on windows) ... on the mac there is a different location.

**Comment by keithsw1111** [comment] 2016-09-13 10:58
Implemented ... my interpretation of this.

**Closed by keithsw1111** 2016-09-13 10:58 UTC
Labels: Enhancement
