### ISSUE TITLE
Virtual Matrices on secondary/ third display outputs. 

### ISSUE THREAD

**Issue by MaxJago93** [smeighan/xLights#2193] opened 2020-09-01 11:04 UTC
Virtual Matrices in Xschedule wont play on secondary or 3rd display outputs on graphics card, you can place the position window onto the display however the virtual matrix doesn't display when playing a sequence. it will only display the virtual matrix on the main display with the position window set to the main display?

is it possible to make virtual matrices function on any display output? this way I can assign one virtual matrix to one screen and another to another screen.

**Comment by keithsw1111** [comment] 2020-09-07 07:32
I think this is fixed in .35

**Closed by keithsw1111** 2020-09-07 07:32 UTC
Labels: Enhancement

**Comment by MaxJago93** [comment] 2020-09-07 08:38
Hi Keith,

I will have a play when I get home and report back to you.
Thanks so much for the fast response and rectification 😁

Kind Regards,

Max Jago
Owner-SunSmart Energy

**Comment by MaxJago93** [comment] 2020-09-07 09:21
Hi Keith,

The Xlights.org site seems to be down can’t open main site or the releases page?

Can however bring up manual.xlights page to open up zoom link.

**Comment by MaxJago93** [comment] 2020-09-07 09:21
﻿Hi Keith,

The Xlights.org site seems to be down can’t open main site or the releases page?

Can however bring up manual.xlights page to open up zoom link.

**Comment by MaxJago93** [comment] 2020-09-08 02:12
Hi Keith,

I can confirm with 2020.35 the 2nd screen matrix displays on the screen the position window is put on, its however not in the exact location of the position window but it stays on the screen so I should be able to have a play and trick it to being centralised.


Thanks heaps for the fast fix for this!

**Comment by keithsw1111** [comment] 2020-09-08 10:22
Is it out by much? What are your monitor scaling settings (main and the projector) ... as this is the root cause of the problem.

**Comment by MaxJago93** [comment] 2020-09-08 12:07
Hi Keith,

I have the monitor set to 624x312 same as the virtual matrix in Xlights.

I think I have figured it out when putting the position window in place you set it so the top left corner is where you want the matrix to start display rather then centre it on screen and then it all sits correctly when playing.

Kind Regards,

Max Jago

**Comment by keithsw1111** [comment] 2020-09-08 18:36
its not the window size that was the problem ... it was the scaling. if there was different scaling it was throwing off the positioning.

**Comment by MaxJago93** [comment] 2020-09-08 22:22
Hi Keith,

Okay great well I’ll keep playing with it but it’s definitely looking like you have solved my issue and I won’t need FPP yay!
I have managed to get a old graphics card and set its resolution to match the matrix 624x312 and the Xschedule virtual matrix can be positioned to match the screen with a little bit of playing with position window so far so good with testing on monitor now to go to big led screen!

I very much appreciate the support and free software you provide! I’ll be sure to make another donation shortly.

Kind Regards,

Max Jago

**Comment by MaxJago93** [comment] 2020-09-22 06:58
Hi Keith,

So since updating from 2020.26 I’m unable to set DMX as a protocol my dmx props was working in .26 however once I went to .34, .35, .36 and now .39 they went into a error state and don’t have a protocol set, I can go into the model and set dmx hit save go out of the prop and then back into it and it reverts back to no protocol set.
Any ideas on this?
If I revert back to .26 the models start working again.

Kind Regards,
Max Jago
