### ISSUE TITLE
Individual Start Nodes Does not work on Spiral Trees

### ISSUE THREAD

**Issue by PiXeL-Paradise-USA** [smeighan/xLights#3455] opened 2022-10-03 01:41 UTC
Hello today I went to insert the model on our 414 node spiral tree, which uses two separate strings (but only 1 linear run) from the bottom up to the top. 414 Nodes was too much to run on one port so I divided it between two separate strings to utilize two controller ports. When adding a second string it merely adds another spiral (like a DNA helix) instead of just adding the 2nd string to the end of the first, like any other prop. This prevents users from being able to assign "Individual Start Nodes" at all for spiral trees. Since spiral trees are more commonly a single strand spiral, I believe the default #2 of strings should instead place the 2nd string at the end of the first and allow Individual Starting Nodes to be programmed to specify the exact count of LEDs from the bottom to the top over 2 strings. Optionally, a "helix" option could be made to cater to those running double strings in opposites instead of end-to-end. Thanks guys for all your hard work!
![spiral trees](https://user-images.githubusercontent.com/109118551/193487527-77034fbe-bb8f-4bfc-9baa-d5d2ef4337c3.jpg)

**Comment by derwin12** [comment] 2022-10-05 22:30
Since this is not seen that often we would just create a shadow model to address this...so perhaps this is more of an enhancement request.

**Comment by PiXeL-Paradise-USA** [comment] 2022-10-05 23:03
Thank you for your reply. Although it may seem rare, it also seems obvious to allow a single spiral to be defined by total # of nodes and total number of strings in a single spiral. This is why I chose to put this as an "issue" as opposed to a "feature request". The # of strings function was programmed to act differently than with a standard megatree. With the standard megatree, defining the number of strings, strands, and nodes all assume the strings are connected end to end.  The spiral tree adds a helix, and there's not way to add a string end to end. For anyone building a large spiral tree, greater than 5', it's currently not possible to create one in xlights using multiple strands... unless we power inject throughout. A pain if using LED strips. Would this be an easy fix to program? -Dave

**Comment by AzGilrock** [comment] 2022-10-05 23:39
In the old days you would just tell xLights it’s one string then you would configure the controller to split it across two ports.   This whole problem is caused by trying to get xLights able to auto configure all the controller settings.  You can still do it the old way.

**Comment by PiXeL-Paradise-USA** [comment] 2022-10-06 01:10
> In the old days you would just tell xLights it’s one string then you would configure the controller to split it across two ports. This whole problem is caused by trying to get xLights able to auto configure all the controller settings. You can still do it the old way.

I'm not sure I follow you. How can I say total 414 nodes, String 1 = 300, String 2 = 114, to make a single spiral?

**Comment by AzGilrock** [comment] 2022-10-06 18:19
I'm saying create one model and tell it there are 414 nodes to create the spiral.  Then you just need to map the outputs in the controller to start where the split is.

**Comment by AzGilrock** [comment] 2022-10-06 18:20
Don't use Individual start nodes

**Comment by PiXeL-Paradise-USA** [comment] 2022-10-06 18:42
> I'm saying create one model and tell it there are 414 nodes to create the spiral. Then you just need to map the outputs in the controller to start where the split is.

Thanks Gil. I'm worried that would make me have to uncheck the "full xlights control" option as it would be a manual entry of the channels. Thinking the temporary fix would be derwin's above using shadow models, which can make the two separate strands be on two different ports with their own unique pixel count, and still allow xlights to Upload Output correct with full control. I'm not giving up on this though! I think this particular request for individual start nodes would be a great thing for spiral trees that use high density LED strips.
![2022-10-01 17 09 51](https://user-images.githubusercontent.com/109118551/194393296-b7b274a2-8928-4432-b908-e240fc9be640.jpg)

**Comment by dkulp** [comment] 2022-10-06 18:45
This is working as designed.   As mentioned, the second string (or third or forth) is for multiple spirals.  It was specifically implemented that way for that purpose.

**Comment by PiXeL-Paradise-USA** [comment] 2022-10-06 19:13
> This is working as designed. As mentioned, the second string (or third or forth) is for multiple spirals. It was specifically implemented that way for that purpose.

Thanks Dan! I think the "multiple spirals" or "helix mode" could be made as a specific option for the spiral tree for those wanting 2 strands (less common). This way, it would free up the "string count" function to single spiral trees to easily add strings end to end - allowing users a much easier way to build a single spiral trees that greater than 350 nodes (for power reasons). I know you're super busy with FPP right now and this is small potatoes coming into the busy season and are likely focused on bugs and stability issues, but please put in on the docket- it just feels silly that I'm having to build a custom or shadow model for a spiral tree that's only 5' tall 414 nodes, using two separate strands to make a single spiral.

Appreciate all the work you do sir.
-Dave Mills
![2022-10-01 18 57 38](https://user-images.githubusercontent.com/109118551/194399078-8ecb55ed-22a3-49d7-b823-9d216d8c8ca0.jpg)
![2022-10-01 17 10 08](https://user-images.githubusercontent.com/109118551/194399097-320c191e-231e-4d71-9038-1b54767bcd9c.jpg)

**Comment by derwin12** [comment] 2022-10-06 20:12
This is really a duplicate of https://github.com/smeighan/xLights/issues/2334

**Comment by AzGilrock** [comment] 2022-10-06 21:31
Keith and I have talked about the desire to have individual start nodes work for all models.  Pretty soon I will have a new model type added that could potentially accomplish this.  You could create a single string spiral tree and then I'll have the ability to convert any model to my new model type which I believe already supports individual start nodes.

**Comment by PiXeL-Paradise-USA** [comment] 2022-10-07 16:29
> 

Gil this would be most excellent. Actually, you reminded me of an option that works as a temporary fix - clicking on the spiral tree model in the layout I can "Export to custom model". Then simply import it back and it forgets that it's a spiral tree, and the individual start nodes option appears, so I can choose start 1 and start 301 :D The downfall, is that it compresses the 3D spiral into a flat shape on my 3D layout. Anyway to restore it's look? Or should I make this the shadow for the other one?
![custom model](https://user-images.githubusercontent.com/109118551/194602429-51881140-26b8-4309-88a3-eaa9ac71010a.jpg)

**Comment by keithsw1111** [comment] 2022-10-07 23:15
shadow would be easiest ... you can in theory make a custom model 3D but there is a bit of work to do to make that happen ... essentially add depth to the custom model then use the F7/F8 keys when located on a node cell that you want to push back/pull forward and it will push them back to create depth.

**Closed** 2022-10-08 22:56 UTC
