### ISSUE TITLE
Enhancement request - ability to select the backup location

### ISSUE THREAD

**Issue by JasonPortwood** [smeighan/xLights#509] opened 2016-03-29 13:30 UTC
I believe a good enhancement would be to have the backup location be settable by the user.  By default it could be how it currently is but allow the user to modify the location.  This would make it easier to save backups automatically to a different location to avoid hard drive failures for example.

**Comment by AzGilrock** [comment] 2016-03-30 01:05
Duplicate of #235

**Comment by Vlad-Star** [comment] 2016-06-14 06:35
A duplicate seemed to be closed with "wontfix" resolution. Please, re-consider.

I would like to add my vote to the request - this is the feature xLights is currently missing. Should you lose your primary drive - all of your work along with the backup folder is gone (unless you manually copy it somewhere else, which is a different story). Keeping backups on a secondary (external) drive should allow to survive a failure of the primary drive, having a quick recovery of the most recent work.

Besides, I would like to suggest two more related options:
1) "Autobackup on Save". Every time you press a "Save" button, your work is auto-saved to the backup location (without a need to press F10).
2) Backup retention (limited to either a number of days or copies). Obsolete files and subfolders need to be auto-deleted from the Backup folder (for instance, on exit).

**Comment by keithsw1111** [comment] 2016-06-16 10:48
What I have implemented:

You can now optionally specify that you want a backup to the normal backup location every time you save.
You can now press F11 and it will save to a specified alternate backup location. It will never automatically backup to this location. This is a manual backup only.

**Closed by keithsw1111** 2016-06-16 10:48 UTC
Labels: Enhancement
