### ISSUE TITLE
Need way to change timing track colour

### ISSUE THREAD

**Issue by cjd** [smeighan/xLights#619] opened 2016-07-13 22:41 UTC
The current timing track colours are set to be cyan, red, green, blue, yellow (then repeat)
But red in particular can be hard to see and read for many (especially for colour-blind users)
It would be good to either remove red from the list of possible colours - or enable custom track colours.

**Comment by cjd** [comment] 2016-07-13 22:48
quick workaround is to change "value = &xlRED;" in "RowHeading::GetTimingColor"
to "value= &xlMAGENTA" but not sure if this is a suitable change

**Comment by kppankratz** [comment] 2016-07-14 02:44
Another hard combination to read is the dark blue with black text.

**Comment by AzGilrock** [comment] 2016-07-14 03:10
No I don't want to just hard code it to another color.  I'd rather implement a way for users to customize the colors for this and other things in the app.  Its been on my mind for awhile.

**Comment by AzGilrock** [comment] 2016-08-09 19:47
This is a duplicate of #363.

**Closed by AzGilrock** 2016-08-09 19:47 UTC
Labels: Enhancement
