### ISSUE TITLE
Lyric track enter issue

### ISSUE THREAD

**Issue by CFOLMichelle** [smeighan/xLights#1082] opened 2018-01-23 15:40 UTC
On the Mac version, after entering lyrics in the Label window, the enter button no longer works to close the window.  You have to go and click the OK button for it to close.

**Comment by stevegiron** [comment] 2018-01-23 15:53
The code changed. You can go to settings and change the behaviour of the
double click.

**Comment by CFOLMichelle** [comment] 2018-01-23 16:24
I know that change, it’s not getting the window to open it’s getting the window to close after inputting the lyrics.  I used to just hit enter and it went away, now I have to stop and click ok.  Darrell said it’s only a Mac issue and enter still works on a PC.

**Comment by dkulp** [comment] 2018-01-24 16:47
It's a bug in wxWidgets:

https://trac.wxwidgets.org/ticket/18060#ticket

and affects everywhere we use the wxTextEntryDlg.

**Comment by keithsw1111** [comment] 2018-04-11 09:45
Was this fixed with the wxWidgets upgrade?

**Comment by dkulp** [comment] 2018-04-11 11:46
No...   I keep meaning to create a subclass of the text entry dialog that would work around it.   Haven't had a chance.

**Comment by AzGilrock** [comment] 2018-10-08 22:01
According to the wxWidgets ticket if you follow to what they called it a duplicate of they supposedly fixed this issue 7 weeks ago.  Not sure if that's easy to pull in or not.

**Comment by AzGilrock** [comment] 2019-10-23 19:37
Michelle do you know if this is fixed?

**Comment by CFOLMichelle** [comment] 2019-10-25 03:08
Gil it has been.

**Closed** 2019-10-28 15:02 UTC
