### ISSUE TITLE
20 Crashes on render

### ISSUE THREAD

**Issue by Russ1T** [smeighan/xLights#4183] opened 2023-12-02 04:19 UTC
[xLights_dbgrpt-14808-20231201T231223.zip](https://github.com/smeighan/xLights/files/13533332/xLights_dbgrpt-14808-20231201T231223.zip)
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**

Xlights Crashes on rendering

**To Reproduce**
Steps to reproduce the behavior: imported a sequence in 19 rendered all was good installed 20 and xlights crashes on render. 
included zip file.
(and/or link to a short video showing the problem with audio track describing what you are doing)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by dkulp** [comment] 2023-12-02 06:35
The issue is that you have a matrix assigned to a controller that is set as "Video playing remote only".   There are no channels for it.     It shouldn't crash which we'll try and fix, but if you unassign the matrix from that controller, it would then render.

**Closed** 2023-12-02 07:03 UTC

**Comment by Russ1T** [comment] 2023-12-02 11:50
Thank you for your reply.  I've had it that way for a while but it only
happened when  I updated to xlights 20...
