### ISSUE TITLE
Submodel issue

### ISSUE THREAD

**Issue by Cattbeanie** [smeighan/xLights#3681] opened 2023-01-12 18:59 UTC
In layout: No submodels showing in 2023.1 - submodels show nodes only in windows, no preview. To reproduce - go to any model and slick submodel. This will show nodes but not any preview or pictorial representation of the submodel which was expected:
![image](https://user-images.githubusercontent.com/110200185/212157065-90d23263-0d5f-422c-ba90-7117df433546.png)
![image](https://user-images.githubusercontent.com/110200185/212157171-11755f4d-6f4e-4887-8346-f8fa8e1ac128.png)

**Comment by computergeek1507** [comment] 2023-01-12 19:02
Duplicate of https://github.com/smeighan/xLights/issues/3674

**Closed by computergeek1507** 2023-01-12 19:02 UTC
