### ISSUE TITLE
Version 2018.2 Polyline with individual segment crash

### ISSUE THREAD

**Issue by CrAsH0v3r** [smeighan/xLights#1078] opened 2018-01-20 18:58 UTC
I know this should have been resolved in this version but i'm still experiencing a crash when moving an effect in my sequence if I have a polyline model with individual start.

Lets explain. I have a 3 levels star with polylines starting from center to the 5 points of the stars. As 3 points on each of these lines overlap with points of the stars, I want to map the same channel (it's why I use polylines).  If you have a better way to do it, let me know.

![star](https://user-images.githubusercontent.com/35637227/35186844-08d2e4e2-fde9-11e7-8150-c4f051407051.png)

Anyway, as soon I check the "Individual channel" box of one of these polylines and I move an effect on the star, the app crash, sometime with backup, sometime hard crash. It happens when channels from the star are the same of some points of the polylines. If I remove these channel overlap, It does not crash.

Here is the latest bug report. I'm pretty sure I'm missing something in my investigation but it is a good start..

[xLights_dbgrpt-880-20180120T135607.zip](https://github.com/smeighan/xLights/files/1649171/xLights_dbgrpt-880-20180120T135607.zip)

Thank you

**Comment by keithsw1111** [comment] 2018-04-06 22:26
I am not seeing a crash in the latest version. Can you try it again with 2018.9.

**Comment by keithsw1111** [comment] 2018-05-08 03:02
I am closing this issue as no follow up was received. If the problem is still occurring please reopen the issue.

**Closed by keithsw1111** 2018-05-08 03:02 UTC
Labels: Bug - Minor
