### ISSUE TITLE
Bug: Video Effect Start Time Slider Broken(?)

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#871] opened 2017-06-07 17:22 UTC
Please see video. I am unable to start the video later than 30 seconds in yet the video is over 5 minutes long and is a .mov file type.

This is xLights 2017.15 on a 64 Bit Windows PC running Windows 10.

[xLights Video Effect Bug.zip](https://github.com/smeighan/xLights/files/1058803/xLights.Video.Effect.Bug.zip)

**Comment by patdelaney** [comment] 2017-06-07 20:30
I didn;t think we could play MOV

Pat

**Comment by AzGilrock** [comment] 2017-06-08 02:46
You can play MOV format.  The slider isn't broken not sure what's going on.  I just tried a file and it went out past 3 minutes.  The slider is choppy because I guess its trying to render as you're dragging it.

**Comment by keithsw1111** [comment] 2017-06-11 03:46
I also cant reproduce the problem. Can you package up the sequence and send it to us so we can try to reproduce the problem.

**Comment by keithsw1111** [comment] 2017-07-10 18:32
Can we get more information on this or else we will need to close it.

**Closed** 2017-07-16 09:09 UTC
Labels: Bug - Trivial
