### ISSUE TITLE
Change to colorwash breaks existing effects/sequences

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#620] opened 2016-07-14 04:58 UTC
xLights was once great at not breaking existing sequences. Not so much with the rapid changes to effects and moving code to other sections.  With the removal of settings on color wash this error comes up.

Here is an existing color wash looking for old controls.

![image](https://cloud.githubusercontent.com/assets/10568498/16828444/a972c51c-4944-11e6-8a06-4f5db967b6c2.png)

and then one error for each of the X,Y locations.

![image](https://cloud.githubusercontent.com/assets/10568498/16828464/d99e0b8e-4944-11e6-9966-00e188ac655c.png)

**Comment by stevegiron** [comment] 2016-07-14 05:01
Ditto for any effect that once had Fit to Time as an option that still exists in the xml.  Please provide a way to upgrade these sequences without error.

![image](https://cloud.githubusercontent.com/assets/10568498/16828524/4d0cd08c-4945-11e6-9539-e320c140d5ee.png)

**Comment by keithsw1111** [comment] 2016-07-14 06:19
Can you post a sample sequence and I will see what I can do to fix it.

**Comment by AzGilrock** [comment] 2016-07-14 13:07
This is related to #496.  We need to fix how effects in old presets get updated.

**Comment by dkulp** [comment] 2016-07-15 12:34
There is code to fixup all these settings when it detects a sequence created from a version of xlights older than when they were eliminated.   If you are seeing this, there is likely a problem detecting the version of the sequence.   We'd NEED to see the sequence.

**Comment by AzGilrock** [comment] 2016-07-15 13:16
The problem is these are effect presets not sequences.  We didn't update the preset upgrade code when a lot of the recent effect changes were done.  We really need to modify it to somehow use the same effect upgrade functions but presets I'm not sure we've been archiving the xlights version with the preset exports.

**Comment by stevegiron** [comment] 2016-07-15 15:09
Dan, I've emailed you my xlights_rgbeffects.xml file.  Thanks - Steve

**Comment by dkulp** [comment] 2016-07-18 19:20
This should be fixed now, I hope.

**Closed by dkulp** 2016-07-18 19:20 UTC
Labels: Bug - Minor

**Comment by AzGilrock** [comment] 2016-07-18 19:34
If this is fixed then #496 could be closed.  I haven't reviewed this checkin but is the function  xLightsXmlFile::FixEffectPresets still called from anywhere and does it need to be fixed or deleted.  I know previously the effect presets had their own version number.  I think moving to use the xlights version is the right thing to do.  Would be nice to delete that function if we can.

**Comment by dkulp** [comment] 2016-07-18 20:03
FixEffectPresets is still there as it adjusts the structure of the effects in the file.  New attributes, new layout,  etc... would still involve this.    However, each effect (also effects in keybindings.xml) now have an additional "xLightsVersion" attribute (defaults to 4.0 if not specified) that indicates the version that created the raw settings data.   That is passed into the paste routine which can then use that to determine if the settings themselves need adjusting.   This DOESN'T actually change/update the data in the file at all.   It just updates settings at paste time.
