### ISSUE TITLE
OSC xScheduler Crash

### ISSUE THREAD

**Issue by GrizAF** [smeighan/xLights#1119] opened 2018-04-17 02:06 UTC
Got the OSC working an received several crashes relating to the same issue.  I believe the cause of the crash of "rapid" button pressing on the phone (kids....).  If that is the cause of the crash I can build in a delay buffer, but if that's not what is causing the crash please let me know.  Thanks!

[xSchedule_dbgrpt-10812-20180416T215432.zip](https://github.com/smeighan/xLights/files/1917912/xSchedule_dbgrpt-10812-20180416T215432.zip)

**Comment by keithsw1111** [comment] 2018-04-17 22:55
This has nothing to do with OSC per se. What is going on here is you swamped xSchedule with events to play playlists and it became overwhelmed ... and even threw its hand up when it logged ... "PlayListStep being destroyed but we appear to be manipulating it elsewhere. This may not end well."

Fixing this wont be easy. There are so many things going on the only thing I can try to do is slow things down and serialise them to avoid such problems.

**Comment by GrizAF** [comment] 2018-04-18 00:41
Keith - Thanks for the explanation.  Again, just kids getting their hands on it - and breaking my toys.  I don't know there is another fix other than saying "don't mash the buttons", which is fine.  Thanks for getting back with me on this issue.

**Comment by keithsw1111** [comment] 2018-08-18 10:42
I am closing this because i dont believe we are going to be able to reproduce and fix it. We can always either reopen it or create a new issue if it becomes more reproducible.

**Closed by keithsw1111** 2018-08-18 10:42 UTC
