### ISSUE TITLE
Crash when adding multiple items to group

### ISSUE THREAD

**Issue by Ellis101** [smeighan/xLights#1075] opened 2018-01-18 06:15 UTC
Not sure if this is something I am doing wrong but if someone could take a look please :)

[xLights_dbgrpt-5196-20180118T160812.zip](https://github.com/smeighan/xLights/files/1641797/xLights_dbgrpt-5196-20180118T160812.zip)

**Comment by keithsw1111** [comment] 2018-01-18 07:07
Is the crash happening repeatably? Any chance you could catch what you are doing on video

**Comment by Ellis101** [comment] 2018-01-18 07:14
I've had a few crashes while tinkering with basic sequencing on arches this arvo too, just random times.

I got the groups sorted but took a few times to get it done.

I will try to replicate the crash and video it.

**Comment by Ellis101** [comment] 2018-01-24 08:24
Haven't been able to get video but have had heaps of crashes at different times and random.

This time was removing a model after making a new one to replace it.

[](https://www.youtube.com/watch?v=YSIs5QZIGmk)

**Comment by Ellis101** [comment] 2018-01-24 08:25
[https://www.youtube.com/watch?v=YSIs5QZIGmk](url)

**Comment by Ellis101** [comment] 2018-01-24 08:25
[https://www.dropbox.com/s/tphq7511jgyw49x/Photo%2024-1-18%2C%206%2016%2033%20pm.jpg?dl=0](url)

**Comment by dkulp** [comment] 2018-01-24 18:03
Is this on OSX?   There is definitely a bug in the wxTreeListCtrl with the latest wxWidgets (that I'm testing specifically to flush out these things) that I've logged with them.   I do have a workaround for our code that I'm looking at, but there are other other bugs in wxTreeListCtrl as well causing weird sorting issues.

**Comment by keithsw1111** [comment] 2018-01-24 18:49
From the logs ... this is windows 64 bit

**Comment by Ellis101** [comment] 2018-01-24 20:17
Yes windows 64 bit. 
This started for me with 18.2 and is doing the same with 18.3.

Thanks for working on it.

**Comment by Ellis101** [comment] 2018-01-24 20:22
[xLights_dbgrpt-6272-20180121T164115.zip](https://github.com/smeighan/xLights/files/1661541/xLights_dbgrpt-6272-20180121T164115.zip)

**Comment by AzGilrock** [comment] 2018-01-24 20:24
Seems to have crashed doing a string sort.  You said it was while adding models to a group.  Did you happen to have that group expanded in the top pane?  Just trying to figure out how to reproduce it.  If you can find a fairly repeatable set of steps to cause it then we have a better chance of finding a fix.

**Comment by Ellis101** [comment] 2018-01-24 20:36
OK just tested the same as I did yesterday...

I created a basic spinner, then tried to delete a Boscoyo Mega Spinner. The crash happens at the time of trying to delete the mega spinner.
I just get the runtime error then it shuts down.

Hope that helps.

**Comment by Ellis101** [comment] 2018-01-24 20:42
In the original crash I was trying to add 50 models to a single group at one time, all highlighted then pressed arrow to copy to group.

**Comment by keithsw1111** [comment] 2018-04-06 22:46
Is this still happening?

**Comment by keithsw1111** [comment] 2018-05-08 05:12
I am closing this issue due to no follow up. If this is still a problem please reopen the issue.

**Closed by keithsw1111** 2018-05-08 05:12 UTC
Labels: Bug - Minor
