### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by davidwill1** [smeighan/xLights#980] opened 2017-11-11 05:36 UTC
I have put a bunch of crash files on here because xlights is crashing everytime I mess with pinwheel, or most of the icons. I don't know what I am doing wrong if I am causing it. I was using the most current .35 and I decided to go back a few releases to see if that changes, only went back to .31, nothing changed keeps crashing. I'm starting to thing it is my computer but haven'd done any change in quite some time. Any help would be appreciated.

**Comment by davidwill1** [comment] 2017-11-11 05:42
Apparently I can post the crash reports

**Comment by AzGilrock** [comment] 2017-11-11 11:28
Did you mean to say "can't"?
If you use the web interface you should be able to attach them just fine like I did here.

[xLights_dbgrpt-17184-20170126T171157.zip](https://github.com/smeighan/xLights/files/1463692/xLights_dbgrpt-17184-20170126T171157.zip)

**Comment by keithsw1111** [comment] 2017-11-11 21:03
Without your crashlog I will have to close this as we cant reproduce it.

**Comment by davidwill1** [comment] 2017-11-11 21:09
ok trying to get the crash logs posted, sorry

**Comment by keithsw1111** [comment] 2018-01-02 03:38
I am closing this as no new information has been posted to help us resolve the issue.

**Closed by keithsw1111** 2018-01-02 03:38 UTC
