### ISSUE TITLE
New twinkle render method is only single threaded

### ISSUE THREAD

**Issue by kkatee** [smeighan/xLights#2456] opened 2021-01-14 12:24 UTC
**Describe the bug**
xlights only uses a single cpu core when rendering the new twinkle effect

**To Reproduce**
Run 2021.1
create sequence with just twinkle
render all
Watch it only use one core. (and take forever)

**Expected behavior**
Use all the cores.

**Screenshots**
![image](https://user-images.githubusercontent.com/34851555/104590411-677e3a00-56bf-11eb-95c5-0cad3b1561d9.png)

**Versions (please complete the following information):**
 - OS: windows 10
 - xLights version 2021.1

**Additional context**

**Attachments**
[Test.zip](https://github.com/smeighan/xLights/files/5814370/Test.zip)

**Comment by kkatee** [comment] 2021-01-14 12:33
a 30 second twinkle effect on the everything group, on 5300 pixels, 40fps took 668.007 seconds to render.

**Comment by AzGilrock** [comment] 2021-01-14 13:39
You can switch back to the old render method for multiple cores.  Its single core by design.  The old method determined where to place twinkles and then they were locked in place.  That's what the new render method fixes but when I ran it in a parallel for loop which is what provides the capability to use multiple cores it had a bug because there is a common counter all threads need to be able to update so it kinda defeats the purpose of the parallel loop.  Its possible we could add a thread lock around that counter and it could help a bit because not every loop iteration will need to touch the counter.  Dropping effects on huge groups can be costly for some effects.

**Comment by kkatee** [comment] 2021-01-14 20:47
Costly is one thing, but a 30 second sequence with one effect on it shouldn't take 11 minutes to render on an i9

**Comment by kkatee** [comment] 2021-01-14 21:51
556x slower than the old renderer.

**Comment by dkulp** [comment] 2021-01-14 22:20
Just want to say I cannot reproduce this.   The Test.zip renders in 11.5 seconds in the DEBUG build (so slower) of 2021.01 on my Mac.

**Comment by kkatee** [comment] 2021-01-14 23:08
I don't know what was happening last night, but I didn't save any of the test sequences when I went to bed, and today when packaging my main layout to upload, I can't reproduce the problem to the same extent.

Its still slow compared to the old renderer (5x as long) but not the 500x longer I was seeing yesterday.


I'll upload it here anyway.
[MainHouseUpload.zip](https://github.com/smeighan/xLights/files/5817432/MainHouseUpload.zip)

**Comment by AzGilrock** [comment] 2021-01-14 23:46
Yeah I knew it wasn't optimal but I had spent enough hours and wanted to get it out there knowing we could improve it later.

**Comment by AzGilrock** [comment] 2021-01-14 23:58
Ok MainHouseUpload took 63 sec on my i7 so its a good baseline for me to test improvements.  Not sure if my 2 remote admin sessions have much effect to my performance.

**Comment by AzGilrock** [comment] 2021-01-15 00:19
Also when you do effects on a group its not just the number of pixels in your display.  That Everything group is set for a grid size of 400 so it can be up to a 400x400 buffer that the effect is rendering onto.  So the effect thinks its rendering onto 160,000 pixels.  Then the pixels map into those cells to figure out how each one gets painted.  I could be wrong but I think that's how the groups work.  I didn't write that part.

**Comment by AzGilrock** [comment] 2021-01-15 00:34
Well I checked in the debugger the buffer only ends up 59x260 so its treated as 15,340 pixels.

**Comment by AzGilrock** [comment] 2021-01-15 00:50
Well now that I've looked at what I did I forgot I had already made some improvements and in fact both algorithms utilize the parallel for loop so it does use multiple threads.  The new algorithm has to do a final run through to check for any lights that have expired and need to be reallocated.  You are doing 2 things which make the time really bad.  One is you are using the Per Model Default render style.  Since its just Twinkles its probably fine to just use the Default render style which reduced my render time from 63 to 31 seconds.  Then I noticed you also have it set for 100%.  That means there's a twinkle on every location.  The problem as you make that percentage higher is when the effect creates a random X/Y location to place the twinkle it tends to land on occupied locations so it takes a while to find an empty spot.  If I reduce the number of Twinkles to 50% it renders in 1.7 seconds.  So this appears to be a worst case scenario you normally wouldn't twinkle 100% of the lights.  I'm not sure I can make it any faster unless one of the other devs has an idea.

**Comment by kkatee** [comment] 2021-01-15 00:56
the reason i switched the render style is default treats the outlines on the sides of the verandah as one, so they all twinkle together, per model default got around this.

is there another render style you would recommend for better performance that doesn't do weird things on 3d outlines?

**Comment by AzGilrock** [comment] 2021-01-15 01:43
Not that I know of.  So put it back to Per Model Default and then reduce the effect to 95% and it should be much faster.  That only leaves 5% of the pixels off at any point in time but they will all still randomly come on.

**Comment by keithsw1111** [comment] 2021-01-15 05:33
@Gil ... instead of random x/y and checking if you know how many are available and generate a random number between 0 and available then count available until you get to your random number. That eliminates the hit/miss which can slow it down but requires you to scan for how many are available.

**Comment by AzGilrock** [comment] 2021-01-15 13:52
Yeah had a similar idea when I woke up today.  Thought about keeping a vector of available locations and then I only need one random number to index into the vector to grab the location which could be a single number if using a format like “width * y + x”.  Also thinking single threaded would be faster.  I’m already iterating through the list twice...once in parallel and a second time with a single thread to count num to place.  Single threaded I can go through the list just once and be able to write to the common available list.  Most of the time was lost “seeking” which can’t be run in parallel anyways.

**Comment by AzGilrock** [comment] 2021-01-16 19:02
@keithsw1111   So I've tried my idea and also what I thought you were suggesting and nothing seems to be faster.  It appears there is too much cost for using my vector idea when it needs to remove an item from the middle of the vector.  And your idea unless I didn't code it the way you thought seemed slower.  I would create a random number and then iterate through the list counting available locations until I got to that number.  So if there is 15000 pixels and it generate 14000 then that iterates 14000 times to place one light.  The original random number version had a chance to place on the first hit.

Only other idea I can think of is generate the entire list of random numbers, sort them and then run through the list once to find them.  Problem with that is then every number you generate you gotta check if you've already picked it so yet another search.

**Comment by dkulp** [comment] 2021-01-16 21:11
Gil, 

Can you test this patch?  Basically, it does a bunch of things:
1) All of the "strobes" are at the front of the strobe vector.  Thus, for smaller strobe %, the for loop has a lot less work to do.
2) It know exactly which x/y pairs do NOT currently have a strobe (at the end of the strobe vector) and thus can randomly chose one directly without checking.
3) uses an atomic_int so the for loop can increment the lights_to_renew directly.

[testpatch.txt](https://github.com/smeighan/xLights/files/5825131/testpatch.txt)

**Comment by AzGilrock** [comment] 2021-01-16 21:46
I never worked with patches.  Is there an easy way to apply that file?

**Comment by dkulp** [comment] 2021-01-16 21:54
> I never worked with patches. Is there an easy way to apply that file?

From the command line "git apply testpatch.txt" would do it, but not sure if you have a git command line thing.

**Comment by AzGilrock** [comment] 2021-01-16 22:35
Cool git did work from the command line to do that.  So I do believe that is faster but not a huge difference.    My VS debugger is painfully slow anyways so any little thing makes a big difference so its hard to test.  Like if I open the model preview it doubles the time.  If I dial the Twinkle back to about 90% so it doesn't take forever I saw about 50s with what's checked in and 44s with your change.  I'd say check it in.

**Closed** 2021-01-27 13:59 UTC
