### ISSUE TITLE
Alignment -> Align Both Times Problem 

### ISSUE THREAD

**Issue by idleup** [smeighan/xLights#669] opened 2016-08-24 15:46 UTC
Problem:
"Alignment -> Align Both Times" only works if both the start and end times of the source and target are different. If one of them is the same it does nothing. 

Proposed Solution:
If the end time of the target and source already are aligned, then continue the operation and align the start times. Same thing for the if the start times are already aligned then continue the operation and align the end times.

**Comment by AzGilrock** [comment] 2016-08-24 16:01
The code that moves the effects for alignment is the same for all alignment options.  There is an early piece of code that determines the align start and align end which is the only difference.  So that means this could happen with any alignment option.  Effects won't move if there is another effect blocking it but I have to make sure that the effect doesn't appear to block itself so there must be a boundary condition where if the effect to be moved is sitting on the edge of where it needs to go it thinks it's blocking itself.

**Comment by AzGilrock** [comment] 2016-08-24 23:53
I can't reproduce this.  I've tried a few different ways with the same start time and it's working.

**Comment by idleup** [comment] 2016-08-25 04:35
Thats strange, I will do more testing to find out what conditions if any I can get it working in, perhaps it is something with my environment like the fact that I am trying to align effects on groups or maybe specific effects. You did make the effects different sizes with the start times aligned right?

**Comment by AzGilrock** [comment] 2016-08-25 14:12
Yes I dropped them between timing marks and then dragged the endpoint longer on one of them.  As far as this functionality the effects don't look at which type of model they sit on.  It's purely assigned to an effect layer object which is the same for all model types.

**Comment by idleup** [comment] 2016-08-25 14:54
Try aligning to the longer effect. I think that is why it works for you and not me. I just tried aligning to the shorter effect and it worked, then did it again to align to the longer effect and it did not work.

**Closed** 2016-08-30 01:17 UTC
