### ISSUE TITLE
Multiple Mac V35 Issues with Crashes

### ISSUE THREAD

**Issue by byakymyk** [smeighan/xLights#1614] opened 2019-07-26 02:44 UTC
Mac xLights V35 - Mac Version 10.14.6 - OpenGL Set to V3
Manually set OpenGL version to 3 because check sequence states that shader will not render if set to lower version.
After opening sequence and rendering, I play sequence and background image does not render while playing.  The application eventually crashes at various points while using application.  Screen cap PNG included in zip file showing the background image does not exist.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3433990/xLightsProblem.zip)

**Comment by byakymyk** [comment] 2019-07-27 00:37
[xLights_dbgrpt-2549-20190726T203336.zip](https://github.com/smeighan/xLights/files/3437701/xLights_dbgrpt-2549-20190726T203336.zip)

**Comment by byakymyk** [comment] 2019-07-27 01:02
[xLightsProblemV2.zip](https://github.com/smeighan/xLights/files/3437718/xLightsProblemV2.zip)
Crash occurred when:
1) Opened xLights
2) Opened Sequence
3) Rendered Sequence
4) Crash when Save pressed

**Comment by byakymyk** [comment] 2019-07-28 13:40
[xLightsProblemV3.zip](https://github.com/smeighan/xLights/files/3439215/xLightsProblemV3.zip)
On V36B
xLights Lock Up with Spinning Wheel when playing sequence after:
1) Open xLights
2) Delete FSEQ file
3) Render All
4) Play Sequence
5) Lockup
Force quit xLights and restarted.  Reopened sequence and it played normally.  Went to change color of Pinwheel effect and crashed.  Attached log files

**Comment by byakymyk** [comment] 2019-07-28 18:38
[xLightsProblemV4.zip](https://github.com/smeighan/xLights/files/3439461/xLightsProblemV4.zip)
[xLightsProblemV5.zip](https://github.com/smeighan/xLights/files/3439462/xLightsProblemV5.zip)
On V Lubenow
V4 Problem is when trying to RenderAll and crashed
V5 Problem is when xLight hung playing and performed KillAll

**Comment by byakymyk** [comment] 2019-07-30 16:13
[xLightsProblemV6.zip](https://github.com/smeighan/xLights/files/3447680/xLightsProblemV6.zip)
Same hang issue on new V37

**Comment by dkulp** [comment] 2019-07-31 16:23
Can you test with the .37c build?

**Comment by byakymyk** [comment] 2019-08-01 01:46
[xLightsProblemV7.zip](https://github.com/smeighan/xLights/files/3454537/xLightsProblemV7.zip)
Generally working well especially on playback.  Hung after copying strand effect.

**Comment by keithsw1111** [comment] 2019-08-05 04:43
Every time you copy strand effect? I am not sure the hang is related so we will need more info. Unfortunately hangs dont log anything so it needs to be reproducible.

**Comment by keithsw1111** [comment] 2019-10-10 19:39
Closing due to lack of any new information

**Closed by keithsw1111** 2019-10-10 19:39 UTC
