### ISSUE TITLE
Linux: Model data for downloaded Models

### ISSUE THREAD

**Issue by AleXthePunK** [smeighan/xLights#1507] opened 2019-03-12 15:24 UTC
Hello. Someone in the zoom chat had a problem with the linux version. When they click on model data, of a downloaded model, it crashes. Attached is the bug report.
[xLights_dbgrpt-10332-20190312T111356.zip](https://github.com/smeighan/xLights/files/2957494/xLights_dbgrpt-10332-20190312T111356.zip)

**Comment by computergeek1507** [comment] 2019-03-12 21:00
Duplicate of #1456

**Comment by AleXthePunK** [comment] 2019-03-12 22:41
Sorry, I read that thread as a new custom image. I didn't realize it was the model data. Thanks for looking.

**Comment by ghormann** [comment] 2019-03-23 15:11
@keithsw1111  Patch has been applied. I believe we can close this one too.

**Closed** 2019-03-23 15:16 UTC
