### ISSUE TITLE
Moving tabs around and then selecting a tab will cause debug report

### ISSUE THREAD

**Issue by LightsOnHudson** [smeighan/xLights#139] opened 2015-04-01 23:07 UTC
I was moving the Tabs around (as I read that you could now do that). The tabs did move, but selecting one of the other tabs, clicking off of it, and selecting another tab or two very quickly caused a debug report . 

I'm trying to upload / attach the backtrace and it is telling me that it does not support that type of file. Try with PNG, GIF, or JPG. 
How is the proper way to add a debug zip file containing the elements that caused the crash and generated to the debug output?

**Comment by LightsOnHudson** [comment] 2015-04-01 23:09
Using OSX 4.0.10 (copy and paste of the Backtrace)

0   xLights                             0x000000010372fe00 _ZN10xLightsApp16OnFatalExceptionEv + 1472
1   xLights                             0x0000000103b63e9c wxFatalSignalHandler + 28
2   libsystem_platform.dylib            0x00007fff93db0f1a _sigtramp + 26
3   ???                                 0x000000000000005f 0x0 + 95
4   xLights                             0x00000001036e3dc2 _ZN12xLightsFrame15InitPapagayoTabEb + 5554
5   xLights                             0x000000010376fc9b _ZN12xLightsFrame23OnNotebook1PageChanged1ER18wxAuiNotebookEvent + 1419
6   xLights                             0x0000000103b69a3a _ZN12wxEvtHandler23SearchDynamicEventTableER7wxEvent + 186
7   xLights                             0x0000000103b696fd _ZN12wxEvtHandler12ProcessEventER7wxEvent + 253
8   xLights                             0x0000000103b69814 _ZN12wxEvtHandler19ProcessEventLocallyER7wxEvent + 164
9   xLights                             0x0000000103b696be _ZN12wxEvtHandler12ProcessEventER7wxEvent + 190
10  xLights                             0x0000000103a2b434 _ZN12wxWindowBase8TryAfterER7wxEvent + 228
11  xLights                             0x0000000103b695e6 _ZN12wxEvtHandler8TryAfterER7wxEvent + 22
12  xLights                             0x0000000103b69744 _ZN12wxEvtHandler12ProcessEventER7wxEvent + 324
13  xLights                             0x00000001037e84fc _ZN13wxAuiNotebook17DoModifySelectionEmb + 332
14  xLights                             0x00000001037e633c _ZN13wxAuiNotebook20SetSelectionToWindowEP8wxWindow + 364
15  xLights                             0x0000000103b682b0 _ZN16wxEventHashTable11HandleEventER7wxEventP12wxEvtHandler + 448
16  xLights                             0x0000000103b6971b _ZN12wxEvtHandler12ProcessEventER7wxEvent + 283
17  xLights                             0x0000000103b69814 _ZN12wxEvtHandler19ProcessEventLocallyER7wxEvent + 164
18  xLights                             0x0000000103b696be _ZN12wxEvtHandler12ProcessEventER7wxEvent + 190
19  xLights                             0x0000000103a2b434 _ZN12wxWindowBase8TryAfterER7wxEvent + 228
20  xLights                             0x0000000103b69744 _ZN12wxEvtHandler12ProcessEventER7wxEvent + 324
21  xLights                             0x00000001037df6c6 _ZN12wxAuiTabCtrl10OnLeftDownER12wxMouseEvent + 806
22  xLights                             0x0000000103b682b0 _ZN16wxEventHashTable11HandleEventER7wxEventP12wxEvtHandler + 448
23  xLights                             0x0000000103b697cd _ZN12wxEvtHandler19ProcessEventLocallyER7wxEvent + 93
24  xLights                             0x0000000103b696be _ZN12wxEvtHandler12ProcessEventER7wxEvent + 190
25  xLights                             0x0000000103b69adf _ZN12wxEvtHandler18SafelyProcessEventER7wxEvent + 15
26  xLights                             0x00000001039368b4 _ZN17wxWidgetCocoaImpl18DoHandleMouseEventEP7NSEvent + 100
27  xLights                             0x000000010393286d _ZN17wxWidgetCocoaImpl10mouseEventEP7NSEventP6NSViewPv + 173
28  AppKit                              0x00007fff91efca18 -[NSWindow _reallySendEvent:] + 12721
29  AppKit                              0x00007fff9198316e -[NSWindow sendEvent:] + 446
30  xLights                             0x0000000103923905 -[wxNSWindow sendEvent:] + 117
31  AppKit                              0x00007fff91935451 -[NSApplication sendEvent:] + 4183
32  xLights                             0x0000000103896af8 -[wxNSApplication sendEvent:] + 136
33  AppKit                              0x00007fff917c1608 -[NSApplication run] + 711
34  xLights                             0x0000000103919c34 _ZN14wxGUIEventLoop8OSXDoRunEv + 116
35  xLights                             0x0000000103b43514 _ZN13wxCFEventLoop5DoRunEv + 52
36  xLights                             0x0000000103aa0d75 _ZN15wxEventLoopBase3RunEv + 165
37  xLights                             0x0000000103a6e481 _ZN16wxAppConsoleBase8MainLoopEv + 209
38  xLights                             0x00000001038dbb0a _ZN5wxApp5OnRunEv + 26
39  xLights                             0x0000000103ad8a97 _Z7wxEntryRiPPw + 71
40  xLights                             0x000000010372e8f4 main + 20
41  xLights                             0x000000010356aab4 start + 52

**Comment by stevegiron** [comment] 2015-05-18 22:30
As of May-14 we are version 4.0.31. Is this issue still occurring?

**Comment by LightsOnHudson** [comment] 2015-05-19 05:41
I will test and let you know.

**Comment by stevegiron** [comment] 2015-07-09 20:47
With 4.1.10 7-8-15 are you still having this issue?
http://nutcracker123.com/nutcracker/releases/

**Comment by AzGilrock** [comment] 2016-02-16 03:27
I tried to cause this and it doesn't seem to crash on Windows.  If nobody reports this is still an issue I'll close this next time I go through the list.

**Comment by AzGilrock** [comment] 2016-05-13 22:23
Couldn't reproduce with latest version.  Plus we are working on removing all the tabs eventually

**Closed by AzGilrock** 2016-05-13 22:23 UTC
Labels: Bug - Trivial, Waiting for user feedback
