### ISSUE TITLE
xLights Causes Bluebeam Revu Hardware Rendering to be Disabled

### ISSUE THREAD

**Issue by jdonleyco** [smeighan/xLights#2416] opened 2020-12-15 20:58 UTC
This is a weird issue since it is not related to the functioning of xLights, but an issue with another program after installing xLights.

**Describe the bug**
Installing xLights on my computer causes my Bluebeam Revu program to stop opening PDFs.  I start getting an error message in Bluebeam stating "Hardware rendering has been disabled due to an issue with the graphics driver."  If I uninstall xLights Bluebeam starts to work again without any problems.

EDIT:  Installing Xlights32_2020_53 seems to not cause the issue.  Possibly only the 64bit version causes the issue.

**To Reproduce**
1.  Install xLights on a system with Bluebeam Revu installed.
2.  Open any PDF in Bluebeam causes the error message.

**Expected behavior**
I expected Bluebeam to open PDFs with xLights installed.

**Screenshots**
Screenshot of error message from Bluebeam if it is any help.
[https://www.dropbox.com/s/g0y66479kgcr0by/BluebeamError.PNG?dl=0](url)

**Versions (please complete the following information):**
 - OS: Windows 10 Pro
 - xLights version 2020_55.  Also tried a few older versions with the same issue

**Comment by keithsw1111** [comment] 2020-12-17 10:11
This is likely a path issue. xLights amends the systems path which in rare situations can cause problems like this. Can I suggest you edit your path and either move xLights to the bottom or remove it in total but there is a risk that will break xLights.

**Comment by Cassock** [comment] 2020-12-28 16:54
Duplicate of #2156

**Comment by Cassock** [comment] 2020-12-28 17:10
Moving the xLights entry to the end of the path had no effect for me. Deleting it altogether seems to have restored Bluebeam functionality and there are no immediately apparent issues with running xLights64 2020.56. Presumably I'll have to delete the path entry every time xLights is updated.

**Comment by cottonwood99** [comment] 2021-02-24 16:55
I recently have had the same issue.  I contacted Bluebeam and they confirmed there is a known issue with a shared DLL (SDL2.dll).  Below is their response.  

**Thank you for contacting us. The description of the issue, along with the errors recorded in the logs fall in line with a known problem caused by applications called "Xlights" or "MatLab". These are more common applications that we've seen reported which use the " SDL2.dll" file, which is the underlying issue. Any application that uses the SDL2.dll file will cause this problem with Revu. Uninstalling the application that uses this dll file will resolve the problem. Alternatively, if these applications must remain, using Revu x32 is the only other workaround.**

**Comment by AzGilrock** [comment] 2021-02-24 17:00
Well xLights and Matlab are the bigger fish so tell Bluebeam Revu to fix their shit...lol.

**Comment by dkulp** [comment] 2021-04-03 19:43
This isn't an xLights issue IMO.

**Closed by dkulp** 2021-04-03 19:43 UTC
