### ISSUE TITLE
Circle Effect - Radial 3d ignores Pallete

### ISSUE THREAD

**Issue by ncosper** [smeighan/xLights#1796] opened 2019-10-30 21:04 UTC
As the title insinuates I noticed that when applying to rendering a sequence that uses the 3d radial option in the Circle effect it uses a rainbow vs the pallet. Didn't see a way around it so think it could be a bug.

**Comment by AzGilrock** [comment] 2019-10-30 21:20
I just explained why it works like this when closing Issue #915 a few days ago.

**Closed by AzGilrock** 2019-10-30 21:20 UTC

**Comment by ncosper** [comment] 2019-10-30 21:23
Interesting, so nothing was changed? I had a sequence from March that had this effect in it several times and with the current xlights version it was rendered completed different than in march. Not a big deal if its working the way its intended now it was just different than I found before and it looked broken.

**Comment by AzGilrock** [comment] 2019-10-30 21:29
What I believe changed was in the older versions you had to have Radial checked or else Radial 3D did nothing.  I think Keith made a change that now allows Radial 3D to work without checking Radial so that could be the cause of it changing.  You should be able to verify it if you open in the older version vs the new one and look at the options selected.

**Comment by computergeek1507** [comment] 2019-10-30 23:00
I had the same issues, I unchecked Radial 3D and the effect reverted to the old look.

**Comment by AzGilrock** [comment] 2019-10-31 01:04
Well then you guys probably had Radial3D checked by itself.  In the old version that checkbox did absolutely nothing unless Radial was also checked.  So if it was checked solo and then you upgraded it was changed so that now it does something.  So in that sequence you guys were using it was checked when it didn't need to be.
