### ISSUE TITLE
On Import Effects not all models are showing to import from

### ISSUE THREAD

**Issue by ctrobbins** [smeighan/xLights#4219] opened 2023-12-14 18:44 UTC
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
When trying to Import Effects from a vendor sequence, one of the models does not appear on the right hand list. In this case the "Spiral Trees" model group does not appear in 2023.22, but does appear when using 2023.20 on a Windows 11 machine. The model has 149 effects so would be expected to show up. This was discovered when trying to import the "Save your Tears" sequence from RGB Sequences (available upon request).
![Screenshot 2023 20 Import Effects](https://github.com/smeighan/xLights/assets/10458941/3ef16a70-54de-4311-902d-01334723cf54)
![Screenshot 2023 22 Import Effects](https://github.com/smeighan/xLights/assets/10458941/5c05c67d-69e3-47fe-9651-2912af52dfba)

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Create new sequence
2. Click Import Effects
3. Select sequence file to import from (sequence file from RGB Sequences - The-Weeknd-AG-Save-Your-Tears-HD.zip is available upon request)
4. See that "Spiral Trees" does not exist on the right hand list

**Expected behavior**
That all models, submodels, and model groups with effects would appear on the right hand list.

**Screenshots**

**Versions (please complete the following information):**
 - OS: Windows 11
 - xLights version 2023.22

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by AzGilrock** [comment] 2023-12-14 18:49
This is a duplicate of #4188 
Temporary fix is turn off Dark Mode.

**Closed by AzGilrock** 2023-12-14 18:49 UTC
