### ISSUE TITLE
Mac preview screen bug 

### ISSUE THREAD

**Issue by zcloutier** [smeighan/xLights#904] opened 2017-08-30 13:22 UTC
i have a problem in xlights where all of my different previews will move to my main monitor on my MacBook Pro  anytime i click on something that opens a new window. it does it when i create a new sequence, import effects, open the rendering box that shows what is rendering and what has already rendered, change tabs and if i don’t save a sequence before i save it and it pops open the box if i want to save or disregard changes it also does it when i open a sequence and i have not saved yet but if it is saved and i go and open a different sequence it does not do it. i have also done some testing with a pc and it does not do it at all. i have my perspective saved and it did not do it until the 2017.15b release and every release sense has done it.

**Comment by AzGilrock** [comment] 2017-08-30 14:05
Duplicate of #884.

**Comment by dkulp** [comment] 2017-08-30 14:24
This is LIKELY a wxWidgets bug if it introduced in 2017.15b.    Between 2017.15 and 2017.15b, I had to update wxWidgets a bit as it would no longer compile with the latest Xcode that was released at that point due to the removal of the older (long deprecated) media code.

**Comment by zcloutier** [comment] 2017-08-30 14:44
I know its a Duplicate but was hoping that since I figured out exactly when it started happening that it might help with a solution to this. Before we just thought it was a random thing but after testing on multiple computers and going back in versions we came up with a timeline to try to help. Not sure if there is a fix but will help with whatever we can.

**Comment by AzGilrock** [comment] 2017-08-30 14:53
Dude its just a reference for us to know to close both when it's fixed.  Otherwise I would have closed it but I thought it contained good additional info.

**Comment by zcloutier** [comment] 2017-09-18 22:17
@dkulp have you had any time to figure out what is causing this issue? Is there any other information you need or anything I can help test?

**Comment by dkulp** [comment] 2017-09-18 22:22
Haven't really looked.  I did just update to the latest wxWidgets code (to fix the popup menus on the WiringView dialog) so it might be different in 2017.28, but I'm not really sure.

That said, I also haven't been able to reproduce it repeatably on my machine (dual monitors as well).  It sometimes does it ONCE after I open xLights, but then is OK the rest of the time xLights is open.

**Comment by zcloutier** [comment] 2017-09-18 22:42
Ok, I went to 2017.28 and it still does it like it did before like I listed above I will stay on 2017.15 for now but I will keep checking when the new updates come out and see if it is fixed. Is there any setting I should try to change if not I am more than happy to test if you need me to. Below I have the specs to my mac.
![screen shot 2017-09-18 at 5 32 03 pm](https://user-images.githubusercontent.com/14355198/30567897-1fb2b578-9c98-11e7-8d5a-778baffc6e3a.png)

**Comment by dkulp** [comment] 2017-09-18 23:11
Actually, can you send me your xlights_* files and maybe a sample sequence (dan at kulp  dot com)?  With 2017.28, I cannot even reproduce what I was seeing before.   The previews all stay right where I put them and saved in the perspective.    I can pop up the "rendering status" window and they stay right where they were.

**Comment by zcloutier** [comment] 2017-09-18 23:26
I just sent it, if you have any questions shoot me a message.

**Comment by dkulp** [comment] 2017-09-19 16:06
I just stuck a 2017.28b version up.  Can you give that a try?   It's using a different method to hide/restore the floating windows that I hope avoids whatever is triggering the movements.

**Comment by zcloutier** [comment] 2017-09-19 16:14
That did not fix it. Do you think it could be a graphics card problem?

**Comment by AzGilrock** [comment] 2019-10-04 13:49
Closing since its been over a year and half since anyone talked about this.  Its either gone away or nobody can reproduce/fix it.

**Closed by AzGilrock** 2019-10-04 13:49 UTC
Labels: Bug - Trivial
