### ISSUE TITLE
Model Channel Grid odd behavior with Individual Start Chans check box.

### ISSUE THREAD

**Issue by patdelaney** [smeighan/xLights#186] opened 2015-04-08 18:53 UTC
I'm not sure if this is by design or just a wierd bug:
I have created a model in xLights that will address only a certain region of a Matrix. I have mapped the channels using Individual start chans. I save the model, and close xLights.

When I restart xLights and go to model dialog and modify that model. the screen comes up like this:
Individual start chans is checked, but the start channel is 30001, but that doesn't match the grid
![grid1](https://cloud.githubusercontent.com/assets/8147459/7052827/9ccba636-ddf6-11e4-969a-9fb8bf485244.JPG)

If I uncheck the check-box then the channels change?

![grid2](https://cloud.githubusercontent.com/assets/8147459/7052832/a152833c-ddf6-11e4-9b14-409684afd23f.JPG)

IS this a problem?

**Comment by patdelaney** [comment] 2015-04-08 19:05
After discussing with Ben, we have determined that this is somewhat self-inflicted. I did enter that start channel 30001, at first but then we decided to try a different way to build the model. So the issue as described in not an issue.

But if you change the Start Channel entry to match the channel that you really want to start on, and if you are using Individual start channels, if you build that channel assignments but unchecked the Individual Start Chan checkbox, you will loose your mapping, even if you check it again.

The work around is just cancel.  I guess this could be release noted.

**Comment by stevegiron** [comment] 2015-04-08 21:39
Pat you can also create a custom model, paste from Excel and call it a day. 
![image](https://cloud.githubusercontent.com/assets/10568498/7055982/f71e2bf8-ddfc-11e4-884f-db0907eb3e02.png)

**Comment by AzGilrock** [comment] 2015-04-08 23:09
If I'm interpreting this right everything sounds like it's working as intended.  The individual start channels box is a manual override.  If you uncheck it the channels are going to revert back to sequential auto-numbering from the specified start channel.

**Comment by dkulp** [comment] 2015-04-08 23:39
Right.  Working as designed.  Enhancement request would be to disable the start channel  controls if the check box is checked to really denote that it doesn't have any real affect.

**Comment by LightsOnHudson** [comment] 2015-04-09 13:12
Also, what Pat and I noticed, is that if you have a value in the Start channel box. in this case 30001. And you click ' individual start channels ' check box, and put in a value - say 192. The Start channel box still remains at 30001. It would be nice to have this update to the first value of the first line so that the other enhancements that have been requested, that the start channel and channel count are made visible on the MODELS list instead of having to click into each model using the modify button to see what channels are in use. 

Can this be done?

**Comment by stevegiron** [comment] 2015-05-18 20:24
Per Dan "Working as designed." Closing this issue.

**Closed by stevegiron** 2015-05-18 20:24 UTC
