### ISSUE TITLE
Twinkle effect issue

### ISSUE THREAD

**Issue by aggie81** [smeighan/xLights#2738] opened 2021-08-06 17:06 UTC
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
This is similar to tracker reports 2602 & 2674. Currently on 2021.24 but started seeing this 4 or 5 releases back. If I have more than one instance of the twinkle effect on a model, the first works OK but subsequent ones have this funny stuck on white thing for the first bit of the effect. I tried to boil this down to the simplest test I could do. Created a new show folder with just one matrix, then a simple test animation with only twinkle effect. I get the attached result. This is just 4 twinkle effects separated by 1 sec gap (does not matter if they are touching each other, get the same thing). Funny thing is if I select one of the effects that are doing this, the model preview shows it correctly. But if I re-render it comes back.

**To Reproduce**

1. Create a new temp show folder and create a simple layout with just one matrix.
2. Start a new animation
3. On the matrix add several instances of the twinkle effect with multiple colors. new render method.
4. First effect works OK but subsequent ones have a stuck on white flash at the beginning of the effect.

**Expected behavior**
Twinkle to work correctly (it did on releases earlier in the year).

**Screenshots**
Attached

**Versions (please complete the following information):**
 - OS: Windows 10 (on several different PCs and laptops, all do same thing)
 - xLights version 2021.24

**Additional context**

**Attachments**
- Packaged test sequence, screen shot and house view movie.
[TwinkleTest.zip](https://github.com/smeighan/xLights/files/6946968/TwinkleTest.zip)
![TwinkleTest](https://user-images.githubusercontent.com/9982279/128546437-86baf41c-17fd-4f6d-8ad2-56215ae59980.jpg)

https://user-images.githubusercontent.com/9982279/128546458-b07f40bf-e63c-459a-a1b8-7ff6f317ceeb.mp4

**Comment by aggie81** [comment] 2021-08-06 17:10
Should add this only does this with new render method, old seems fine. I also see this in a much more complex real sequence but figured this simple test sequence might be a better example. But I can send a full sequence if necessary.

**Comment by aggie81** [comment] 2021-08-06 17:29
Just determined this, I have three colors selected in the twinkle effects. What ever the firs color is (to the left on the color selections) will be the color of what I call the "flash" at the beginning of the effects that show this.

**Comment by AzGilrock** [comment] 2021-08-06 18:05
You say it wasn't a problem in earlier versions in the year.  If you did some legwork to figure out which version it quits working on there's a higher chance of it getting fixed.  Its easy to install multiple versions side-by-side just rename the install folder with the version number on the end.

**Comment by aggie81** [comment] 2021-08-06 18:36
My apologies, I think I fooled myself in regards to it working OK in earlier releases. I had frozen last year at 2020.40 which didn't have the new twinkle render method. When I picked up this year I started with 2021.15 and noticed some of my sequences didn't look the same, but with help from the FB group figured out it was the new twinkle render style. Got that shorted out on all my existing sequences and everything looked OK. Then recently I updated to 2021.21/22/23/24 regularly as they came out. At the same time I was working on a totally new sequence in which I started noticing this and just thought it was a recent development. Guess I had just never used twinkle in this exact way.

I did as you asked and went back all the way to 2021.02 and it still acts the same as described above with the included test sequence. So as far as I know this has been this way since the new twinkle render method was added.

In any event, it seems easy to me to reproduce and obviously is not the desired result (plus some similar reports have been logged from my searching), so hopefully it can be tracked down or let me know if I am doing something wrong.

Thanks for all you guys hard work! Let me know if I can help in any way.

**Comment by AzGilrock** [comment] 2021-08-06 18:48
Ok that helps.  I only was dropping one effect when I wrote the new render method.  I assume you are doing a render all and its completing first.  The new render method can take a lot longer than the old one on larger models.  I hadn't looked into this before before both the old tickets you referenced ended up either having a ton of node effects or ended up not be reproducible.

**Comment by aggie81** [comment] 2021-08-06 18:56
Glad it helps and again sorry for the misinformation. Just to let you know, I have tried this on my Win10 Laptop, Win10 desktop and for grins I just tried it on Debian 18 running in a VirtualBox. All do the same thing. BTW I much prefer the new render method, thanks for putting it in! Again let me know if you need anything from me.

**Comment by aggie81** [comment] 2021-08-06 19:05
And yes I am doing a render all. If I was not clear before the strange thing is if I do a render all and play it back in the house preview I see the flashes. But if I then click on and select each effect it shows properly in the model preview and then if I play it in the house preview (without hitting the render all button) then it plays back OK! But once I do a render all it comes back. So I wasn't sure if this actually ends up in the fseq file or was just a house view playback problem. I have not tried this on real HW and lights yet  to see if it is indeed like this in the final fseq output file.

**Comment by kkatee** [comment] 2021-08-06 19:13
https://github.com/smeighan/xLights/issues/2602

**Comment by AzGilrock** [comment] 2021-08-06 19:20
Yes I looked at #2602 before and when you said you couldn't reproduce it in a new sequence I moved on.  The sequence provided here appears to be a much nicer example since its isolated to just a few effects.

**Comment by kkatee** [comment] 2021-08-06 19:23
I was able to reproduce it after reading your post. It only does it if there is multiple twinkles on the timeline for the same group and I only did 1 in the test sequence.

**Comment by nmiller0113** [comment] 2021-08-06 20:32
> Glad it helps and again sorry for the misinformation. Just to let you know, I have tried this on my Win10 Laptop, Win10 desktop and for grins I just tried it on Debian 18 running in a VirtualBox. All do the same thing. BTW I much prefer the new render method, thanks for putting it in! Again let me know if you need anything from me.

@aggie81, I didn't realize there was a new render method. Do you know when that was released?

**Comment by kkatee** [comment] 2021-08-06 20:37
I think it was added in 2020.57, but it didn't work quite right in the first release.

**Comment by nmiller0113** [comment] 2021-08-06 20:46
> I think it was added in 2020.57, but it didn't work quite right in the first release.

Thanks @kkatee, I was trying to find the release notes in Git but for some reason could not find it.

**Comment by aggie81** [comment] 2021-08-06 21:07
@kkatee is correct and updated in some later releases (last was 2021.20.

2020.57 December 29 2020
   -- enh (gil)    Twinkle effect has new algorithm that is more random to cover all pixels.  Old algorithm can still be selected.

Select in the effects settings for twinkle. Looks a lot more random and better to me!

![image](https://user-images.githubusercontent.com/9982279/128570893-61f15807-211f-49d9-b356-ad6092278eb5.png)

**Comment by AzGilrock** [comment] 2021-08-07 20:12
I made a change that fixes it (not committed yet) but I'm not sure its the right fix.

@dkulp or @keithsw1111  I'm pretty sure this cache technique is used in other effects.  I assumed every effect would get its own cache but on a whim I added this line which forces a new cache whenever the render is at the start of the effect and it fixes the problem.  So that means this render cache is carrying over for all future Twinkle effects.  Is there a better way to deal with this?

![image](https://user-images.githubusercontent.com/2024669/128612785-cbf89b9b-cd12-4085-b92c-42aff9c6b6fb.png)

**Comment by AzGilrock** [comment] 2021-08-07 20:13
Problem with that fix is it would not work for multi-threaded rendering

**Comment by dkulp** [comment] 2021-08-07 20:18
I wouldn't create one there.    After that block, do an if (buffer.needToInit) { .... } and re-initialize anything that needs to change at init time.

**Comment by AzGilrock** [comment] 2021-08-07 22:48
Ok I already had a needToInit section I just missed a variable that needed to be reset.

**Comment by AzGilrock** [comment] 2021-08-07 22:53
This should be fixed for next release

**Closed by AzGilrock** 2021-08-07 22:53 UTC
