### ISSUE TITLE
Linux - xLights-2019.59-x86_64.AppImage fails to breakdown words

### ISSUE THREAD

**Issue by tgodfrey73** [smeighan/xLights#1781] opened 2019-10-24 04:01 UTC
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
-Enter a label on the timing track, breakdown phrase will break the words apart on [2], breakdown work results in an error -'Failed to open Phoneme dictionary.' The error message is repeated 2 more times when clicking OK and then displays 'Failed to open Phoneme Mapping File!' 
-This has been an ongoing error since around appImage 40 or 41. 

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. Create a new animation or sequence
2. Set a timing mark
3. Enter a label
4. Right click to breakdown the phrase
5. Right click on a word or works to breakdown word

**Expected behavior**
Should breakdown the word to syllables 

**Screenshots**

**Versions (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - xLights version: xLights-2019.59-x86_64.AppImage but has been a problem since around 40 or 41 I believe 

**Additional context**
2019-10-23 22:53:55,640 140277314321280 log_base [DEBUG] Keybinding fired: TIMING_ADD 
2019-10-23 22:54:10,698 140277314321280 log_base [DEBUG] OnGridPopup - ID_GRID_MNU_BREAKDOWN_PHRASE
2019-10-23 22:54:12,083 140277314321280 log_base [DEBUG] EffectsGrid::mouseDown effect selected Hello.
2019-10-23 22:54:13,825 140277314321280 log_base [DEBUG] OnGridPopup - ID_GRID_MNU_BREAKDOWN_WORD
2019-10-23 22:54:13,825 140277314321280 log_base [WARN] Failed to open phoneme dictionary. 'user_dictionary'
2019-10-23 22:54:13,825 140277314321280 log_base [ERROR] DisplayError: Failed to open Phoneme dictionary!
2019-10-23 22:54:14,976 140277314321280 log_base [WARN] Failed to open phoneme dictionary. 'standard_dictionary'
2019-10-23 22:54:14,976 140277314321280 log_base [ERROR] DisplayError: Failed to open Phoneme dictionary!
2019-10-23 22:54:15,627 140277314321280 log_base [WARN] Failed to open phoneme dictionary. 'extended_dictionary'
2019-10-23 22:54:15,627 140277314321280 log_base [ERROR] DisplayError: Failed to open Phoneme dictionary!
2019-10-23 22:54:16,327 140277314321280 log_base [ERROR] DisplayError: Failed to open Phoneme Mapping file!
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3765642/xLightsProblem.zip)

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use 

Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/3765644/xLightsProblem.zip)
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by AzGilrock** [comment] 2019-10-24 13:00
Duplicate of #1707.  When it gets fixed there it will be fixed but there is only 1 person that seems to fix Linux issues if you want to step up.  That issue claims they fixed the problem by building from source.

**Closed by AzGilrock** 2019-10-24 13:00 UTC
