### ISSUE TITLE
Crash on 22.10 Singing Faces Effect

### ISSUE THREAD

**Issue by jonash326** [smeighan/xLights#3247] opened 2022-05-16 21:21 UTC
The Singing faces effects seems to crash 22.10 when applied to a model in the sequencer tab. 
Here are a few tests:
-Crashes regardless of which timing track is used
-Crashes regardless of if a Phoneme or Timing Track is selected in the effect properties
-Crashes regardless of if there is faces defined or not, and regardless of the custom model
-Crashes regardless of placing a new effect on the grid, or copy-pasting a faces effect from another model
-Also crashes when the effect is selected in the grid (from a previously created sequence)
-Crashes on a brand new layout, network, and sequence; with only one controller, one model, and one effect
-Crashes on Mac and PC (22.10)

The last version that I know of that works is 2022.06, as suggested by another similar GitHub issue with the state effect.

**Comment by AzGilrock** [comment] 2022-05-16 21:34
Sounds like this is a duplicate of #3242 and #3243 which Dan says is fixed for next release.

**Comment by dkulp** [comment] 2022-05-16 22:04
It might not be.  The fix for that was specifically when dropping the Faces effect on a model which might not be the same as all the things listed above.   Since Mac was mentioned, the easiest way to check would be to update to the latest in the App store (2022.10.1) and see if that fixes the crash on the Mac side.   Or try with the windows nightlies.

**Comment by computergeek1507** [comment] 2022-05-16 23:04
The window nightlies are broken until Keith updates the libltc lib or I skip xSchedule

**Comment by derwin12** [comment] 2022-05-17 23:18
My bug noted above is indeed fixed in the nightly build.
https://github.com/smeighan/xLights/suites/6546376808/artifacts/244487102

**Closed** 2022-05-18 07:22 UTC
