### ISSUE TITLE
"On" Effects, Properties not responding

### ISSUE THREAD

**Issue by wwid4christ** [smeighan/xLights#976] opened 2017-11-08 14:13 UTC
I'm new to xlights this year, so my setup is fairly simple. I'm starting with two dmx dimmer packs to control my existing lighting, so my sequence only has 8 channels total. Should be a breeze once I work out the kinks! Everything started out fine in the show as I'm only using the "On" effect to program right now, however after a couple of instances of fading in or shimmering, the properties of the "On" effect have stopped responding. Thus, I cant produce any fades or shimmering. I've tried a reboot already to see if its just a glitch, but it didn't resolve the issue. Not sure if its something I need to change or if its a hiccup in the program? Any chance that a fresh Install would fix it?

**Comment by AzGilrock** [comment] 2017-11-08 14:37
There's a 98% chance you just have a setting wrong.  Those panels tend to retain their settings so check everything.  I've seen people leave the brightness slider at 0 or move the Morph slider over and it totally blanks out the entire effect.  Reinstalls generally never fix anything because we don't delete anything when you uninstall that has effects on the sequences.

**Comment by wwid4christ** [comment] 2017-11-08 15:30
I'll double check the settings this evening.  I know last night I even tried copy and pasting the original couple of instances that were working, and the copied ones still wouldn't work. I'll dig through and recheck myself though. Thanks for the help!

**Comment by keithsw1111** [comment] 2018-05-08 03:03
I am closing this because we seem to have no follow up to the request for a copy of the sequence. If the problem is still current please reopen the issue.

**Closed by keithsw1111** 2018-05-08 03:03 UTC
