### ISSUE TITLE
Collapse All Not working

### ISSUE THREAD

**Issue by SniperMunyShotz** [smeighan/xLights#1145] opened 2018-06-02 05:08 UTC
I was not able to perform a collapse all in the sequence, but could do it individually.  Tried doing it with timing selected, unselected, everything selected etc.

**Comment by keithsw1111** [comment] 2018-06-08 06:08
I cant reproduce the problem I have tried it several times expanding all sorts of things and they all collapse just fine. Can you provide screen shots or something so we can see exactly what you mean otherwise I will need to close the issue.

**Comment by SniperMunyShotz** [comment] 2018-06-08 14:00
https://www.dropbox.com/s/jxnqwwpx0zf084b/2018-06-08_09-57-00.mp4?dl=0

It could be that it is not supposed to happen and it is not a bug as it will collapse the level below the layers, but was hoping that when you collapse all, it takes all the layers down to one instead of hitting the plus sign.

**Closed** 2018-06-10 02:56 UTC
