### ISSUE TITLE
Missing File Dialog Box

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#522] opened 2016-04-07 02:31 UTC
2016.17
I found that if you perform the sequence of operations below the file dialog box will no longer be displayed for selecting an existing sequence or creating a new sequence.

1. Start Xlights.
2. Open any existing sequence.
3. Undock "House Preview".
4. Close the sequence.
5. Dock "House Preview".
6. Try to open an existing sequence or create a new sequence.  The file dialog box does not appear any longer when you select the "New Sequence" or "Open Sequence" icon or use the file menu drop down box.  You either have to undock the "House Preview" or restart the application to be able to see the file dialog box again.

Denny

**Comment by AzGilrock** [comment] 2016-04-07 04:01
Whatever is causing this is the exact same root cause as what's causing issue #520.  It's basically something with the floating panels that is putting the application into a state where events aren't firing.  There is another workaround other than closing the panel.  Just make sure you have another application open like Internet Explorer and when this happens you can click on that app to change focus and then when you click the focus back to xLights it will work.

**Comment by AzGilrock** [comment] 2016-05-12 02:01
This was fixed when #520 was fixed.

**Closed by AzGilrock** 2016-05-12 02:01 UTC
Labels: Bug - Trivial
