### ISSUE TITLE
Vertical mirror Text while Exporting any format from matrix model (gif or avi)

### ISSUE THREAD

**Issue by Kamal-Sonani** [smeighan/xLights#1981] opened 2020-03-22 19:22 UTC
50x50 matrix 
Text layer is on top of other 2 layer

While i try to export , text goes vertical mirror in exported output. (Gif or avi)

For now i fix this issue manually by flipping vertical from layer setting.

**Comment by bchiaino** [comment] 2020-03-22 19:54
same here, confirmed on mac, I exported a bunch and I have to flip vertical, Also Kamal if you play it back on the actual matriculates you will notice the blacks are purple so any pixel that should be off is actually a dull purple, I reported in another thread just wanted to give you the heads up cause all looks good in xlights but once I plugged in lights I noticed the issue

**Comment by keithsw1111** [comment] 2020-03-23 07:31
I dont see it guys ... I have done this several times and every time it comes out perfect ... what are you doing I am not

**Comment by bchiaino** [comment] 2020-03-23 12:45
I will try and reproduce later, working from home, my big issue is in the other thread where "off" or spots that should be black are a dull purple, that is very easily reproducible

**Comment by bchiaino** [comment] 2020-03-23 15:24
Keith, this actually looks like it may have been fixed in .10. I went thought each release from 2020.05 to 2020.11 and 5-9 have the "vertical flip" issue but 2020.10 and 11 exported fine on the same model as you can see in the pic

Karmal, can you update to .11 and try again? Im on my mac trying, not sure if this differs on PC

<img width="443" alt="Untitled" src="https://user-images.githubusercontent.com/40632971/77332779-e05b7200-6cf8-11ea-8817-2991833631b7.png">

**Comment by computergeek1507** [comment] 2020-03-23 15:49
Gif exporting was upside down in version 2020.5-9. Kieth fixed it in .10, I had the 0,0 point in the wrong location when I added the code in 2020.5

**Comment by bchiaino** [comment] 2020-03-23 16:42
> Gif exporting was upside down in version 2020.5-9. Kieth fixed it in .10, I had the 0,0 point in the wrong location when I added the code in 2020.5

thank you, is there a way to look at the other request I put in about the pixels that should be "off" being lit up purple? in xlights they look fine but if the lights are physically plugged in and testing the gif exported files are turning lights on when they should be off

**Closed** 2020-03-24 18:36 UTC
