### ISSUE TITLE
2021.15 crashing when saving layout image

### ISSUE THREAD

**Issue by bacarudaguy** [smeighan/xLights#2633] opened 2021-05-06 01:32 UTC
Attached video shows saving the layout image, making a change, then re-saving the image and attempting to replace the file. XLights crashes and does NOT produce a crash report (app or system).

OSX 10.15.3

https://user-images.githubusercontent.com/1183946/117229647-634e6780-ade9-11eb-8b3e-eb35982805ec.mp4

**Comment by keithsw1111** [comment] 2021-06-01 10:19
Maybe an OSX issue ... It seems to save ok on windows.

**Comment by dkulp** [comment] 2021-06-01 19:10
Cannot reproduce on OSX either.

**Comment by bacarudaguy** [comment] 2021-06-01 19:15
Just replicated it twice... seems to be an issue overwriting the Untitled.jpg default file name...

**Comment by keithsw1111** [comment] 2021-07-13 09:14
If neither Dan or i can reproduce it then we either need more information or I will need to close this.

**Closed** 2022-06-29 10:42 UTC
