### ISSUE TITLE
"Twinkles" imports as "shimmers" from LOR Sequences (AC Lights)

### ISSUE THREAD

**Issue by Shane8johnson** [smeighan/xLights#2134] opened 2020-07-19 04:45 UTC
For the difference in twinkles and shimmers, consult this link:
http://www.lightorama.com/help/concept_effects.htm

Basically, "The difference between "Twinkle" and "Shimmer" is that twinkle is more random: Two different strings of lights that are both told to shimmer at the same time will quickly turn off and on in sync with each other; if they are instead told to twinkle, they will still quickly turn off and on, but not in sync with each other."

I have an LOR sequence that I am importing to Xlights to control both pixels and AC controllers from Xlights. I have used shimmers and twinkles on the LOR sequence, but when I import the sequence into xlights, it's like it's converting all the twinkles to shimmers instead. 

If more information is needed, please contact me. Thanks!
Xlights Version 2020.28

[Here](https://drive.google.com/file/d/1XaVB0K92w5g36lKNusY96zwUAqDEesSO/view?usp=sharing) is a video of the "Twinkle" in LOR. 
[Here](https://drive.google.com/file/d/1XgE2boFSB2j8eUHQ8BMq5zWv_lpJf_64/view?usp=sharing) is a video of the imported sequence into Xlights (no changes made to either sequence)

**Comment by Shane8johnson** [comment] 2020-07-19 05:00
[Here](https://drive.google.com/file/d/1XaVB0K92w5g36lKNusY96zwUAqDEesSO/view?usp=sharing) is a video of the "Twinkle" in LOR. 
[Here](https://drive.google.com/file/d/1XgE2boFSB2j8eUHQ8BMq5zWv_lpJf_64/view?usp=sharing) is a video of the imported sequence into Xlights (no changes made to either sequence)

**Comment by AzGilrock** [comment] 2020-07-19 16:07
S4 or S5?


Sent from Nine
________________________________

**Comment by Shane8johnson** [comment] 2020-07-19 16:16
> S4 or S5? Sent from Nine
> […](#)
> ________________________________ From: Shane8johnson <notifications@github.com> Sent: Saturday, July 18, 2020 10:00 PM To: smeighan/xLights Cc: Subscribed Subject: Re: [smeighan/xLights] "Twinkles" imports as "shimmers" from LOR Sequences (AC Lights) (#2134) Here is a video of the "Twinkle" in LOR. Here is a video of the imported sequence into Xlights (no changes made to either sequence) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#2134 (comment)](https://github.com/smeighan/xLights/issues/2134#issuecomment-660587789)", "url": "[#2134 (comment)](https://github.com/smeighan/xLights/issues/2134#issuecomment-660587789)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Using LOR S4

**Comment by Cryptkeeper** [comment] 2020-07-23 19:49
For reference:
[Twinkle handling code](https://github.com/smeighan/xLights/blob/master/xLights/ConvertDialog.cpp#L1882)
[Shimmer handling code](https://github.com/smeighan/xLights/blob/master/xLights/ConvertDialog.cpp#L1920)

Since xLights does not utilize the proprietary Light-O-Rama protocol [(more information here)](https://github.com/Cryptkeeper/lightorama-protocol), its code implementation is *emulating* the expected Light-O-Rama behavior. This means the shimmer & twinkle effects imported into xLights are custom approximations of the effects, and not the actual effects built into the Light-O-Rama hardware units.

The similarity between the two effects can be fixed by either adjusting xLight's custom implementation of the effects (which would produce different results for than previously imported sequences, breaking _true_ backwards compatibility) or improving the usage of the Light-O-Rama proprietary protocol; a more difficult undertaking.

**Comment by AzGilrock** [comment] 2020-07-23 19:58
By the time a sequence is rendered the data file that is used to send commands to controllers has no information about which type of effect is contained so xLights will never try to send hardware specific commands to LOR units or any other proprietary hardware.  Those effects preceded me but I'm pretty sure they were not trying to be exact copies of LOR.  A lot of us have dialed in Twinkle effects to get the result we want so I would oppose any change that messes up my work.

**Comment by Cryptkeeper** [comment] 2020-07-23 20:04
I'm aware of the fact xLights is removed from any hardware contextualized data. That's why the route of simply adjusting the twinkle effect is easier.

I'm a bit confused why you oppose the change however. Currently, any user importing a LOR sequence using the LOR conversion dialog is getting a broken result. Why should the LOR conversion dialog not strive to import an accurate xLights representation of the LOR sequence? That seems completely counter intuitive to user expectations, and honestly an annoyance to anyone migrating existing sequences to xLights. 

Changing the twinkle effect logic would be purely within the scope of the LOR conversion dialog, without impacting other elements of xLights, and only serve to further improve the purpose of the LOR conversion dialog.

**Comment by AzGilrock** [comment] 2020-07-23 21:22
I said I'd oppose changes that mess up my work i.e. existing sequences so messing with conversion logic doesn't apply.  Go ahead and try to improve it.

**Comment by AzGilrock** [comment] 2020-07-23 21:24
You said "I'm going to play with modifying the xLights twinkle effect to introduce more randomness...".  That sure sounds like messing with the effect itself and not the import logic.

**Comment by Cryptkeeper** [comment] 2020-07-24 02:57
I directly linked the referenced code section on top of the context of this PR being within the LOR sequence conversion process. The misunderstanding is unfortunate but I don't see much reason to be continuing its discussion.

**Comment by Shane8johnson** [comment] 2020-07-24 02:58
Here's something else I figured out for the devs... When importing from LOR, Regular "Twinkles" import correctly. The ones that are broken are when you've selected a "custom" fade down twinkle. I can attach an example LOR if a dev needs it.

**Comment by Cryptkeeper** [comment] 2020-07-24 05:02
I'm having some trouble replicating the issue. A copy of your LOR sequence would be a big help.

**Comment by Cryptkeeper** [comment] 2020-07-27 22:50
@Shane8johnson bumping this for visibility, see above :)

**Comment by Shane8johnson** [comment] 2020-07-27 23:15
Sorry about the delay. The replies were buried in my emails...
See Attached. The area of interest is 15-22 seconds. That's the clip included in the very first post. 
[Candy_Cane_Lane.zip](https://b2b.lojnet.net/download.php?id=1&token=HJN3y2G8cRu0NhD3dEnUBngBOpNvai2Z)

**Comment by Cryptkeeper** [comment] 2020-07-28 07:01
I'm not able to directly convert your LOR sequence, it seems to be crashing my copy of xLights. It's obviously an issue, but is unrelated to the twinkle issue and something for another day.

On the topic of the twinkle issue, I couldn't recreate it, but I'm rather convinced its a `rand()` entropy issue. Is the result the same each time you import the sequence @Shane8johnson? Does it happen the same in other sequences you import?

**Comment by Shane8johnson** [comment] 2020-07-28 16:22
@Cryptkeeper great question. To be honest, this is my first year transitioning from LOR to XLights, so this was my first sequence I tried to convert. I will try to recreate the issue with a different import and will let you know. 
I thought of something else too, I'm wondering if it could be my modeling that is causing the issue?
The candy cane arches are a single custom model. There are 8 candy canes, but are drew together as one model, with each individual candy cane being 1 node. (This modeling works fine for all other imported effects)
See attached image. I also also send a blank XLights sequence if needed.  

[Model & Wiring View](https://b2b.lojnet.net/download.php?id=4&token=mS7rLMmTecCmAbS5FXgWXv7GuTzfzXIM)
[Channel Information with start nodes.](https://b2b.lojnet.net/download.php?id=3&token=JFXaHhEn6BgtB2iVtjeYCVrgjRufEVZh)

**Comment by Shane8johnson** [comment] 2020-08-10 02:57
@Cryptkeeper Getting back around to this. Version .31 still has the issue.
**Steps to recreate.** 

1. Go into LOR and create/edit a sequence with the following: 
2. Click the "Star" in the toolbar. Click on the twinkle button that has the star, and finally click the fade down button with the star. 
    - This step just created a "Custom Twinkle Fade-down." 
3. Click on the Animation Viewer (View> Animation) and take note of the effect. The 8 lights are flashing randomly (not together) while fading down. 

Now, to import to xlights, map them to any 8 random props. 
(I'm assuming you know how to import a LOR sequence so I will skip those steps)
Render, and take note of the way it imported. All 8 props flash together/simultaneously while fading down, rather than random while fading down. 

I have attached both an example LOR sequence with the Custom Twinkle Fade down, and an Xlights sequence with the LOR imported for reference. 

Thanks. 

[LOR-File-Download](https://b2b.lojnet.net/download.php?id=6&token=9R6qrDmVRv14nXrm7LP7GSvHqqbZs4BX)
[Xlights-File-Download](https://b2b.lojnet.net/download.php?id=5&token=3xEJGlJzKFjMsg5K1bXfShw4kdMWXAT2)

**Comment by Shane8johnson** [comment] 2020-08-15 00:39
@Cryptkeeper I noticed something else in your verbiage that might be helpful with this issue. The problem is happening on *importing* LOR Sequences. (Not converting) I know there is a way to "convert" a LOR sequence to XLights, but the way I'm doing it is by clicking Import>Import Effects>sequence.lms>then mapping the props>Ok. This method is producing the issue above.

**Closed** 2020-08-20 10:38 UTC

**Comment by keithsw1111** [comment] 2020-08-29 10:10
I am really not sure what I was meant to be looking at in the video. Remember all I have is xLights and your files ... You need to be more specific ... model names (LOR and xlights - if they are different) ... times etc. Unless I can reproduce it i cant fix it.

I opened it ... imported onto several props and they all look like when i imported it onto the spinners.

**Comment by Shane8johnson** [comment] 2020-08-30 01:00
Apologies Keith for the lack of detail. To make the issue easier to see, I have attached two sequences below, and a video as well that is ONLY showing the RGB Strands. They are basic RGB Dumb lights, and each line you see is 3 channels. (R,G,B). The effect used in LOR is a shimmer, and as you can see when it imports the effect into XLights, the strands are just fading down white (instead of shimmering) 

(Again, I want to really thank you for fixing the issue in .33 and It has made my transition to XLights much easier.)

[Xlights Sequence ](https://b2b.lojnet.net/download.php?id=7&token=xUOW0a6mLUpAw8pxEFlBvNVZuCtBX4jV)
[LOR Sequence](https://b2b.lojnet.net/download.php?id=8&token=ZJAbJlyHvHmogTGvAgfW37lmsfXuuDgK)
[Video of standalone issue](https://drive.google.com/file/d/1Seb_gVwG4SAzT1u0TyBbSveY0DHuTRn7/view)

**Comment by keithsw1111** [comment] 2020-08-30 05:34
Ok ... so that is never going to come in easily as the sequencing is at the channel level ... and xLights does not sequence at the channel level ... with one exception ... the channel block. If you create 24 channel channel block model and map it to the same channels and then import onto the channel block using the RGB import lines ... it will work ... and thats the only way it will work.

You can then put the channel block in the unassigned preview so it doesnt clutter your layout.

Having looked at the LOR file this is the only way this will work.
