### ISSUE TITLE
moving an effect down sequence grid does not move correctly

### ISSUE THREAD

**Issue by cp16net** [smeighan/xLights#1054] opened 2017-12-31 08:10 UTC
This is kind of hard to explain in words so i've left a video showing it. here: https://youtu.be/e-idjIM4yGc

To recreate: have a sequence view opened with a model group and the individual models (at least 3) as well in a different order from what is in the model group. (This is probably not ideal) 
double click the model group to open the models inside
drop any effect on the model group and select it and use the down arrow.

expected:
the effect will go down sequentially in the models group models and the continue to the individual models once you are past the group models.

actual:
the effect jumps to the order of the individual models once the effect is moved down past the 1st model in the model group.

possible reason:
Seems like there is a difference between single effect selected to multiple effects selected. Seems like the last row or model the effect is on becomes the primary row or model that is moving when using the down arrow but it seems like it works correctly when using the up arrow.

**Comment by AzGilrock** [comment] 2017-12-31 16:04
Yep that's how its gonna work unless someone else wants to tackle that situation.  The problem is once you start expanding groups then you create situations where the effects exists in multiple places.  Once you made it show up in 2 places the upper one and the lower one were the exact same effect.  Both of them were in the selected state because it is 2 views of the same selected effect.  So moving it down from there created 2 different destinations for the same effect.  There is nothing that keeps track of which copy of the effect was the original selection.  It took a lot of work to get this to work as well as it does.  I've seen situations where the same effect can exist on the grid in 3 places.  That's why in the code you will see me tagging effects so I can track if an effect copy has already been moved.  I really don't know why people need to move effects between models that often anyways.

**Comment by AzGilrock** [comment] 2018-01-06 01:13
I was looking at this more.   So checkout this scenario.   The routine that moves effects down always starts at the bottom row and goes up because if it started at the top row it could be trying to move the effect on top of other effects for multi-effect moves.  So it moves the one just above CoroAngel-1 first.  Then it skips the other copy because it was tagged as already moved.  So after the command the lower effect is the currently selected row.  The code also believes there to be multiple selected effects in this situation even though its really a copy of the same effect showing up in 2 places.  This code is already quite complex I'm not sure there's an easy way to make this any better.  The best thing is to have views were the same model is not showing up in 2 or 3 places.

![image](https://user-images.githubusercontent.com/2024669/34634653-7b58a6e8-f243-11e7-968b-2565938e86ce.png)

**Comment by cp16net** [comment] 2018-01-07 19:04
Hmm yeah i think i was confused on why it started on the bottom when looking through it. But this statement kinda explains why that is the case. 
`The routine that moves effects down always starts at the bottom row and goes up because if it started at the top row it could be trying to move the effect on top of other effects for multi-effect moves.`
I can accept the given work around to avoid the scenario.

**Closed** 2018-01-07 19:31 UTC
