### ISSUE TITLE
2018.2 won't open in linux

### ISSUE THREAD

**Issue by cmyers66748** [smeighan/xLights#1071] opened 2018-01-15 22:44 UTC
when I click on the icon to open, it will start to open, and apparently fail part way through and just close, no crash report, nothing, just close.

running Kubuntu 17.04 and xlights 2018.1 worked perfectly, 2018.2 won't open. No other changes were made between the two.

**Comment by cjd** [comment] 2018-01-17 21:38
The problem is caused by the newly added Vendor Model Dialog.
When it initialises the CachedFileDownloader 'cacheDir' is not setup properly and so a segfault results.
Looking into it currently

**Comment by keithsw1111** [comment] 2018-01-18 07:06
I think I have this fixed ... test please chris ... the downside of my fix is caching only works within a single session at best

**Comment by cjd** [comment] 2018-01-18 08:58
A test fix is in place now to disable the caching so at least it works on linux for now.
New builds are in progress

**Comment by keithsw1111** [comment] 2018-01-18 09:27
It doesn’t totally disable the cache. Just limits the cache lifetime until you exit XLights.

**Comment by cjd** [comment] 2018-01-18 09:31
That should be acceptable for most users then

**Comment by keithsw1111** [comment] 2018-04-06 22:27
I am closing this because I believe it is fixed. Please reopen if it isnt

**Closed by keithsw1111** 2018-04-06 22:27 UTC
Labels: Bug - Minor
