### ISSUE TITLE
Pushing config shows wrong channels when serial port models used

### ISSUE THREAD

**Issue by JohnCreed** [smeighan/xLights#3154] opened 2022-03-06 19:16 UTC
**Describe the bug**
Both the Visualize and Layout shows correct channel counts when using serial port and standard pixel models together; however, upon uploading the config to a HinksPix Pro controller the first pixel model starts at channel 1 instead of the next channel after the serial port models.
Example:  Serial Port models use channels 1 - 46, both the Visualize and Layout tabs show first pixel model starting on channel 47; however, after uploading config to HInksPix Pro the first pixel model shows channel 1 instead of channel 47.  

**To Reproduce**
See video here: [https://youtu.be/rzpR6AIn1GI](https://youtu.be/rzpR6AIn1GI)

**Expected behavior**
I would have expected the first pixel model to start with channel 47 because it seems xLights assigns channels to Serial Port first followed by Pixel models next.

**Screenshots**
<img width="461" alt="Visualize 2022-03-06" src="https://user-images.githubusercontent.com/99777857/156938305-94149e41-b78e-4612-a7c9-14845a3e2f31.png">

<img width="461" alt="Layout Tab 2022-03-06" src="https://user-images.githubusercontent.com/99777857/156938307-5ae2aa0f-dd40-4b36-990d-535b9d7c9dcc.png">

<img width="789" alt="HinksPix PRO - DMX Port 2022-03-06" src="https://user-images.githubusercontent.com/99777857/156938312-96b1e814-b584-4dc8-b003-afdb5361a966.png">

<img width="783" alt="HinksPix PRO - E131 Universes 2022-03-06" src="https://user-images.githubusercontent.com/99777857/156938346-52537da1-758d-46a9-8f52-260caa5621e2.png">

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version 2022.06

**Comment by computergeek1507** [comment] 2022-03-06 19:25
That's not a bug, it is intentional. The HinksPixs internal channel buffer doesn't care about DMX data. The channel numbers in the HinksPix are relative to it's first not DMX universe.

**Comment by JohnCreed** [comment] 2022-03-06 20:23
When I push the config from xLights I end up with all types of issues, wrong Pixels turned on, wrong colors, etc.  While troubleshooting I determined if I remove the models from the Serial Port then everything works and it appears to be because the channel numbers then match up in xLights for the pixels.

**Comment by computergeek1507** [comment] 2022-04-10 20:33
Fixed with 2724fc8980489bcfd61b1f15dbc8c5b41956fe04

**Closed by computergeek1507** 2022-04-10 20:33 UTC
