### ISSUE TITLE
Order Timing tracks

### ISSUE THREAD

**Issue by Poporacer** [smeighan/xLights#2218] opened 2020-09-11 13:59 UTC
**Is your feature request related to a problem? Please describe.**

In the Display Elements editor, you can order the models, but you can't order the timing tracks. There are times that having the timing tracks in a different order would be more efficient.

**Describe the solution you'd like**

I know this could be a bit problematic to do so that the timing tracks will remain at the top but it would be nice to have the ability to order them as well (Split window for Models/groups and timing tracks?)

**Describe alternatives you've considered**

You can manually edit the xsq file but not everyone should be editing that file.

**Additional context**

**Comment by keithsw1111** [comment] 2020-09-11 14:03
Duplicate of #1272

**Closed by keithsw1111** 2020-09-11 14:03 UTC
Labels: Enhancement
