### ISSUE TITLE
Ver 27 Clicking on Firework Effect Crashes xLights

### ISSUE THREAD

**Issue by byakymyk** [smeighan/xLights#2124] opened 2020-07-09 00:28 UTC
[xLights_dbgrpt-24693-20200708T202334.zip](https://github.com/smeighan/xLights/files/4893836/xLights_dbgrpt-24693-20200708T202334.zip)

Starting with V27 on Mac OS 10.15.5 MacBook Pro 16 inch 2019

Everytime I click on Firework effect it crashes

**Comment by dkulp** [comment] 2020-07-09 02:07
The issue is with custom value curves, not the fireworks.  Fixed on master.

**Closed by dkulp** 2020-07-09 02:07 UTC
