### ISSUE TITLE
Missing lights on mega tree (2017.15)

### ISSUE THREAD

**Issue by FlyingPlanes99** [smeighan/xLights#867] opened 2017-06-01 16:24 UTC
I've decided to forget importing all of my LOR sequences and just going to re-sequence everything in xLights. 

I've created all of my models and layouts as expected but as you'll see, the middle strand is dim and when I run sequences on it, those areas always stay dimmed.

I don't think it'll impact performance but just wanted to raise it to your attention.  Thanks

![missinglights](https://cloud.githubusercontent.com/assets/27301656/26689487/c98d0dc6-46c3-11e7-9b88-e4c44512a00d.JPG)

**Comment by FlyingPlanes99** [comment] 2017-06-01 21:04
It wouldn't allow me to attach the files in the message so here they are.


________________________________

**Comment by keithsw1111** [comment] 2017-06-01 21:33
Could it be you have another model on top of the tree probably with some transparency dimming the tree?

**Comment by FlyingPlanes99** [comment] 2017-06-02 00:48
Nope.  As a test I just moved the matrix at the top out of the way and re-ran my test and got the same result:
![pic2](https://cloud.githubusercontent.com/assets/27301656/26706447/92ca003a-470b-11e7-9eb1-9c9cf5f13e23.JPG)

**Comment by dkulp** [comment] 2017-06-02 18:31
What's the "rotation" on the tree and the "degrees" of the tree?  I think if it's a 360 treen and rotation is not something around the 10 to -10 range it could likely cause this due to the order in which the pixels are rendered.   Some of the blacks would be rendered after the reds and thus cause this.

**Comment by AzGilrock** [comment] 2017-06-02 18:42
And I'd undock the window and see if it changes when you make the panel larger.

**Comment by FlyingPlanes99** [comment] 2017-06-02 19:11
I did that and it didn't have any affect.

On Jun 2, 2017, at 2:42 PM, Gil Jones <notifications@github.com<mailto:notifications@github.com>> wrote:


And I'd undock the window and see if it changes when you make the panel larger.

**Comment by AzGilrock** [comment] 2017-06-02 19:18
I'm not seeing any files that ever got attached to the thread.

**Comment by FlyingPlanes99** [comment] 2017-06-02 19:25
I keep trying to attach either zip files or xml and this site is saying "We don't support that file type'.  Do you have some place I could upload them?

**Comment by AzGilrock** [comment] 2017-06-02 19:30
Yes the same folder I created for you last time is still there:
https://www.mediafire.com/folder/d9su1pb18aa7s/Flying

**Comment by FlyingPlanes99** [comment] 2017-06-02 20:08
Just uploaded them - dimlights.rar

**Comment by dkulp** [comment] 2017-06-02 20:18
Yep.  Rotation 90 as I expected.    More or less working correctly.    For the most part, we STRONGLY STRONGLY suggest making the starting point of your tree in the very back.  Most effects in xLights would expect that.

**Comment by AzGilrock** [comment] 2017-06-02 20:22
Got em...guess I'll upload them here.  I'm not at home but a quick look it appears you have tree rotation set to 0.0.  I thought the default was 3.0 to try to offset the rear pixels from the front.
[xlights_keybindings.zip](https://github.com/smeighan/xLights/files/1048862/xlights_keybindings.zip)

**Comment by AzGilrock** [comment] 2017-06-02 20:24
Ah guess I looked at the wrong tree.  I do see the top tree is 90.0.

**Comment by FlyingPlanes99** [comment] 2017-06-02 20:26
But why make the back the first string?  As of now, my first string is at the 9 o'clock position and goes counter-clockwise  I have a number of animations that are only programmed to go on strings 1-12 (so not all 24) and if I start them in the back, they'll be 1/2 blocked.

**Comment by FlyingPlanes99** [comment] 2017-06-02 21:25
It's a 360 tree with 24 strands all pointing outward. If looking at the tree from the street. The 9 o clock is left the 6 is front center and the 3 is right.

On Jun 2, 2017, at 5:20 PM, Daniel Kulp <notifications@github.com<mailto:notifications@github.com>> wrote:


What's the "rotation" on the tree and the "degrees" of the tree? I think if it's a 360 treen and rotation is not something around the 10 to -10 range it could likely cause this due to the order in which the pixels are rendered. Some of the blacks would be rendered after the reds and thus cause this.

**Comment by AzGilrock** [comment] 2017-06-03 04:44
If you scroll pictures they will look like they appear wherever the "seam" is so putting it in the back is best.  That's how I do mine and I also have sequences where I only use the middle 12 strings.  Just create a shadow model that only contains the middle 12 strings and with the channels overlayed to the full tree you can sequence to the shadow model and it will show up in the middle of the full tree.  If you want to leave it at 90.0 might I recommend trying a small delta like 93.0 to give some offset between the front and back strings.  It won't be enough of an angle difference to affect the show.

**Comment by dkulp** [comment] 2017-06-03 12:41
If you insist on not doing the recommended setup (start at 12:00), you are going to have a significantly more difficult time.   Many effects assume the center of the model is right in front.   Things like curtain, pinwheel, fan, spirograph, etc...   Even pictures and text.     If you ever plan to import any sequences from other xLights users (or purchase from Lilia or similar), you definitely want to use the standard setup or everything that is imported will look funky. 

In any case, this is a "working as designed" and "optimized for the standard use case" type issue and will likely not be changed.

**Comment by FlyingPlanes99** [comment] 2017-06-03 23:45
Ok, thanks for following up.  I just find it interesting that on the tree I built, when  I do an import of a SUP file purchased from holidaysequences, it always starts string 1 at 12 but when I try to do a single string, for whatever reason, it thinks strand 1 is at 9

**Comment by AzGilrock** [comment] 2017-06-04 00:28
You can fix all your troubles if you put the rotation back to 0 and then create a shadow model for the SUP imports.  If you had a 24x50 tree as a 360 starting at channel 1 then just create a 12x50 tree as a 180 with a starting channel of 901.  That will offset the shadow model by 6 strings which lets your SUP file import onto the middle 12 strings of the 24 string tree.

**Comment by dkulp** [comment] 2017-06-04 17:06
A "Front" sub-buffer would also work fairly well.

The SUP import is the same way.   It assumes you are placing the effects on the "center" of the model.  If you want the "center" of your tree facing the user, the start has to bbe at the 12:00 position.  

Anyway, I'm closing this as it's not something we're going to change.   Things are optimized for the 12:00 starting position.

**Closed by dkulp** 2017-06-04 17:06 UTC
