### ISSUE TITLE
WLED matrtix - misplaced pixels

### ISSUE THREAD

**Issue by mase76** [smeighan/xLights#2832] opened 2021-10-02 15:33 UTC
Hi!
I have 4 matrices of 32x8 aligned to 32x32 controlled with WLED via DDP. In the past I used a custom model in xLights and mapped the LEDs to my needs. That ran just fine. Now WLED has the option to configure the alignment of the single matrices in the firmware. I did so, and the built in 2D effects in WLED look good. Now I tried a matrix model in xLights with 1 String, 1024 LEDs, and 32 Strands. But it does not run optimal. Some pixels are misplaced. I attached a picture of the 32x32 skull from xLights, but I have also have this issue with text or other effects
![135717168-d7b59a11-c48f-45fc-998a-58d3bbe8a73c](https://user-images.githubusercontent.com/2173853/135723061-4657cd69-e50e-405f-98f9-5c046543d161.jpg)
.

**Comment by keithsw1111** [comment] 2021-10-03 11:55
There is not enough information here for us to do anything. We would need a copy of your logs packaged with tools packaged logs and screen shots of your WLED configuration. This is most likely just a configuration error. You may want to try the zoom room in the first instance to validate you have actually set it up correctly.

**Comment by mase76** [comment] 2021-10-03 13:18
Every single matrix of 32x8 is layed out vertically. So every single matrix has 32 strands. WLED is the sound-reactive fork, that has the matrix options build in: https://github.com/atuline/WLED
I am not sure, it this is an issue with WLED or xLights. I am also not sure, what logs you need for this issue, but here is a screenshot of my LED config in WLED
![Bildschirmfoto_2021-10-03_15-11-15](https://user-images.githubusercontent.com/2173853/135755358-53570eb5-a96a-41ba-a8fd-e98dd488e9f6.png)
:

**Comment by mase76** [comment] 2021-10-03 13:26
I also tried this custom mapping in the original WLED (renamed json to txt for upload). It has the same effect.
[ledmap.txt](https://github.com/smeighan/xLights/files/7273396/ledmap.txt)

**Comment by keithsw1111** [comment] 2021-10-03 22:38
I really need your packaged logs to do anything at all with this.

**Comment by AzGilrock** [comment] 2021-10-07 21:09
Under the Tools menu -> Package Log Files

**Comment by mase76** [comment] 2021-10-09 20:50
Here are my logs.
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/7316349/xLightsProblem.zip)

**Comment by keithsw1111** [comment] 2021-10-10 03:59
I really think this is a WLED configuration issue. Without knowing what those WLED parameters mean it would be us just guessing. The thing that looks suspicious to me is the vertical orientation but that should only turn the image on its side and I dont think that is what you are describing ... without the images in the sequence I cant tell exactly what is out of place so anything else would be just guessing.

Looking at your LED map the layout is a mess and wont map to anything the xlights matrix model can produce. xLights assumes strings run the whole length of the matrix but you seem to have 4 stacked vertical matrices. While you can produce that in xLights, put them in a group and use vertical stack its a bit messy. For this most would just build a custom model and move on.

Either way this is not a bug.

Attached is a custom model that might work
[weirdmatrix.zip](https://github.com/smeighan/xLights/files/7316818/weirdmatrix.zip)
.

**Comment by netmindz** [comment] 2022-03-13 08:36
Try running just a simple chase with single pixel at a time to check the order they light up in. Easier to see error

**Comment by dosipod** [comment] 2022-07-19 09:17
Might be late but xlights and Jinx works correctly if in wled matrix setup **you do not select** serpentine ( yes the matrix will be a mess in wled but will work fine from external control )

**Comment by keithsw1111** [comment] 2022-08-28 09:55
Closing to no relevant updates.

**Closed by keithsw1111** 2022-08-28 09:55 UTC
