### ISSUE TITLE
Cash when moving effect to beginning of timeline

### ISSUE THREAD

**Issue by uzelessknowledge** [smeighan/xLights#615] opened 2016-07-08 01:24 UTC
I have been able to create a crash when moving an effect to the beginning of the timeline. I saw this in .33 and then moved to .39 and it continued.
[Crash.zip](https://github.com/smeighan/xLights/files/353339/Crash.zip)
[xLights_dbgrpt-12054-20160707T201930.zip](https://github.com/smeighan/xLights/files/353341/xLights_dbgrpt-12054-20160707T201930.zip)

**Comment by AzGilrock** [comment] 2016-07-08 03:16
Sorry I can't reproduce that.

**Comment by keithsw1111** [comment] 2016-07-08 03:33
My guess is this is a cross thread issue ... so the specifics of the sequence would matter. A video of it happening would help us focus on exactly how this happens.

Keith

________________________________

**Comment by AzGilrock** [comment] 2016-07-08 04:06
The Crash.zip attachment had a video.

**Comment by keithsw1111** [comment] 2016-07-08 04:59
Looking at where it crashed we seem to be rendering the modelPreview on a timer thread but there is no mutex protection on the model list. I am not sure why we do this. I understand in the past we used to play the output on the preview in which case it makes sense ... but now we dont ... is this render call still necessary?

**Comment by uzelessknowledge** [comment] 2016-07-08 11:07
Keith/Gil, let me know if there is anything more I can provide you.

**Comment by AzGilrock** [comment] 2016-07-08 13:52
Keith not sure what you meant by "but now we don't".  That ModelPreview render loop is how we play the frames on all the additional custom previews for the multiple preview function.

Uzeless do you have any additional preview layouts defined?

**Comment by AzGilrock** [comment] 2016-07-08 14:00
I'm not able to dig into it at the moment but I would have thought the timer was designed such that it couldn't get into the "TimerRgbSeq" call more than once.

**Comment by uzelessknowledge** [comment] 2016-07-09 01:45
Yes, I do have other views, but none with that model in it. I have tried tonight to recreate and was not able to. The only difference is that I was not connected to a controller (F16v2R). I will try again while connected and the output enabled.

**Comment by AzGilrock** [comment] 2016-08-03 17:52
We've made a lot of changes that may have improved or affected this.  I'd say you can probably close this one and then open a new one if it happens again.

**Closed** 2016-08-04 15:39 UTC
Labels: Bug - Minor
