### ISSUE TITLE
Issue: Looping sequence "blinks" black when cycling

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#842] opened 2017-04-03 18:27 UTC
See below for current record on this issue being discussed:

1) JHolmes experiences a blank frame when looping 30-second sequence on FPP with Raspberry Pi and SanDevice 6804. Sequence was created with XLights 2017.7 (64 bit) on Macbook Pro. 

2) GadgetSmith reports, in his testing, that any new sequences created with the 2017.x version of xLights has this blinking issue.  All sequences created with the 2016.x versions are fine. 

3) Kel Christmas (Keith) reports he has checked xLights 2017.7 and there is absolutely nothing wrong with the FSEQ is generated. If your effects occupy the whole sequence then there will not be a final black frame. However, there is a bug in xSchedule which would cause it to consistently output a black frame between songs. I have checked in a fix for this. It will be in 2017.8.

If there is any other tests I can do personally to assist, let me know.

**Comment by AzGilrock** [comment] 2017-04-03 18:50
If Keith says the FSEQ looks fine then I can only think of one possibility.  The number of frames in the FSEQ file does not exactly match the number of milliseconds in the audio file so the data runs out one frame early.

**Comment by jholmes09** [comment] 2017-04-03 19:02
Excellent point. In this case there is no audio file and I've deleted the FSEQ to allow a complete re-render but no avail.

**Comment by keithsw1111** [comment] 2017-04-03 19:38
Someone needs to share a sequence with us which has this problem so we can reproduce it. Ideally one that works ok in .51 but generates a black frame in .7 ... then we can compare them.

**Comment by jholmes09** [comment] 2017-04-03 19:53
I will need a little time to get exactly what you asked for. However, for now, here is one of the sequences that has been problematic in .7. 

[Blanking_Packaged_Sequence.zip](https://github.com/smeighan/xLights/files/891206/Blanking_Packaged_Sequence.zip)

**Comment by AzGilrock** [comment] 2017-04-03 23:53
There is no black frame in the end of the data when I render that sequence using 2017.7.  To verify I added an Off effect on the last frame and compared the files side by side.  The one with the Off effect had a chunk of zeroes on the end of the file.

**Comment by AzGilrock** [comment] 2017-04-03 23:55
I also just used 2016.56 and got a binary match with the 2017.7 file.  I don't see any new bug in xLights.

**Comment by keithsw1111** [comment] 2017-04-03 23:58
As I suspected. So with v8 xschedule fix you shouldn't get a blanking there which only leaves fpp which may itself blank at the end of the sequence which I thought they had a setting to control.

**Comment by jholmes09** [comment] 2017-04-04 01:18
I will continue the discussion on the FPP forum and report back. Thank you!

**Comment by gadgetsmith** [comment] 2017-04-04 17:16
I just downloaded the birthday sequence above, loaded it onto 2017.8 , and the resulting fseq blinks when run from my FPP.  Uninstalled 2017.8, installed 2016.56 and resulting fseq does not blink.  Using Beyond Compare 4, the files are not the same at the end.  At line 0025529A is where the files start to look completely different.  This is a link to the two fseq files created from the two different xlights versions.
https://1drv.ms/u/s!AgkqIQkY6VrCqGNm7s1svT2zvTnw

**Comment by AzGilrock** [comment] 2017-04-04 17:24
gadget what OS version of xLights are you using?

**Comment by gadgetsmith** [comment] 2017-04-04 17:25
I realize that we now have two threads going, so if there is a preferred one, just let me know.

@Gil, Windows.

**Comment by AzGilrock** [comment] 2017-04-04 17:27
I think it's 4 threads cause you know this 50ms blink is so important...lol.

**Comment by jholmes09** [comment] 2017-04-04 18:22
I have stopped discussing this on the Facebook thread and while there is continued discussion on FalconChristmas.com about the FPP side of things, this is the only XLights related one I am aware of.

Considering the developers often say that longer length files can add rendering time and general struggles in the XLights software, the ability to loop perfectly seamless so the audience doesn't notice is fantastic. I was always impressed by that! 

Let me know how else I can help.

**Comment by AzGilrock** [comment] 2017-04-04 18:35
I go black between all my songs so I've never needed a seamless loop.  I'd love to fix it but unless I can get it to occur on my setup I can't fix it.

**Comment by jholmes09** [comment] 2017-04-04 18:49
I appreciate your willingness to help! I had surgery this morning so I'm too out of commission but I completely intend to take everyone's advice and test where I can. When I have new information to share, I will! Thank you :)

**Comment by cpinkham** [comment] 2017-04-04 21:39
The 2017 file has a blank frame at the end while the 2016 file has data
in the last frame.  Here are a couple dumps from the 'seqdump' utility
included with fpp (but not compiled by default).

fpp@rpi7 ~/fpp/src/util $ ./seqdump ~/media/sequences/Birthday\
2016.56.fseq | tail
       000000: 00 3e ff 00 52 ff 00 69 ff 00 90 ff 00 a8 ff
00    .>..R..i........
00:29.36 Frame #1196, Ch: 1-16, fnb: 2: (16 bytes)
       000000: 00 2f ff 00 43 ff 00 5a ff 00 80 ff 00 97 ff
00    ./..C..Z........
00:29.37 Frame #1197, Ch: 1-16, fnb: 2: (16 bytes)
       000000: 00 23 ff 00 39 ff 00 4d ff 00 76 ff 00 8a ff
00    .#..9..M..v.....
00:29.38 Frame #1198, Ch: 1-16, fnb: 2: (16 bytes)
       000000: 00 15 ff 00 2b ff 00 3f ff 00 67 ff 00 7b ff
00    ....+..?..g..{..
00:29.39 Frame #1199, Ch: 1-16, fnb: 2: (16 bytes)
       000000: 00 0c ff 00 1f ff 00 35 ff 00 5a ff 00 71 ff
00    .......5..Z..q..
CloseSequenceFile() /home/fpp/media/sequences/Birthday 2016.56.fseq
fpp@rpi7 ~/fpp/src/util $ ./seqdump ~/media/sequences/Birthday\
2017.8.fseq | tail
       000000: 00 3d ff 00 51 ff 00 68 ff 00 8f ff 00 a7 ff
00    .=..Q..h........
00:29.36 Frame #1196, Ch: 1-16, fnb: 2: (16 bytes)
       000000: 00 2e ff 00 42 ff 00 59 ff 00 80 ff 00 96 ff
00    ....B..Y........
00:29.37 Frame #1197, Ch: 1-16, fnb: 2: (16 bytes)
       000000: 00 22 ff 00 38 ff 00 4c ff 00 75 ff 00 89 ff
00    ."..8..L..u.....
00:29.38 Frame #1198, Ch: 1-16, fnb: 2: (16 bytes)
       000000: 00 14 ff 00 2a ff 00 3e ff 00 66 ff 00 7b ff
00    ....*..>..f..{..
00:29.39 Frame #1199, Ch: 1-16: (16 bytes)
       000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00    ................
CloseSequenceFile() /home/fpp/media/sequences/Birthday 2017.8.fseq
fpp@rpi7 ~/fpp/src/util $ 

On Tue, 2017-04-04 at 10:16 -0700, charlie wrote:
> > > > > > > I just downloaded the birthday sequence above, loaded it onto 2017.8
, and the resulting fseq blinks when run from my FPP.  Uninstalled
2017.8, installed 2016.56 and resulting fseq does not blink.  Using
Beyond Compare 4, the files are not the same at the end.  At line
0025529A is where the files start to look completely different.  This
is a link to the two fseq files created from the two different
xlights versions.
> 
> https://1drv.ms/u/s!AgkqIQkY6VrCqGNm7s1svT2zvTnw
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/smeighan/
xLights","title":"smeighan/xLights","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/smeighan/xLights"}},"updates":{"sni
ppets":[{"icon":"PERSON","message":"@gadgetsmith in #842: I just
downloaded the birthday sequence above, loaded it onto 2017.8 , and
the resulting fseq blinks when run from my FPP.  Uninstalled 2017.8,
installed 2016.56 and resulting fseq does not blink.  Using Beyond
Compare 4, the files are not the same at the end.  At line 0025529A
is where the files start to look completely different.  This is a
link to the two fseq files created from the two different xlights
versions.\r\nhttps://1drv.ms/u/s!AgkqIQkY6VrCqGNm7s1svT2zvTnw\r\n"}],
"action":{"name":"View
Issue","url":"https://github.com/smeighan/xLights/issues/842#issuecom
ment-291569565"}}}

**Comment by AzGilrock** [comment] 2017-04-04 21:50
Problem is I can't figure out how to reproduce the FSEQ file that has zeroes at the end no matter how many files someone else shows it's not gonna help unless they can debug it on their own setup.  Must be some other xLights setting causing it.  I'm also not sure why the timestamps appear to be advancing in 10ms intervals and ending on 00:29.39.  If it's a 30sec sequence with 1200 frames that sounds like its setup as a 40fps (25ms) sequence.

**Comment by cpinkham** [comment] 2017-04-04 22:21
Step time does indicate that it is a 40 fps 25ms sequence.  The
00:29.39 is a combination of seconds and frame numbers, so it does have
the correct number of frames in both files.  Frames and seconds start
at 0 in the seqdump output, so that is the 30th second (0-29) and the
40th frame (0-39) in that second.

fpp@rpi7 ~/fpp/src/util $ ./seqdump ~/media/sequences/Birthday\
2016.56.fseq | head -15
OpenSequenceFile(/home/fpp/media/sequences/Birthday 2016.56.fseq)
Sequence File Information
seqFilename           : /home/fpp/media/sequences/Birthday 2016.56.fseq
seqVersion            : 1.0
seqFormatID           : PSEQ
seqChanDataOffset     : 28
seqFixedHeaderSize    : 28
seqStepSize           : 2040
seqNumPeriods         : 1200
seqStepTime           : 25ms

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/smeighan/
xLights","title":"smeighan/xLights","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/smeighan/xLights"}},"updates":{"sni
ppets":[{"icon":"PERSON","message":"@AzGilrock in #842: Problem is I
can't figure out how to reproduce the FSEQ file that has zeroes at
the end no matter how many files someone else shows it's not gonna
help unless they can debug it on their own setup.  Must be some other
xLights setting causing it.  I'm also not sure why the timestamps
appear to be advancing in 10ms intervals and ending on 00:29.39.  If
it's a 30sec sequence with 1200 frames that sounds like its setup as
a 40fps (25ms) sequence."}],"action":{"name":"View Issue","url":"http
s://github.com/smeighan/xLights/issues/842#issuecomment-291642501"}}}

**Comment by jholmes09** [comment] 2017-04-04 22:23
I'll happily check my settings. Which setting should I be looking for that might cause this?

**Comment by AzGilrock** [comment] 2017-04-05 00:22
So if you expand the model to the node level does it look like this?

![blink1](https://cloud.githubusercontent.com/assets/2024669/24684477/2ee2f0f0-195b-11e7-8feb-0edbed246898.png)

**Comment by AzGilrock** [comment] 2017-04-05 00:27
Ok I see it now.  I pulled the effect in a little closer and its stopping rendering 2 frames early.  Not sure what change someone did that caused that but maybe now that it's obviously a problem it will jog someone's memory.
![blink2](https://cloud.githubusercontent.com/assets/2024669/24684579/e7c75340-195b-11e7-9e1c-84c0dcad229e.png)

**Comment by jholmes09** [comment] 2017-04-05 00:30
Hello,

I just checked and no, it is cutting short.

<img width="1440" alt="screen shot 2017-04-04 at 5 28 57 pm" src="https://cloud.githubusercontent.com/assets/18503894/24684651/5dba322a-195c-11e7-95d8-22abdab7cc3f.png">

**Comment by AzGilrock** [comment] 2017-04-05 00:31
Sorry I beat you to it.

**Comment by jholmes09** [comment] 2017-04-05 00:32
That is why you are the master ;).
I'm just glad I'm not completely crazy. I hate to waste your time on issues that don't exist.

**Comment by AzGilrock** [comment] 2017-04-05 00:34
Yeah the problem was if you drag it a little further past the end the problem goes away.  Most people who drag it past the end are zoomed out and get a much bigger section off the end.

**Comment by jholmes09** [comment] 2017-04-05 00:35
I thought about doing that but since I want as seamless a loop as possible, I figured dragging it past the end-point would cause a "jolt" (so to speak) when the loop reset. What is your experience with that?

**Comment by AzGilrock** [comment] 2017-04-05 00:37
It depends on whether the effect loops seamless or not.  The FSEQ will be cutoff at the end of the proper duration not where the effect ends.  In either case it's an issue that should be fixed so extending effects is a temporary workaround.

**Comment by dkulp** [comment] 2017-04-05 00:38
Grr..  
`for (int frame = startFrame; frame < endFrame; ++frame) {`

that should be <= as endFrame is set to `endFrame = SeqData.NumFrames() - 1;`

**Comment by dkulp** [comment] 2017-04-05 00:48
There is an opposite problem in the node display where the last frame is displayed double wide which explains why it LOOKS like it extends out an extra frame.

**Comment by dkulp** [comment] 2017-04-05 00:51
Gil just pushed a fix, can you verify?

**Closed** 2017-04-05 00:50 UTC

**Comment by AzGilrock** [comment] 2017-04-05 00:58
Yep looks good now.

![blink3](https://cloud.githubusercontent.com/assets/2024669/24685111/41bbba7c-1960-11e7-92fc-8532fee2dd4a.png)

**Comment by jholmes09** [comment] 2017-04-05 01:45
Thank you gentlemen! You rock!

**Comment by gadgetsmith** [comment] 2017-04-06 13:30
Ah.  I was not saving or rendering after I zoomed in.  Once I did that, I can see what you guys see now.

Thanks to Dan, Gil and Keith!

I'm guessing these changes get rolled into the next release 2017.9 ?

Cheers!

**Comment by gadgetsmith** [comment] 2017-04-10 12:28
Tried out 2017.9 this morning and things work great.  Thanks again!
