### ISSUE TITLE
Setting Default Test show bug

### ISSUE THREAD

**Issue by caeklund** [smeighan/xLights#774] opened 2016-12-09 15:32 UTC
We have been running our test show off a folder in the DropBox. That allows two of us to both access and to allows me to use it on two different computers.

In a effort to get a Show folder that was up to date, I drug the show folder to my desktop and cleaned it up so it was current and deleted unneeded files. I deleted the folder off the Dropbox and waited for it to synch like that to all users. Then I drug it back into the dropbox.

Another Mac, my Mac desktop, and Kurt’s Window’s 10 laptop all lran fine from the dropbox.

When I tried to change my show directory back to the dropbox folder (from my desktop folder), it bombed. I tried restarting, downloading the program, and moving the show folder to a different spot in the dropbox. Same results—a bomb when I tried to change the show folder.

On a whim, I changed the name of the show folder on my desktop and lo and behold, I could change the show folder back to dropbox version and it works fine.

This was on version 2016.53 and the latest version of the Mac OS (Sierra 10.12.1)

I've attached the debug file.

Chuck
[xLights_dbgrpt-557-20161208T140321.zip](https://github.com/smeighan/xLights/files/642527/xLights_dbgrpt-557-20161208T140321.zip)

**Comment by keithsw1111** [comment] 2017-08-13 20:57
This crash looks like it was in the old scheduler code which has now been removed and the functionality is in xSchedule. Unless there is something here that is reproducable I am closing this issue.

**Closed by keithsw1111** 2017-08-13 20:57 UTC
Labels: Bug - Trivial
