### ISSUE TITLE
FSEQ's error

### ISSUE THREAD

**Issue by abgarza911** [smeighan/xLights#1006] opened 2017-12-03 04:14 UTC
Im getting this erron on the check schedule ...
ERR: Play list 1 has sequence 1 with 3120 channels when it should be 2610.

ERR: Play list 2 has sequence 2 with 2612 channels when it should be 2610.

ERR: Play list 3 has sequence 3 with 2612 channels when it should be 2610.

Can some one help me with this issue

**Comment by computergeek1507** [comment] 2017-12-03 04:36
Join the Zoom Video Meeting and Some of use can look at your setup.

https://zoom.us/j/175801909

**Comment by keithsw1111** [comment] 2017-12-03 07:42
The bottom 2 you can ignore. The top one needs to be rerendered and saved

**Comment by abgarza911** [comment] 2017-12-03 14:49
I already join zoom, how do i get help on that error that appears on the check schedule window...thanks?

Sent from Yahoo Mail on Android 
 
  On Sun, Dec 3, 2017 at 1:42, Keith Westley<notifications@github.com> wrote:   
The bottom 2 you can ignore. The top one needs to be rerendered and saved

**Comment by keithsw1111** [comment] 2017-12-03 18:28
Github is not a real time conversation mechanism. Zoom generally has someone on the call most evenings but especially Wednesday nights US time and Friday nights Australian time. Speak up and ask those in the room ... even if there seem to be people there not saying anything.

I am closing this issue because your original request is a) not a bug and b) answered. The xLights Official Facebook group or the Nutcracker Forum are better places for these sorts of questions.

**Closed by keithsw1111** 2017-12-03 18:28 UTC
