### ISSUE TITLE
bulk render issue with twinkle effect

### ISSUE THREAD

**Issue by kkatee** [smeighan/xLights#2602] opened 2021-04-17 07:21 UTC
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
twinkle effects are starting with the whole effect the first selected pallete colour after a render all, or render on save. once you interact with the effect it goes back to normal until you hit render all again.

https://youtu.be/bB-utMQlk0U?t=70

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
1. insert twinkle effect.
2. render all.
3. selected models will flash the first colour in the pallete

**Expected behavior**
normal apperance of the effect

**Screenshots**
https://youtu.be/bB-utMQlk0U?t=70

**Versions (please complete the following information):**
 - OS: Windows 10
 - xLights version. 2021.12

**Additional context**

**Attachments**
[Time Warp.zip](https://github.com/smeighan/xLights/files/6328772/Time.Warp.zip)

**Comment by kkatee** [comment] 2021-06-27 04:56
This only affects the new render method.

Still occurs on 2021.19

**Comment by keithsw1111** [comment] 2021-06-28 07:34
I cant reproduce the problem from your descrption.

Can you maybe produce a sequence with just the one effect that is demonstrating the issue. I started a new sequence. Dropped a new render style twinkle effect on the whole house and then tested it via both clicking on it and clicking render all and they rendered the same.

If you can only see your problem in the sequence then can you tell me the model, layer and time of a twinkle effect that shows the problem.

**Comment by kkatee** [comment] 2021-06-28 12:29
Thanks for taking a look Keith.

on the attached sequence it happens on the two twinkle effects on the whole house group that start at 1:12.5, the ones at 2:02 2:29 and 2:57

I have also been unable to reproduce the fault with a new sequence.

**Comment by kkatee** [comment] 2021-08-06 19:21
[Test.zip](https://github.com/smeighan/xLights/files/6947575/Test.zip)

Some other people are also experiencing this issue, and based on their experiences I was able to reproduce the error on a new sequence. It only happens with  multiple twinkle effects on the same group on the timeline, it doesn't happen to the first one.

**Comment by AzGilrock** [comment] 2021-08-06 19:23
I believe its real and I think I've heard enough to look into it.  I'm not at home so I can't do anything but comment at the moment.

**Comment by kkatee** [comment] 2021-08-06 19:43
Thanks Gil, I was thinking it was just something with my sequence when I couldn't repro

I should also add I was able to work around it by using a diffferent render style than default

**Comment by AzGilrock** [comment] 2021-08-07 22:53
This should be fixed for next release

**Closed by AzGilrock** 2021-08-07 22:53 UTC
