### ISSUE TITLE
XLights 2020.3 Linux Crash Issues

### ISSUE THREAD

**Issue by extremeskillz** [smeighan/xLights#1922] opened 2020-01-20 23:59 UTC
**Describe the bug**
Upon startup of 2020.3 I get crash when going to my layout tab. I want to update the background photo. As soon as I attempt to update, I get a crash. I attached the log files to this post. See attached video and logs in zip.
[Xlights error logs and video.zip](https://github.com/smeighan/xLights/files/4088539/Xlights.error.logs.and.video.zip)

**Comment by AzGilrock** [comment] 2020-01-21 14:14
Please delete parts of the template you aren't filling out.  You only typed into the Describe the bug section but left the entire template which is real confusing to read.

**Comment by extremeskillz** [comment] 2020-01-21 23:43
Updated and sorry.

**Comment by computergeek1507** [comment] 2020-01-21 23:45
What Linux distribution and are you using the appimage?

**Comment by extremeskillz** [comment] 2020-01-21 23:47
Ubuntu 18.04lts

**Comment by myhrmans** [comment] 2020-01-23 10:47
Same issue here. Can't add new models. 

All version are broken now, tried versions that worked before aswell.
Running 18.04 Ubuntu.

Attached logs:
[xLightsProblem.zip](https://github.com/smeighan/xLights/files/4102622/xLightsProblem.zip)

System information:
[sysinfo.txt](https://github.com/smeighan/xLights/files/4102640/sysinfo.txt)

**Comment by PeteMatthews** [comment] 2020-01-24 10:04
I had a play with this and can reproduce everything. Rebuilding with 959c259a backed out (the move from wxWidgets 3.1.2 to 3.1.3) fixes things, though there's no obvious reason why the minor point release would turn everything into a crashy mess. I'll poke a bit further and see if I can work out what's happening.

**Comment by AzGilrock** [comment] 2020-01-24 13:24
In the past I've used git bisect on the wxWidgets codebase and tracked down a bug in their code.  Well it was a bug on Windows only.

**Comment by dkulp** [comment] 2020-01-24 13:36
I also would suggest trying to flip to the GTK3 build of wxWidgets instead of GTK2.   Almost all the testing/fixes/changes in wxWidgets for GTK are targeting GTK3 with very little testing/updating of the 2 codebase.

**Comment by PeteMatthews** [comment] 2020-01-24 13:48
> I also would suggest trying to flip to the GTK3 build of wxWidgets instead of GTK2. Almost all the testing/fixes/changes in wxWidgets for GTK are targeting GTK3 with very little testing/updating of the 2 codebase.

Thanks for the pointer - Rebuilding to test now

**Comment by PeteMatthews** [comment] 2020-01-24 16:38
Confirmed, shifting to GTK3 sorts things out. Will formalise and check AppImage builds work right.

**Comment by PeteMatthews** [comment] 2020-01-24 17:44
PR created to resolve this - https://github.com/cjd/xlights-build-docker/pull/1

**Comment by leighfiddes** [comment] 2020-01-25 06:22
I created #1909 and I hope this fix is successful.

**Comment by PeteMatthews** [comment] 2020-01-25 09:48
Just spun up a clean Ubuntu 19.10 VM and successfully tested a new 2020.03 AppImage build. If anyone else is interested in giving it a go, there's a copy in Dropbox at https://www.dropbox.com/s/2sg32f9ssm8ysvf/xLights-2020.3-GTK3-x86_64.AppImage?dl=0

If you give it a go, please let me know how you get on.

**Comment by computergeek1507** [comment] 2020-01-25 16:21
I know DJ builds the Appimages on 16.04 because if you build it on the newest it doesn't work on older versions of the distribution.

**Comment by leighfiddes** [comment] 2020-01-25 22:13
I've run Pete's GTK3 build on 18.04 this morning and have identified two issues so far:
1) Major: Changing the show directory on the Setup page causes a crash. The crash log is attached.
2) Minor: On the Layout tab, when first opened, the "Model/Group" column is very narrow (this was also the case in 2019.xx). The Background Image area is visible. Changing the width of the Model/Group column automatically selects the first line in the table and the Background Image area disappears. In 2019.xx changing this first column width did not select the first line and so the Background Area was still visible.
[xLights_dbgrpt-16066-20200126T090150.zip](https://github.com/smeighan/xLights/files/4112961/xLights_dbgrpt-16066-20200126T090150.zip)

**Comment by PeteMatthews** [comment] 2020-01-26 22:54
Thanks for trying it out. I note that the PR has been merged on the build repo now (which is great - thanks folks), so all future xLights AppImage releases should (hopefully) be fixed. 

I can replicate the crash inside an AppImage build, but not one I build/run natively. I'll see if I can have a poke around  in the next few days. It would probably be worth raising these as separate issues, as this one can/probably should be closed once the layout tab issues are verified as fixed.

**Comment by cjd** [comment] 2020-01-30 04:49
Can someone give https://www.adebenham.com/wp-content/uploads/xlights/xLights-2020.3-x86_64.AppImage a test - that is using GTK3 and wxwidgets 3.1.3
The base image is debian stretch to maximise compatibility with older distros

**Comment by leighfiddes** [comment] 2020-01-30 20:14
A quick test still produces a crash sometimes (50%) when the show directory is changed. I'll try some more detailed tests on the weekend and get some logs.

**Comment by extremeskillz** [comment] 2020-02-01 20:18
I downloaded and ran the 2020.3 appimage on Ubuntu 18.04lts and its stable again. Not crashes on background image update.

**Comment by extremeskillz** [comment] 2020-02-01 20:26
Spoke too soon. As I was editing the layout it did crash but I was able to recover by restarting the appimage and continuing on. Not sure why but I attached the logs.
[xLights_dbgrpt-12550-20200201T152448.zip](https://github.com/smeighan/xLights/files/4143209/xLights_dbgrpt-12550-20200201T152448.zip)

**Comment by leighfiddes** [comment] 2020-02-03 10:23
I've tried this version and haven't had any crashes in layout, so I think this issue is addressed.

**Comment by extremeskillz** [comment] 2020-02-03 14:55
Try deleting a prop or creating a new one and see if it crashes. It did on me. 

But the original issue in this ticket was resolved.

**Comment by cjd** [comment] 2020-02-03 22:26
I'm fixing up some gtk3 issues currently - but aim to release a 2020.4 tomorrow for testing

**Comment by cjd** [comment] 2020-02-03 22:42
I've just uploaded 2020.4 to https://www.adebenham.com/wp-content/uploads/xlights/xLights-2020.4-x86_64.AppImage with some changes to how the appimage is built
Can you give it a try and log any issues in a bug I've created for tracking this
https://github.com/smeighan/xLights/issues/1933
Since the original issue for this bug is resolved I'll close this off for now - any new issues should go in the new bug

**Closed by cjd** 2020-02-03 22:42 UTC
