### ISSUE TITLE
2022.02.1 some ports get assigned overlapping start channels both with visualizer and with manual start channels via "use start channel"

### ISSUE THREAD

**Issue by martyjlewis** [smeighan/xLights#3084] opened 2022-01-17 07:50 UTC
Verified the problem goes away with 2021.35.2 (latest available from the archive before 2022.02).

First noticed the problem using visualizer.  Two ports on two different Kulp 16 controllers are being assigned overlapping port numbers with another port.  Confirmed auto size was selected for each affected controller, and verified everything is correct in visualizer.

As a debug step, I turned off auto size and auto update on each controller and set channel size manually.  Next, I verified correct channel configurations in FPP.  Finally, I changed each model to "use start channel" and manually entered each start channel as appropriate, pressing tab and then clicking save after each entry.  I still saw the same overlapping start channels in the top "Models" pane, while the bottom details pane had the correct start channel.  This persists even if the program is restarted (e.g. the bottom pane still knows what channel it should be, but the top pane has the incorrect start channel).  

The problem propagates to the fseq file, causing the associated pixels to not light up correctly.

Check sequence warns of the affected models starting on the wrong controller and finishing on the correct controller, in spite of everything being correct in visualizer.

e.g. " WARN: Model 'Roofline Lower Flat' starts on controller 'FppRoof' with IP 'XXX' but ends on a controller 'FppPorch' with IP 'XXX'."

Opening the same show directory in 2021.35.2, the problem goes away.  Re-rendering re-uploading the sequence via FPP Connect allowed all lights to light up appropriately with this version.
<img width="740" alt="Screen Shot 2022-01-16 at 8 37 12 PM" src="https://user-images.githubusercontent.com/35250577/149728723-305df9da-3bb6-4e29-988f-8d3b208bf351.png">
<img width="542" alt="Screen Shot 2022-01-16 at 6 30 37 PM" src="https://user-images.githubusercontent.com/35250577/149728730-02578842-b638-4f28-9e0f-75a13c087ec2.png">
[Valentines Animation.zip](https://github.com/smeighan/xLights/files/7885105/Valentines.Animation.zip)

**Comment by AzGilrock** [comment] 2022-01-17 16:50
Pretty sure this is clearly only happening from PolyLine models due to my attempt to add multiple string support.  It was already reported to me but every attempt I tried was working fine so I'll use your report to see if I can duplicate the issue.  Well it doesn't look like you provided a sample layout with the issue.  I know when I tried to create a layout from scratch I couldn't figure out how to cause an error.

**Comment by martyjlewis** [comment] 2022-01-17 23:15
Yes, both affected models are poly lines.  I will export my layout and upload it a bit later.  Thanks for your efforts!

**Comment by martyjlewis** [comment] 2022-01-17 23:24
[Valentines Animation.zip](https://github.com/smeighan/xLights/files/7885080/Valentines.Animation.zip)
See attached packaged simple animation sequence, which contains the affected layout.  The affected models are "Roofline Upper Flat" and "Garage Door".  Both are poly lines.  Thanks again for all you efforts!

**Comment by sslupsky** [comment] 2022-01-18 03:50
@AzGilrock It might be related but I noticed some rendering issues today on some polylines in version 2022.02.1.  I have another computer that is still running 2022.01 and if I render with 2022.01, the polylines render as expected.  I also noticed an "overlapping nodes" warning when you run a check sequence in 2022.02.1.  That warning is not present when using 2022.01.  I have attached an illustration below.

<img width="1774" alt="Screen Shot 2022-01-17 at 8 45 50 PM" src="https://user-images.githubusercontent.com/16888734/149867775-a825f167-2801-40ce-81ae-13af136d0a52.png">

**Comment by AzGilrock** [comment] 2022-01-18 04:00
I've identified why it happening but didn't have a quick fix so I'll need another day or so.  The reason I never saw it when I tested was because it was only a problem for people that define the PolyLine start location backwards (Blue Square instead of Green Square).  For the other devs the issue is the NodesPerString functions that were added to PolyLine.  They were copied from CustomString but for PolyLine it puts the code in a catch 22 where NodesPerString wants to use the channel number assignments to calculate number of nodes but the actual channel assignments were using the NodesPerString call in the case of a Blue Square start because it needed to count the channel numbers down backwards.

**Comment by sslupsky** [comment] 2022-01-18 04:23
> it was only a problem for people that define the PolyLine start location backwards (Blue Square instead of Green Square).  

Indeed, one of the polylines in that sequence is backward.  That brings up another thought, it would be handy if you could swap the beginning and end of a polyline or single line.  Or perhaps flip/mirror the model about an axis.

**Comment by dkulp** [comment] 2022-01-24 21:07
This was fixed in 2022.03

**Closed by dkulp** 2022-01-24 21:07 UTC
