### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DanJacobsen** [smeighan/xLights#1760] opened 2019-10-15 01:01 UTC
NOTE: IF YOU DO NOT ATTACH A SEQUENCE THAT DEMONSTRATES YOUR PROBLEM THEN THERE IS A HIGH PROBABILITY YOUR ISSUE WILL JUST BE CLOSED AND NOT INVESTIGATED.

**Describe the bug**
Crash occurred when rendering.  I had just moved back to my own setup from the XLATW setup.

**To Reproduce**
(and/or link to a short video showing the problem with audio track describing what you are doing)
[xLights_dbgrpt-12472-20191013T191010.zip](https://github.com/smeighan/xLights/files/3726955/xLights_dbgrpt-12472-20191013T191010.zip)

**Expected behavior**
A clear and concise description of what you expected to happen and why.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. Windows 10, Mac 10.14.5, etc...]
 - xLights version [e.g. 2019.37]

**Additional context**

**Attachments**
- If associated with a crash please attach/link to a dropbox containing the crash log that was produced
- If it crashed but no crash log was produced please use Tools Menu/Package Logs and attach/link to a dropbox containing the resulting zip file
- If the error relates to rendering an effect or a crash while sequencing please use Tools Menu/Package Sequence and attach/link to a dropbox containing the resulting zip file

If you would prefer not to post your sequences publically please say so and be ready to PM them to one of the developers when asked.

**Comment by keithsw1111** [comment] 2019-10-15 06:14
This is a crash I am really interested in understanding the cause of but unless you can reproduce it reliably or at least be much much more specific about what you were doing I am stuck.

**Comment by keithsw1111** [comment] 2019-10-15 10:02
This crash started to appear in 2019.55. I have been through every change made in that release and bar one thing I reversed I cant see anything that looks like a direct cause of this crash. That doesnt mean it isnt there just that i cant see it. It is by far our most common crash so lots of people are experiencing it but either no one has a way to reliably reproduce it or no one who has has raised those specifics with us.

**Comment by AzGilrock** [comment] 2019-10-15 13:03
I went to "...".  I clicked on "...".  I scrolled down to "...".  I did not see an error. :)

**Comment by DanJacobsen** [comment] 2019-10-16 01:06
???hmmm ??   This is recent debug report file .....

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DanJacobsen** [comment] 2019-10-16 02:25
Hopefully this will clarify---I had opened up the XLATW  sequence to see how to map from that sequence to mine.   I closed that sequence then opened up one of the files in my normal show folder.   When I rendered my file, the crash occurred.   I hope that helps..

**Comment by AzGilrock** [comment] 2019-10-16 14:24
I was joking because you left the "Steps to reproduce" in there from the template.  Its a template you're supposed to erase the stuff that doesn't apply.....lol.

**Comment by keithsw1111** [comment] 2019-10-17 07:51
so can you reproduce it over and over again by following specific steps.

**Comment by DanJacobsen** [comment] 2019-10-18 00:28
Let me try not sure

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DanJacobsen** [comment] 2019-10-18 03:29
Keith--tried to duplicate but did not crash this time around.   Pretty sure I opened up the same sequence in my setup that I opened when the crash occurred.   Sorry.

**Comment by DanJacobsen** [comment] 2019-10-18 03:29
Keith--tried to duplicate but did not crash this time around.   Pretty sure I opened up the same sequence in my setup that I opened when the crash occurred.   Sorry.

**Comment by keithsw1111** [comment] 2019-10-18 08:53
i am going to close this then as we can see this in the crash logs so holding this open with no way to reproduce it does not help.

**Closed** 2019-10-18 08:53 UTC
