### ISSUE TITLE
Bars effect - Speed bug ?

### ISSUE THREAD

**Issue by bluzervic** [smeighan/xLights#99] opened 2015-03-24 00:18 UTC
Was playing with a 7x10 matrix (my mini micro Dalek trees)

Parameters:

1. Bars effect
2. Direction is down, Highlight and 3D are not selected
3. Layer timing is 1, no Morph, effect 1, no fade in  or out, fit to time and persistent are not selected
4. Color is Red and black

The effect is running 3 to 4 red lights from top to bottom with a black space.
This is working fine.

Here is where I see problems

1. moving the speed bar, I would think would change the effect visually, however this does not happen until you hit the update button. (I think in XL3 you could do this)

2. speeds beyond 7 and to 23 are unrecognizable pattern wise...

3. by the time we get the speed up to 26 the pattern has already shifted from top to bottom  to going from bottom to top. Speed 30 clearly shows the direction has reversed. now from bottom to top.
I still have down direction selected in the Effect settings.

**Comment by stevegiron** [comment] 2015-05-18 20:26
Hello, I'm helping sort the issues and determine which issues are still valid. 
As of May-14 we are version 4.0.31. Is this issue still occurring?

**Comment by dkulp** [comment] 2015-05-18 21:03
I actually believe this is not a bug and is working "correctly".  

1) If you click on the effect first, then start moving the speed slider, it should change immediately.   I think the older versions of v4 had some selection issues (the current version still has a couple straglers we're trying to track down), but usually clicking on the effect will usually fix that.

2/3) Speed 10 is advancing the bar 1 line each "frame"   At the normal 20fps (50ms timing), that would cycle it up your 7 line tall matrix almost 3 times each second.     Speed "20" is double that, so 2 lines each frame.  Speed 30 is triple.   For it looking like "reverse", thats just that it's advanced far enough that that it happens to look that way.  Just like a rotating bike wheel looks like it's going backwords at certain rotation speeds.

**Comment by stevegiron** [comment] 2015-05-18 21:26
Closing as this effect is working correctly. The apparent speed differential is because the model is small.

**Closed by stevegiron** 2015-05-18 21:26 UTC
Labels: Bug - Trivial
