### ISSUE TITLE
Feature Request: Drag effects between layers

### ISSUE THREAD

**Issue by soundman516** [smeighan/xLights#154] opened 2015-04-02 20:18 UTC
Would it be possible to just click a drag an effect up or down to a layer. This way if you are adding an effect and you accidentally drop it on layer 2, but you want it on layer 1, you don't have to delete and re add the effect. Simply click a drag it up to layer 1.

**Comment by LightsOnHudson** [comment] 2015-04-02 21:41
#135 Is very similar/same

**Comment by soundman516** [comment] 2015-04-02 21:55
I looked through to see if anyone else had submitted this, but must have overlooked your post. Sorry!

**Comment by stevegiron** [comment] 2015-05-18 20:59
Closing this request. Duplicate of 135.

**Closed by stevegiron** 2015-05-18 20:59 UTC
Labels: Duplicate, Enhancement
