### ISSUE TITLE
Display Element Ordering

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#803] opened 2017-01-15 19:56 UTC
Put the display elements in order so it would make sense as I sequence a song.  After I got it in order I DID a backup, noticed that the imported  LOR timings for that audio track were not showing up, even though I had imported them, then I tried to re-import them and the program crashed.  When I started all over again, all the work of ordering my display elements was gone.  Yes the three backup files are there.  Am I outta luck, or is there a way to retrieve that work?  FYI: using ver 2016.54, Win 7.  Also when I go to audio file 2 will the display elements be in the non-desired order again?

**Comment by AzGilrock** [comment] 2017-01-15 19:59
The problem is doing a backup doesn't help if you didn't do a SAVE before the backup.  Normally you need to create a View which will define your element order.  If you didn't create a View then the order you defined is local to that sequence so it would only be found in the XML file for that sequence.  So you need to look for a backup of the sequence file.  I'm afraid if you never hit SAVE you might not have one unless you have the auto-backup running and it saved a copy.

**Comment by JoelDearing** [comment] 2017-01-15 22:49
Thanks for the quick reply.  I did not save the sequence since I had not sequenced anything and the program crashed.  
On another note: I noticed in the videos from Keith he was able to highlight and delete effects from elements in the sequencer.  I am finding that I can't do that.  Has there been a change?

**Comment by AzGilrock** [comment] 2017-01-15 23:31
Nothing changed related to that.  What are you having trouble doing the selection?  Turn off the timing track and drag a yellow dashed box around to select...that's just one way.  Then hit Delete key or right-click select Delete.

**Comment by JoelDearing** [comment] 2017-01-15 23:44
"Turn off the timing track"  OK, that was a step I had not considered., thanks you.  So I can wrap my brain around that, why would you have to turn off the timing track ?

**Comment by AzGilrock** [comment] 2017-01-16 01:05
You don't have to BUT there are 2 selection modes.  With a timing track active it's cell selection mode so you select cells that are defined by where you have timing marks and without a timing track active its freeform selection mode.  The problem with cell selection mode is if you don't draw any timing marks you have no cells to select so that's why I direct folks to the always works freeform selection mode.

**Comment by AzGilrock** [comment] 2017-01-16 17:48
Don't think there is anything else we can help with on this one so closing.

**Closed by AzGilrock** 2017-01-16 17:48 UTC
Labels: Question
