### ISSUE TITLE
Saving effect presets shows 1 layer regardless of actual number of layers

### ISSUE THREAD

**Issue by stevegiron** [smeighan/xLights#775] opened 2016-12-09 19:07 UTC
v53 Windows

New setup, single model. Regardless of the number of layers saved with a preset, the value shown next to the preset name is [1]

**Comment by AzGilrock** [comment] 2016-12-09 19:09
I created one the other day and thought it stayed a [0].

**Comment by stevegiron** [comment] 2016-12-09 19:41
It's a rating system now. Make a better effect for that value to increase.

**Comment by keithsw1111** [comment] 2017-02-07 18:37
Duplicate of #753

**Closed by keithsw1111** 2017-02-07 18:37 UTC
Labels: Bug - Trivial
