### ISSUE TITLE
JHolmes crash-a-lot Thread

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#605] opened 2016-06-23 21:18 UTC
[xLights_dbgrpt-1755-20160623T171632.zip](https://github.com/smeighan/xLights/files/330824/xLights_dbgrpt-1755-20160623T171632.zip)
[xLights_dbgrpt-1672-20160623T171001.zip](https://github.com/smeighan/xLights/files/330823/xLights_dbgrpt-1672-20160623T171001.zip)

**Comment by AzGilrock** [comment] 2016-06-23 21:21
Maybe we can just leave one issue for you.  The fact is your system just crashes alot and it doesn't really matter what you were doing.

**Comment by jholmes09** [comment] 2016-06-23 21:22
Hahaha! Hi Gil.
Just trying to do my part for the community. I’m sorry if I have become burdensome.
Yeah, however you would like to diagnose issues is great by me! I’ve crashed XLights a LOT this week, it was really surprising. 

From now on shall I just create “Jeff’s Crash Thread?” or something?

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by AzGilrock** [comment] 2016-06-23 21:26
The problem is we need to be able to reproduce the problem or submitting an issue like this is useless.  All you're giving is a crash dump and a short title.  That's not much to go on.  So I'd say unless you can reproduce the crash yourself and tell us the steps to follow there's not much chance we can fix it.  That's why all you'll see is these issues are going to sit here for months until we say they are old and obsolete and close them.  I don't think these issues are global to the community.  Something is wrong in your setup.

**Comment by jholmes09** [comment] 2016-06-23 21:29
Ah I see. 
When you posted on Facebook that you could see all the steps I took before the crash, I assumed that meant I did not need to write out what I did.
How might I go about diagnosing what is wrong in the setup? Do you think its my software configuration or a hardware issue?

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by AzGilrock** [comment] 2016-06-23 21:31
The problem is all the crashes appear to be because you are somehow able to continue doing stuff while it's rendering.  Do you see everything grey out when you render?  Do you know the render is done before you continue working?

**Comment by jholmes09** [comment] 2016-06-23 21:32
Yes, I have learned to wait for the Render Done label at the bottom left to be visible before I continue working.
I also turned off auto-rendering so I can save without issue.

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by jholmes09** [comment] 2016-06-23 21:38
Perhaps we can schedule a time to discuss my system and detail? A remote-access session or scheduled meeting next week or at your convenience?

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by AzGilrock** [comment] 2016-06-23 21:54
All I know is all the debug reports appear to have the same root cause so we don't need multiple Github issues.  Its always a crash during a render operation.  I don't see anything I think I can fix.  Maybe Dan will notice something if he takes a look.  The user is usually the best person to know if there is pattern to the crashing.  I notice you like to work with things in a Dropbox.  Can you try working for a while with everything you need stored on your hard drive?  You have Pictures effects that point to dropbox files.  I personally think that's asking for trouble.

**Comment by jholmes09** [comment] 2016-06-23 21:58
Hey Gil,

Yes I do call it Drop-Box but in actuality the files are all locally stored. The Drop-box is simply syncing occasionally as another backup.
I understand where you are coming from regarding the same issue repeated. The last couple of reports (about layers) were during times I was not rendering, or simply did not know there was some kind of background rendering occurring. 

I am noticing, in general, that the effects are not updating in the preview as instantly as usual. Sometimes they have to cycle through a couple times to update. Could this be a symptom or an issue?

In general, I am taking to avoiding the computer at all times when it is rendering but I would love to determine whether its my layout or my machine.

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by patdelaney** [comment] 2016-06-23 22:06
Jeff I’m wondering if the Syncing is actually putting a temporary lock on the file which is causing the issue. Please turn off Dropbox syncing agent for a while and see if you still have the issue.

 

Pat

**Comment by patdelaney** [comment] 2016-06-23 22:11
I skyped Jeff and he is going to disable the dropbox syncing agent and do some testing.

 

Pat

**Comment by AzGilrock** [comment] 2016-06-23 22:13
I don't think it's the machine.  It's working crazy slow on my laptop.  Anytime you drop an effect or make a change to an effect it spawns a render thread to render that effect.  Usually that happens super fast.  For some reason on this layout you've created it's taking like 1 to 2 minutes just to render a 5 second bars effect.  So if you make a few adjustments to effects it could take forever for it to render and settle down.  Eventually its causing a crash.  It's got my xLights application acting locked up right now.

**Comment by AzGilrock** [comment] 2016-06-23 22:20
I created a new sequence with your layout and it's working great.  I drop effects and they render in like 2 to 3 seconds.  I don't know what you are doing with those other effects that is making things go crazy slow.

**Comment by AzGilrock** [comment] 2016-06-23 22:36
One thing that will help is quit making 40fps sequences.  Is there a reason you need 25ms timing?  That's just gonna double all save and render times and I don't think anyone watching the show is going to notice the difference if you switched to 50ms.

**Comment by jholmes09** [comment] 2016-06-24 19:04
Gil,

I think Pat may have been onto something regarding Drop Box. So far keeping it OFF while programming has helped a lot.
I will continue to do this and see what issues I run into. Regarding 40 FPS, our whole system (from the boards to the lights) is designed for 40 FPS and while I did ask for permission to go to a lower frame-rate, I was told that our incremental testing showed anything under 30 FPS was unacceptable. 

Since our hardware supports it and we’ve found a lower frame-rate causes issues, I’m very grateful that XLights supports it. We’ll deal with the larger file sizes.

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by keithsw1111** [comment] 2016-06-27 11:12
Jeff can we close this now?

**Comment by jholmes09** [comment] 2016-06-27 17:37
Yes. I will reach out to you if I begin crashing the system again. 

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by AzGilrock** [comment] 2016-06-27 18:26
FYI: Users can close their own issues.

**Comment by jholmes09** [comment] 2016-06-27 22:18
Thank you!

Unfortunately, we’re now experiencing crashes again.
I took Pat’s suggestion and turned off DropBox but the crashes continue.
I’ll collect a few .zip files of the debugging as they happen and make note of exactly what I am doing.
If I detect a pattern, I’ll reach out.

Thanks!

Jeff Holmes
Creative & Technical Lead
S4 Lights

m: 925.482.4846
e: jeff@s4lights.com
Skype: JeffHolmesPresents

**Comment by jholmes09** [comment] 2016-07-01 19:05
Per your request, I am returning to the same thread as to not clog up Github.
I've followed all your directions regarding DropBox but today I am unable to open my show directory.
I tried three times: Open XLights, Change Directory (also "Select Show Folder"), Open - Crash

Am I still the problem? Cause if its my computer, I'll get that taken care of. 

Here is the crash report: 
[xLights_dbgrpt-1018-20160701T115558.zip](https://github.com/smeighan/xLights/files/344027/xLights_dbgrpt-1018-20160701T115558.zip)

**Comment by AzGilrock** [comment] 2016-07-01 19:22
Did you delete the comment with the crash report from a few minutes ago?  I got an email about your problem with a crash report in a zip file but I don't see that comment here.

Anyways I can't find anything wrong.  I created a show directory with the files from the crash report and it opens up fine.  The backtrace.txt file appears to indicate it was in the middle of selecting a show directory and then crashed trying to update the perspectives menu.  Do you have the xlights_rgbeffects.xml file from the show directory you were trying to switch to?  That's the one I think had a problem.

**Comment by jholmes09** [comment] 2016-07-01 19:25
Thank you for your quick response.
After I submitted the crash report, I continued testing and found I could not open any directory at all.
I then remembered that a new update had been released so I un-installed XLights and updated to the new edition. This seemed to solve the problem so I deleted the comment as to not bother you. 

Here is the file you requested: 
[xlights_rgbeffects.xml.zip](https://github.com/smeighan/xLights/files/344047/xlights_rgbeffects.xml.zip)

**Comment by jholmes09** [comment] 2016-07-08 18:59
Reoccuring issue when adding layers to sequence. Documented July 6th and repeated twice today. 
See three .zip files. Thanks you! I very much appreciate you looking into these!

[xLights_dbgrpt-998-20160706T131257.zip](https://github.com/smeighan/xLights/files/354912/xLights_dbgrpt-998-20160706T131257.zip)
[xLights_dbgrpt-2367-20160708T115514.zip](https://github.com/smeighan/xLights/files/354915/xLights_dbgrpt-2367-20160708T115514.zip)
[xLights_dbgrpt-2240-20160708T115311.zip](https://github.com/smeighan/xLights/files/354914/xLights_dbgrpt-2240-20160708T115311.zip)

**Comment by AzGilrock** [comment] 2016-07-08 19:08
Do you have a quotation mark in the name of a model?  Looks like I see "24' pixel plane".  Please remove that just to be safe.  Never use "~!@#$%^&*();:<>?/\|][{}`,.'" those type of characters in any type of names.  It's just begging for something like an XML parser to blow up.  Use normal characters and numbers and outside that I'd say spaces, dashes, and underscores are about the only safe characters.

**Comment by jholmes09** [comment] 2016-07-08 19:11
Understood. I have changed the name to "24 ft pixel pine" (without quotations). Thank you.

**Comment by AzGilrock** [comment] 2016-07-08 19:46
What kind of computer are you having problems on?  Do you have any others to try?  If you have a machine that makes a gamer proud you have less problems. :)

**Comment by jholmes09** [comment] 2016-07-08 19:56
I am using a Mid 2015, 15-Inch Macbook Pro.
2.8 GHz Intel core i7
16 GB DDR3 Memory
500 GB Flash Storage (but most files are stored on a G-Tech Thunderbolt Drive)

Graphics auto-switch between:
Intel Iris Pro 1536 MB Graphics
AMD Radeon R9 M370X with 2GB of GDDR5 memory

If you have recommended specs for a future computer purchase, I can put in a request.
I would love a nudge in the right direction!

**Comment by AzGilrock** [comment] 2016-07-08 20:06
So are you running the Mac version of xLights?  I have a MacBook Pro also but I mainly boot it up in Windows7.  I don't recall you ever mentioning which OS you use.

**Comment by AzGilrock** [comment] 2016-07-08 20:08
I've run xLights on my 2009'ish MacBook Pro.  It's a little show but it works.  Now I didn't have that mexapixel object you have.

**Comment by jholmes09** [comment] 2016-07-08 20:08
My apologies for the omission. Mac OSX 10.11.5
I do have Windows 10 on this machine (Bootcamp) but I rarely go over there because the Windows drivers have issues with this type of screen. Everything is extremely tiny.

**Comment by jholmes09** [comment] 2016-08-05 21:35
Yes go ahead.
I will create new issues when I have specific problems.

**Closed** 2016-08-05 21:36 UTC
Labels: Bug - Minor
