### ISSUE TITLE
Effect Jumping Right When Selected

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#488] opened 2016-03-05 20:59 UTC
Release 2016-9
Occasionally when I select the last effect for a model in a sequence within the sequence tab, i.e. the right-most effect, it will jump a variable number (10-20) of timing marks to the right.  Thus it creates a gap between the prior effect for this model or if it is the first effect for the model from the start.  
Then when you select it to move it back to its original location by pressing and holding the left mouse button, as soon as you start to move it to the left it will jump 4-5 timings marks further to the right.  You can eventually get it back to its proper location but it may take 2 or 3 movements of the mouse, left click/hold/move, to get it lined up properly.
This behavior, when it occurs, happens on different models with a sequence.

**Comment by AzGilrock** [comment] 2016-03-06 01:51
This is like a UFO sighting. Gonna need video to prove it.

**Comment by dcwehw99** [comment] 2016-03-06 04:49
Attached is a video you requested.  The video will clearly show the jumping when selecting various models in the sequence but I wasn't able to capture the jumping when moving it back into is original location.  It could be do to the fact I did this on my laptop which has a much slower processor.
You will see at ~ 26 seconds the model Coro-Sars jump 15 timing marks to the right.  At 50 seconds the Strobe model jumps 12 timing marks, At 58 seconds the Rainbow Floods model jumps 4 timing marks and at 60 seconds the Window Frames model jumps 4 timing marks.
Let me know if you have any additional questions or need anything else.

Denny

[Xlights Effect Move.zip](https://github.com/smeighan/xLights/files/160165/Xlights.Effect.Move.zip)

**Comment by AzGilrock** [comment] 2016-03-07 14:21
If its the result of a slower process I won't be able to duplicate.  With all that clicking I'm sure at some point it comes across looking like a click and drag.

**Comment by dcwehw99** [comment] 2016-03-07 19:02
I was doing all that clicking to recreate the problem for you in the shortest possible time.  While I'm doing all that clicking I'm being very careful not to move the mouse; only clicking quickly.  
On a faster processor like my desktop (3.5 MHz) it's even more dramatic but I'm out of town and can't show you the issue of moving it back in place (to the left) and it jumping a few timing marks to the right when you release the mouse button.

**Comment by AzGilrock** [comment] 2016-03-07 20:25
Are you using a real mouse or a trackpad with your finger?  Not sure I'll be able to reproduce this.  To restore the effect position I would recommend you right-click and use Undo instead of trying to drag it back.

**Comment by AzGilrock** [comment] 2016-03-07 23:23
So I learned how to duplicate this every time.  You are doing a small drag whether you thought so or not.  Try it again and do a small drag and it will jump every time.  For it to happen there are special conditions that I noticed in your video.  You were sequencing in a way I normally don't.  You had really long effects and the effects you were clicking on were not fully visible on the screen.  So what I think it happening is when you do a tiny drag the effect is snapping over to center the mouse in the total length of the effect not just the visible portion.  If you zoomed out before you did these selection it won't happen.  I gotta think about that one because everything was designed based on you dragging items that are visible which it true in most cases except where you have a really long effect.

**Comment by dcwehw99** [comment] 2016-03-07 23:25
Gil,
1. I'm using a wireless optical mouse on both machines.  Two different hardware vendors.
2. If I cause this movement issue on several different models and then do a "right-click and Undo", it does as you said repeatedly until I do the last one.  After the last "Undo" It produces a "crash report" and terminates the application.  Obviously that's another issue.

In the mean time I had some time this afternoon to do some more testing and have some additional information and the particular condition that makes the "jumping" happen on the first click instead of clicking and clicking away like I did in the video.  Here are the specific conditions necessary.
1. You must "zoom" in and cause the effect for the model to span across more than a single screen.  If everything fits on a single screen like after opening the sequence initially it doesn't exhibit the "jumping" behavior.
2. After "zooming" in in step 1 above, scroll to the end of the effect you want to click on.
3. Contrary to what I said above initially, I discovered that I was moving the mouse ever so slightly when I clicked on the effect.  Clicking on the effect with any unintended movement before releasing the button in any direction, up, down, left or right causes the "jumping".  The clicking I'm talking about is pressing and releasing the button as quickly as possible not a click, hold and release action.

For what it's worth, I noticed that the first timing mark doesn't start exactly at the beginning, i.e. there is a small gap from the beginning to the first timing mark.  All the effects start at the first timing mark and not at the beginning of the sequence.

The other "jumping" issue happens as you start to move the effect back to its previous spot.  If you press and hold the left mouse button down an start to move the effect to the left it "jumps" 4-5 timing marks back to the right.  This jumping happens as I still have the mouse button pressed and I'm starting to move the mouse left.

Since were on movement issues I noticed in any move of an effect the movement of cursor is about twice the rate of the effect you are moving.  By that I mean, it I click on an effect icon I expect the pointer to stay on the effect icon as it is being moved.  What actually happens is the cursor moves about twice as far as the effect that is being moved.  Thus it gradually moves further and further to the right of the effect icon as you move it to the right.

Thanks
Denny

**Comment by AzGilrock** [comment] 2016-03-07 23:29
Sorry beat you to it by 2 minutes. :)

**Comment by dcwehw99** [comment] 2016-03-08 00:24
That you did!  I shouldn't have proof-read it before I sent it and I would have beat you to it.

**Comment by AzGilrock** [comment] 2016-03-08 02:21
Ok about to checkin the fix for this.  Thanks for finding it.  I'll admit I was skeptical at first but that's mainly when I get descriptions like "occasionally" the software does something because given the same conditions and inputs the software always does the same thing.

**Closed** 2016-03-08 02:22 UTC
Labels: Bug - Trivial
