### ISSUE TITLE
Xlights crashing importing skulltronix/vsa routines

### ISSUE THREAD

**Issue by skulltronix** [smeighan/xLights#1188] opened 2018-07-06 18:20 UTC
I'm getting repeated crashing when importing vsa routines. This worked on .18

[xLights_dbgrpt-9032-20180706T111501.zip](https://github.com/smeighan/xLights/files/2171552/xLights_dbgrpt-9032-20180706T111501.zip)

**Comment by keithsw1111** [comment] 2018-07-07 01:17
Ping me or Gil the VSA and i can try to reproduce it

**Comment by skulltronix** [comment] 2018-07-07 13:45
https://www.dropbox.com/s/34sbt5zf3p3shdr/PiSkullOpenJingleBellRockRev5.vsa?dl=0

**Comment by keithsw1111** [comment] 2018-07-07 14:54
Ok ... so there was a problem which I have fixed and it now imports ... I am not sure it is working as expected but at least it isnt crashing. If you need it before .22 comes out you can get it here for the next 12 hrs or so. https://www.dropbox.com/sh/lu5p6pizjarvjas/AACZpCFWm7whvMQSO4gtyiTpa?dl=0

**Comment by AzGilrock** [comment] 2018-07-07 15:01
I've been checking out the VSA import this morning and I'm pretty sure its all screwed up.  I went back to 2017.7 32-bit version and imported my "I Like Nightmares" VSA file and its perfect.  I picked that version because it was near the time I did the video of the feature.  I do the same import, render, playback in 2018.20 and the preview of the skull is jumping all over the place so its f'ed up.

**Comment by AzGilrock** [comment] 2018-07-07 15:02
I don't think the import changed but with all the value curve and model blending changes it screwed up how this works.

**Comment by keithsw1111** [comment] 2018-07-07 15:30
The format issues became a problem when we converted to 64 bit.

**Comment by AzGilrock** [comment] 2018-07-07 15:38
Well if you hadn't started the size_t initiative I would have made it an int. :)

**Comment by AzGilrock** [comment] 2018-07-07 16:58
First thing Jerry is the current xLights importer doesn't work if you disable tracks in between the active tracks.  The reason is because when I read in the track data the file still has an entry for those tracks so it causes a misalignment when trying to match up the track number to the line from the dialog.  There will need to be a fix for that.  Currently you can just go in and check the boxes in VSA to activate those tracks and then your import dialog should look like this:
![image](https://user-images.githubusercontent.com/2024669/42412995-4efbb662-81cc-11e8-9afe-24e5ef8fff56.png)

**Comment by AzGilrock** [comment] 2018-07-07 17:04
Technically the topic of this issue is fixed.  I'm looking into other VSA import issues so I'll close this one and open a new issue that has an appropriate title and description.

**Closed by AzGilrock** 2018-07-07 17:04 UTC
