### ISSUE TITLE
Crash in sequence timeline - 4.1.0

### ISSUE THREAD

**Issue by blehke** [smeighan/xLights#249] opened 2015-06-01 21:27 UTC
I had the same thing when I tried from my previous 4.0.35 setup and can reproduce as follows.  Essentially can't do anything, so I've got to imagine someone else has seen this... that or I'm completely missing something basic.  
From scratch:
Add E1.31, 1 universe, 512 channels, save
Layout > Models > Add > Single line, all defaults
Sequencer > New > Animation > 50ms
Edit Display Elements > Add models > select your model
Left click in New Timing area --> CRASH

backtrace.txt:

0x005e05d8              Effect::SetProtected(bool)
0x005e94df              EffectsGrid::CheckForPartialCell(int)
0x0076a0df              _Unwind_SjLj_Register
0x6a236152 ZN16wxEventHashTable11HandleEventER7wxEventP12wxEvtHandler
0x6ac7b919 ZN9LexerBaseC2Ev
0x6a33bff4 ZN8wxWindow14InitMouseEventER12wxMouseEventiij
0x75e3717a IsWindow
0x75e36d51 GetThreadDesktop
0x6a39ccfc ZN7wxFrame21MSWDoTranslateMessageEPS_P6tagMSG
0x6a1e12a3 ZNK18wxMSWEventLoopBase7PendingEv
0x6ac7bbcf ZN9LexerBaseC2Ev
0x6a0852a8 ZN16wxAppConsoleBase14CreateMainLoopEv
0x6a244713 Z21wxGetPasswordFromUserRK8wxStringS1_S1_P8wxWindowiib
0x6a244be7 Z7wxEntryP11HINSTANCE__S0_Pci
0x759af489 msize

Crashed thread id: 2B08

**Comment by stevegiron** [comment] 2015-06-01 21:35
Appears to be a dupe of #246

**Comment by stevegiron** [comment] 2015-06-01 21:42
I followed your steps and I can get it to crash too.
To make it not crash until a fix is implemented is to manually add timing marks, or import a set of timing marks then click on the grid and no crash will occur.

**Comment by blehke** [comment] 2015-06-02 00:39
Didn't see that just from reading titles - sorry.

**Comment by mikejk67** [comment] 2015-06-03 03:08
I've gotten 4.10 to crash (as well as 4.034 and 4.035) with timing track added, by adding a star model (single channel white, 1 strand, 35 bulbs,  5 points) every time. Works with other models and if you add the star as a single item group is OK. I tried different number of points (no difference). Change the model to wreath or line is OK too.

**Closed** 2015-06-03 03:33 UTC
Labels: Bug - Minor
