### ISSUE TITLE
Blue Screen Of Death

### ISSUE THREAD

**Issue by JoelDearing** [smeighan/xLights#804] opened 2017-01-16 01:05 UTC
I did this twice and got the same result
Win 7 and xLights 2016.54
Clean Boot
Loaded xLights
Set up tab is active tab
Across menu bar selected Tools
Select Test
Click LOR Com3 at 57600 [1-510] (1-510) LOR
Click Output to lights
Green light is now solid on LOR Gen 3 CTB16PCG3 controller
Click "Background" radio button
Raised and lowered slider labeled "background intensity"  (and did not get a light to light up on the controller
Clicked the red X in the upper right of the window to close the Test Lights screen, and the computer went to Blue Screen Of Death and then rebooted

**Comment by AzGilrock** [comment] 2017-01-16 01:08
Sorry about the problem but its not new.  I just spent a lot of time yesterday troubleshooting this same issue and fixed it.  So you just need to wait for next release unless you are building the code from scratch you can just pull the latest checkins.  Duplicate of #797.

**Closed by AzGilrock** 2017-01-16 01:08 UTC
