### ISSUE TITLE
effects moving during render

### ISSUE THREAD

**Issue by PaulB201** [smeighan/xLights#1279] opened 2018-10-16 04:33 UTC
certain songs move effects enclosed is the file most affected by it. 
[Stille Nacht 2018.zip](https://github.com/smeighan/xLights/files/2481435/Stille.Nacht.2018.zip)

**Comment by keithsw1111** [comment] 2018-10-16 10:54
Can you be more specific? Which effects? Maybe make us a video showing us what you mean

**Comment by deplanche** [comment] 2018-10-16 12:17
Keith - I was in the Zoom meeting when they were discussing this problem, but was only half paying attention.  I think the problem was on the bottom few models, and when he rendered the solid white (which was being shown for the ON effect on those models) turned black in some locations, and the end seemed to stop short of the rest of the effects - both of these taking place when he hit render.  In taking a look at the sequence, it seems like it might just be the shimmer that he has on those models, which after a render does make it look like it changes from a solid white (that looks like an always on), to intermittent black and white (for the shimmer).  The end time of the effect doesn't actually appear to be changing, but because the effect goes from being solid to on-off for the shimmer, it give the illusion that  it is changing end times.

**Comment by AzGilrock** [comment] 2018-10-16 13:50
Well we know its impossible for a render to cause any effects to move.  So an illusion that its moving because you are staring at the data as it renders.  I can easily explain that if you click on an effect and it renders you see the entire effect then you do a full render and another effect renders / blends its data onto the same channels.  I bet if you delete all other effects during the same time frame that effect will not "move".

**Comment by keithsw1111** [comment] 2018-10-17 09:37
I dont see the issue ... the twinkle looks different every time it renders but that is by design.

As Gil says there is pretty much no way this could be true so i am closing this. Feel free to reopen it if you can attach a video that demonstrates the problem.

**Closed by keithsw1111** 2018-10-17 09:37 UTC
