### ISSUE TITLE
xSchedule Web Interface Fail (Linux)

### ISSUE THREAD

**Issue by jholmes09** [smeighan/xLights#1257] opened 2018-09-27 17:09 UTC
**xLights 2018.33
Ubuntu 18.04.1 LTS**

When running xSchedule on Ubuntu 18.04.1 LTS, you can start the program once without error.
However, if you close xSchedule and try to re-open, this error pops up:

"Error starting web server. You may already have a program listening on port XX" (happens on any port).

Changing the port # and then restarting the program will fix the issue _only_ for that one restart. If you close the program again, the error comes back and you have to change the port number again.

No other computers are on the network. No other processes are listening on the ports that I jump around to. It seems like xSchedule is tripping _itself_ up.

I am available to compile Linux branches to help diagnose this issue.

**Comment by keithsw1111** [comment] 2018-09-27 19:10
Did the prior instances of xSchedule close completely (the process is gone) ... it sounds like as each instance starts it tries to listen on the port and the prior process is still there with the port open. The other possibility is the we are not closing it properly and the OS is not cleaning it up when the process dies. That seems unlikely.

**Comment by jholmes09** [comment] 2018-09-27 21:01
I will look into that to confirm. However, I do not believe it is a process issue because the error will occur even if I reboot in-between the first and second time I open xSchedule. The first time works. The second time errors.

**Comment by keithsw1111** [comment] 2018-09-27 21:06
Are you able to list which processes are listening to which ports? 

https://www.cyberciti.biz/faq/what-process-has-open-linux-port/

**Comment by keithsw1111** [comment] 2018-09-27 22:29
You may need different options as that netstat dump does not show the port number on each line.

**Comment by cjd** [comment] 2018-09-27 22:31
I can confirm the behaviour - as long as something has connected to the web port it stays open for a while after xSchedule closes.
Checking the logs it doesn't look like HttpServer::Stop() is being called (no message such as "closed server on %s:%u"
[xSchedule_l4cpp.log](https://github.com/smeighan/xLights/files/2426121/xSchedule_l4cpp.log)

**Comment by keithsw1111** [comment] 2018-09-27 22:33
Happy to look into why it isnt closing but why doesnt the operating system reclaim it when the process dies?

**Comment by cjd** [comment] 2018-09-27 22:34
The process is gone (nothing shows up in 'lsof -i tcp:<port>' - but the socket is held open by browser until timeout so it can not be reaped properly

**Comment by jholmes09** [comment] 2018-09-27 22:37
Hi Chris! So glad you could join us :).
Here is my netstat.txt if you still need...but somehow I don't think you do ;)

[netstat.txt](https://github.com/smeighan/xLights/files/2426138/netstat.txt)

**Comment by keithsw1111** [comment] 2018-09-27 22:37
That makes no sense ... so because some client somewhere has a connection to your web server and you web server crashes you cant restart the web server until a timeout occurs so you can listen on the port. That cant be true ... can it?

**Comment by cjd** [comment] 2018-09-27 22:56
Agree - something odd is occurring - but that is just what I found through experimentation.
If I never connect to the web server port - the problem doesn't occur.
It happens even if I kill xschedule and associated processes/LWPs

**Comment by cjd** [comment] 2018-09-28 01:07
Looking at the system - there are a number of sockets held open in TIME_WAIT state waiting for client side to reset/close or timeout to occur

**Comment by jholmes09** [comment] 2018-09-28 02:39
So would it make sense to add something in xSchedule startup that cleared all those sockets or pending states?

Sounds like a similar crash issue as when xSchedule things another instance is running because it didn’t reset the PID file due a crash. I usually just go delete that file in the home directory and it works again. 

Perhaps a startup cleaning needs to be implemented?

**Comment by cjd** [comment] 2018-09-28 04:41
If we add wxSOCKET_REUSEADDR to the socket creation ie:
_server = new wxSocketServer(_address, wxSOCKET_REUSEADDR);
Then it works fine - but not sure the affect on windows/osx of doing so

**Comment by cjd** [comment] 2018-09-28 04:42
diff --git a/xSchedule/wxHTTPServer/server.cpp b/xSchedule/wxHTTPServer/server.cpp
index ec3bffd8..8d3fc3cc 100644
--- a/xSchedule/wxHTTPServer/server.cpp
+++ b/xSchedule/wxHTTPServer/server.cpp
@@ -56,7 +56,7 @@ bool HttpServer::Start(const HttpContext &context)
     logger_base.info("starting server on %s:%u...", (const char *)_address.IPAddress().c_str(), _address.Service());
 
        // Create the socket
-       _server = new wxSocketServer(_address);
+       _server = new wxSocketServer(_address, wxSOCKET_REUSEADDR);
 
        // We use IsOk() here to see if the server is really listening
     if (!_server->IsOk())

**Closed** 2018-09-28 22:06 UTC
