### ISSUE TITLE
"First Frame" & "Last Frame" Button Issue

### ISSUE THREAD

**Issue by dcwehw99** [smeighan/xLights#544] opened 2016-04-20 21:14 UTC
2016.20
If you press the "First Frame" or "Last Frame" buttons the slider at the bottom of the screen is moved to the corresponding position, i.e. the beginning or ending of the sequence but the grid and waveform are not refreshed to the corresponding location.  You must move the slider slightly to have it re display the "First Frame" or "Last Frame" of the sequence.

Thanks
Denny

**Comment by stevegiron** [comment] 2016-04-20 21:16
Confirmed. with .19 too.

**Comment by AzGilrock** [comment] 2016-04-20 22:20
Can you do me a favor and check whether changing focus to another application and back fixes that button behavior?  We have a boatload of buttons not working right that are all due to the same reason and we keep getting a new issue submitted for every button.  I know this used to work is why I ask.

**Comment by stevegiron** [comment] 2016-04-21 00:24
Changing the focus/app/tab does not change the position of the wave form.
Here is the result of pressing the first frame button. The time shows
correctly, and the play works from the start. The display does not match
though.

[image: Inline image 1]

**Comment by AzGilrock** [comment] 2016-04-21 00:27
Changing focus won't move the wave form.  What I mean is make sure the focus switch it done before hitting the toolbar button.  The closing of any floating panel can put the focus in a bad state that make all toolbars have a chance to not work correctly.

**Comment by stevegiron** [comment] 2016-04-21 00:44
Here's an addition to that screen. If you highlight a section of the wave
for editing/playback purposes, then highlight a section of the timeline for
instant playback, the first highlight does not go away.

[image: Inline image 1]

**Comment by stevegiron** [comment] 2016-04-21 00:45
FYI Highlighting wav to wav sections does not exhibit this same behaviour.

**Comment by AzGilrock** [comment] 2016-04-21 02:47
None of those images you are posting are showing up for me.  But based on your description about highlighting the wave then the timeline that's how it's supposed to work.  I copied the behavior from audacity.  It allows you to select a section of the waveform and play it.  Then highlight a section of the timeline which will autoplay and then you can hit the play button and it will jump playback back to the beginning of the selected wave section.  Go try it in Audacity.

**Comment by AzGilrock** [comment] 2016-04-21 02:51
In any case the original issue is real and not part of the focus issue.  I checked and the buttons worked fine in 2016.4 so it got broke along the way.

**Comment by stevegiron** [comment] 2016-04-21 03:03
Here is the second attachement again. Here you can see the wav form and timeline highlighted at the same time in different sections.
![image](https://cloud.githubusercontent.com/assets/10568498/14696812/004a09a8-0733-11e6-9110-477b20620d96.png)

**Comment by AzGilrock** [comment] 2016-04-21 03:07
Yes that's correct.  Just like Audacity like I said.

![audacity](https://cloud.githubusercontent.com/assets/2024669/14696854/621aed00-0733-11e6-8bc0-97736da32c8f.jpg)

**Comment by AzGilrock** [comment] 2016-04-21 03:56
So I've narrowed it to works fine in 2016.15 and is broke in 2016.16 and above.

**Comment by AzGilrock** [comment] 2016-04-21 04:04
Ok found the issue and fixed it.  The checkin titled "Fix some scrolling issues on Windows" jumped out at me.  The grid scrolling event handler got moved to a different class so the handlers for these buttons were now posting the event to the wrong window class.  In case inquiring minds wanted to know.

**Closed** 2016-04-21 04:06 UTC
Labels: Bug - Trivial
