### ISSUE TITLE
Exporting Effect Model as *.eseq does not honor Sequence Time

### ISSUE THREAD

**Issue by ebrady1** [smeighan/xLights#465] opened 2016-02-08 18:57 UTC
Whenever I export an effect model as a Falcon Pi Effect sequence *.eseq, it does not honor the time that I have the sequence length set to.  

In my testing, I set the sequence length to 2 seconds, created a simple pin wheel effect, and then exported it as an eseq.     The resulting file size is set to 4,147,220 bytes for a 48x48 RGB Matrix.  Working out the math, this translates to:

Assuming 6912 channels for 48x48 Matrix (48x48x3)

4,147,220 - 20 (Header Length) = 4,147,200
4,147,200 / 6912 (# of Channels) =  600 Periods
600 x 50ms = 30 seconds.

It appears eseq effect models are being saved as a 30 second file, instead of the 2 seconds I have the sequence length set to.

I have looked at the ouput file using a hex editor and confirmed that there is only 2 seconds of data followed by 28 seconds of darkness.     I was able to recreate on 2016.05 and 04.03.

Not sure if this is a bug, or by design, but wanted to point out.

**Comment by AzGilrock** [comment] 2016-02-09 01:52
I can't reproduce.   I did Export Model with a 30 second animation and got a 127KB eseq file.  Then I opened Sequence Settings and changed the sequence length to 3 seconds, closed the dialog, and executed another Export Model and got a 13 KB eseq file.

**Comment by ebrady1** [comment] 2016-02-09 02:44
I did see the behavior fairly consistently on my end.    I decided to experiment some and created a new setup with new controller and new Model. Everything was set exactly as before, the export now seems to be the correct size.

**Comment by AzGilrock** [comment] 2016-02-09 13:53
Yeah but I just fixed the problem with the sequences not adjusting to sequence length changes 10 days ago.  That change was put into 2016.3.  If you hadn't said you tested in 2016.05 I would say you just needed the new version.  I have to question did you really do a good job testing this in version 2016.05 because yes it was a problem in version 4.03.

**Comment by AzGilrock** [comment] 2016-02-10 19:17
I believe this was fixed in 2016.3.

**Closed by AzGilrock** 2016-02-10 19:17 UTC
Labels: Bug - Trivial
